### ISSUE TITLE
Error while update to FTL 5.3.4 ..... 

### ISSUE THREAD

**Issue by roe1974** [pi-hole/FTL#1003]
### Versions

- Pi-hole:  5.2.2
- AdminLTE:  5.2.2
- FTL:  5.3.3

### Platform

- OS and version:  Raspian Buster

- Platform:  PI4B

After performing an:

PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -up

.. i get an error with:

 Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-armv7-linux-gnueabihf not found

br, Richard

**Comment by DL6ER** [comment]
Hey Richard,

you were too fast, the automated building system was just uploading to Github.

Please try again.

**Comment by roe1974** [comment]
ok ... works now 👍 thx !
