### ISSUE TITLE
FTL/DNS Constantly Crashes 

### ISSUE THREAD

**Issue by mitchross** [pi-hole/FTL#1008]
### Versions

   Pi-hole version is v5.2.2 (Latest: v5.2.2)
  AdminLTE version is v5.2.2 (Latest: v5.2.2)
  FTL version is v5.3.4 (Latest: v5.3.4)

### Platform
Welcome to Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-58-generic x86_64)

### Expected behavior

Dont crash

### Actual behavior / bug

DNS and FTL Stops "DNS service not running"

### Steps to reproduce

After a while, can be seconds to minutes to hours, the system stops responding.
The following appears as the last line in the pihole-FTL.log each time:

   [2020-12-28 13:27:00.454 7914M] Resizing "FTL-queries" from 700710912 to (10952704 * 64) == 700973056 (/dev/shm: 701.2MB used, 1.3GB total)
   [2020-12-28 13:27:13.475 7914M] Resizing "FTL-queries" from 700973056 to (10956800 * 64) == 701235200 (/dev/shm: 701.5MB used, 1.3GB total)
   [2020-12-28 13:27:16.016 7914M] FATAL: realloc_shm(): Failed to resize "FTL-queries" (86) to 701235200: Success (4)

## Debug Token

- URL:  https://tricorder.pi-hole.net/mk4jdjwj8e

**Comment by DL6ER** [comment]
Ah, thanks. I see that we made a small mistake when swapping `fallocate()` by `posix_fallocate()` for compatibility with old kernels. While `fallocate()` returned a negative number and set `errno` to point at the error (4 = Interrupted by signal), `posix_fallocate()` does something else as `man posix_fallocate` tells us:
> **RETURN VALUE**
>         posix_fallocate()  returns zero on success, or an error number on fail‐
>         ure.  Note that errno is not set.

Please try if
```
pihole checkout ftl 
```
fixes the issue you're seeing.

**Comment by mitchross** [comment]
Turns out my VM only had 1 gig ram , I bumped it up and fixed the issue.

**Comment by DL6ER** [comment]
Thanks for coming back to us with the reason
