### ISSUE TITLE
pihole-FTL.db size?

### ISSUE THREAD

**Issue by rrrevin** [pi-hole/FTL#1011]
### Versions
  Pi-hole version is v5.2.2 (Latest: v5.2.2)
  AdminLTE version is v5.2.2 (Latest: v5.2.2)
  FTL version is v5.3.4 (Latest: v5.3.4)

What is the "expected/estimated" size of the pihole-FTL.db file? Mine is almost 4GB.. is this normal?

`4064220 -rw-r--r--   1 pihole pihole 4161757184 Jan  3  2020 pihole-FTL.db
`

**Comment by rrrevin** [comment]
I just found this..
https://docs.pi-hole.net/ftldns/configfile/#maxdbdays

Going to drop that value to 90 and see what happens.

**Comment by DL6ER** [comment]
> What is the "expected/estimated" size of the pihole-FTL.db file? 

That's a question which cannot be answered right away. It depends on the number of queries you're seeing in your network. For comparison, my database at home is about  500MB and I have roughly 40,000 queries per day. However, I have been traveling a lot within the last year (yeah, despite Covid19...) and this has reduced my activity on weekends. There is no general rule you can give here.

How many queries do you have in your database? Try
```
sqlite3 /etc/pihole/pihole-FTL.db "select count(1) from queries;"
```
For me, the result is `8,291,526` (`,` added for readability).

> Going to drop that value to 90 and see what happens.

Note that the database will not reduce in size, it will just reuse the existing space. Look for the `SQL` command `VACUUM` if you need to retain the space.

**Comment by rrrevin** [comment]
Just beat me to it. Ran the count().. 61,675,187.
Was coming back to ask exactly about vacuum.
Would it be possible to add a DB vacuum interval to pihole-FTL.conf to do specifically that?

**Comment by DL6ER** [comment]
> How often does this removal run?

Once an hour (at every full hour sharp).

> Would it be possible to add a DB vacuum interval to pihole-FTL.conf (once/month?)

No, this wouldn't make sense. The much better idea is to limit the growth of the database to a certain level. This is done by setting `MAXDBDAYS`. The problem with a periodic `VACUUM` is that this instruction takes **a lot** of time as it reduces the database size by rewriting the entire database. This to ensure there are no gaps in between. In addition, all index tables have to be recomputed as the content may have moved. This is a lot of effort for, in the end, no real gain. The database will always take the space it needs to store all the queries. Even when `VACUUM` would ensure the size is minimal, tests we ran a few years ago showed that the database would still require about the same amount of space, +/- a few megabytes after every `VACUUM` run.

You can do it once manually if you need the space now. FTL will wait to store the queries while the database is blocked with your operation and store the history once you're done with them.

**Comment by rrrevin** [comment]
Resolution:

- Change value of maxdbdays to 60
- wait for ftl to do it's cleanup on the hour
- showdown ftl
- run "sqlite3 pihole-FTL.db vacuum"
- wait.. wait.. wait..
- File is now 1.2GB from 4GB.

I'll keep playing with the maxdbdays and see what I really need.
