### ISSUE TITLE
Do not install pihole-FTL in /usr/bin/

### ISSUE THREAD

**Issue by autostatic** [pi-hole/FTL#1012]
Only packages from the official repositories of the OS itself should place binaries in `/usr/bin/`. Third party providers should place their binaries in `/usr/local/bin/` or in the case of pihole maybe even `/opt/pihole/bin/`. The rationale behind this is that files in `/usr/bin/` can be overwritten by the OS' package managers.

**Comment by jfb-pihole** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our Discourse Forum.
