### ISSUE TITLE
MAXDBDAYS overflows

### ISSUE THREAD

**Issue by iBotPeaches** [pi-hole/FTL#1021]
### Versions
- Pi-hole:  `v5.2.2 (Latest: v5.2.2)`
- AdminLTE:  `v5.2.2 (Latest: v5.2.2)`
- FTL:  `v5.3.4 (Latest: v5.3.4)`

### Platform
- OS and version:  `Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux`
- Platform:  Pi

### Expected behavior

I want to keep queries forever. I blog every year of the combined stats, but every year it turns out I lose data. This year it was because my set value of `99999` which I thought would just never delete data until whatever 9999 / 365 years is. I'd expect my database to grow forever until it becomes so large I have different issues.

```
[2021-01-15 10:59:00.830 21964/T21968] Notice: Database size is 1171.66 MB, deleted 1108 rows
[2021-01-15 11:01:49.020 21964M] Resizing "FTL-strings" from 180224 to (184320 * 1) == 184320 (/dev/shm: 12.3MB used, 483.5MB total)
[2021-01-15 11:24:54.055 21964M] Resizing "FTL-dns-cache" from 143360 to (9216 * 16) == 147456 (/dev/shm: 12.3MB used, 483.5MB total)
[2021-01-15 11:59:00.220 21964/T21968] Notice: Database size is 1171.91 MB, deleted 1354 rows
```

```
pi@raspberrypi:~ $ cat /etc/pihole/pihole-FTL.conf | grep 'MAXDBDAYS'
MAXDBDAYS=99999
```

Looking back maybe I should have picked a value that is less crazy.

### Actual behavior / bug

Is this just my fault for a dumb too high value? Would you accept a patch for like `-1` and the check is entirely removed? I see that could be added [here](https://github.com/pi-hole/FTL/blob/66919f2aa07fedc77e1c964d4d31aab0979e1896/src/database/query-table.c#L272)

### Steps to reproduce

1. Set `MAXDBDAYS` to `99999`
2. Wait a year.
3. Notice that values are being deleted despite setting a high `MAXDBDAYS`
4. See log

## Debug Token

- URL:  https://tricorder.pi-hole.net/9qhkykv5i6

**Comment by DL6ER** [comment]
Ah, yes,

`99999` days (= `3153568464000` seconds) is clearly too much, I have not anticipated someone trying such numbers :-)

> Would you accept a patch for like `-1` and the check is entirely removed?

Sure, however, you need to change this bit as well to accept the negative `-1`:

https://github.com/pi-hole/FTL/blob/66919f2aa07fedc77e1c964d4d31aab0979e1896/src/config.c#L129-L142

Just make that a `if(value >= 0 || value == -1)` and add a
``` c
if(config.maxDBdays == 0) 
	logg("   MAXDBDAYS: --- (DB disabled)"); 
else if(config.maxDBdays == -1) 
	logg("   MAXDBDAYS: Database cleaning disabled"); 
else 
	logg("   MAXDBDAYS: max age for stored queries is %i days", config.maxDBdays); 
```
or something silimar

**Comment by jfb-pihole** [comment]
Also, make sure you have adequate space on the storage media for the ever-growing database.

**Comment by yubiuser** [comment]
And add a hint in the documentation repo ;-)

**Comment by DL6ER** [comment]
Pi-hole v5.5(.1) has been released.
