### ISSUE TITLE
Unable to update to Pihole-FTL 5.4

### ISSUE THREAD

**Issue by stevehoek** [pi-hole/FTL#1025]
From previous release version

[✓] Detected ARMv7 processor (with hard-float support)
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (22) The requested URL returned error: 404 Not Found
  [✗] Downloading and Installing FTL
  **Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-armv7-linux-gnueabihf not found**
  [✗] FTL Engine not installed

**Comment by DL6ER** [comment]
Please try again, the binaries were just uploaded to Github when you tried to update.

**Comment by stevehoek** [comment]
It works... I see the other component updates are now available as well... I guess I was too fast on the trigger!
