### ISSUE TITLE
FTL 5.5.1 crashes randomly on RPi 4

### ISSUE THREAD

**Issue by rhmceuen** [pi-hole/FTL#1042]
### Versions

  Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is v5.3.1 (Latest: v5.3.1)
  FTL version is v5.5.1 (Latest: v5.5.1)

### Platform

- PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
Router: ASUS RT-AC66U B1 running Merlin 384.19

- Raspberry Pi 4  

### Expected behavior

_FTL should not crash

### Actual behavior / bug

_For unknown reasons, FTL crashes randomly.  

### Steps to reproduce

Allow Pihole to run for a period of time.  FTL will fail, but interface and Pi remain responsive.  Restarting Resolver restores operations.

## Debug Token

- URL:   https://tricorder.pi-hole.net/7hblujatyh

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_The offending pihole-FTL.log.1 is attached here:  https://tricorder.pi-hole.net/n4aocqkh3h

**Comment by Zelo72** [comment]
Same Issue on RPI4 since FTL 5.5.1. Crashing sometimes at midnight 0:00. At the next crash i will generate a fresh debug log.

Last crash 2 days ago, debug log generated after reboot and 1 day uptime:  https://tricorder.pi-hole.net/gte6wpyi9l

**Comment by DL6ER** [comment]
@rhmceuen I checked your log and it seems like you had several `pihole-FTL` instances running at the same time. At least, there are a lot more `started` than `terminated` (or `crashed`) messages in the log which is typically suspicious. Did you manually send some KILL signals to FTL?

@Zelo72 The debug log looks fine, there is no sign of a crash anywhere left. Would be good if you can also check `/var/log/pihole-FTL.log` next time you experience an issue.

**Comment by rhmceuen** [comment]
There were no manual KILL for FTL.  I did use the "restart DNS resolver" as it appeared to restore operations.  I don't understand it's workings, but if FTL was indeed still running then perhaps it added another instance?

I do keep the Raspian up to date with "apt update" and "apt full-upgrade".  I don't stop pihole when doing upgrades.  There may be occasions where the update process KILLs a process.

Are there appropriate diagnostics steps I can take when the pihole is in a failed state?  I usually want to return to operating as soon as practical.  That usually destroys useful information.

**Comment by DL6ER** [comment]
You could copy the last lines of `/var/log/pihole.FTL.log` and `/var/log/pihole.log`. The output of `pgrep -lw pihole-FTL` may be interesting as well.

**Comment by rhmceuen** [comment]
Will do in the future.  I believe the tail of pihole.FTL.log is included with the pihole_debug.log.  I will use the pgrep -lw pihole-FTL in the future.

**Comment by rhmceuen** [comment]
Interesting.  I ran it on a currently operating pihole.  I'm assuming that there should only be one instance running?  Here are current results:
pgrep -lw pihole-FTL
587 pihole-FTL
588 pihole-FTL
589 pihole-FTL
590 pihole-FTL
591 pihole-FTL
592 pihole-FTL
593 pihole-FTL

**Comment by DL6ER** [comment]
That's actually fine. The `-w` option also lists all the individual threads. As FTL is a heavily multi-threaded application, this is expected. As they are immediately following on each other, they will correspond to the same process. `pgrep -l pihole-FTL` should not show these.

Other tools, such as `htop` can reveal their relationship:
![Screenshot from 2021-01-26 21-34-25](https://user-images.githubusercontent.com/16748619/105902024-5f5abe80-601e-11eb-9884-ee2482477362.png)

**Comment by rhmceuen** [comment]
Thanks for info.  I may be confusing the failure of a DNS lookup with FTL failing.  I started this issue when I was looking through the various logs and saw the indication in the FTL that it had crashed and to open an issue here.  That may not be the case.  I'll await a new version of piHole.  Perhaps my issue will resolve and I can get back to stable operating.  I believe this issue should be closed at this point.
