### ISSUE TITLE
Pie chart percentages add up to more than 100 %

### ISSUE THREAD

**Issue by KommX** [pi-hole/FTL#1056]
### Versions

- Pi-hole version is v5.1.2 (Latest: v5.1.2)
- AdminLTE version is v5.1.1 (Latest: v5.1.1)
- FTL version is v5.2 (Latest: v5.2)

### Platform

- OS and version: Raspbian GNU/Linux 10 (buster)

- Platform: Raspberry Pi

### Expected behavior

The percentages in the mouseover tool tips of the pie charts should add up to (roughly) 100 %.

### Actual behavior / bug

The percentages in the mouseover tool tips of the **Queries answered by** pie chart adds up to more than 100 %.

### Steps to reproduce

1. Go to the main dashboard
2. Hover over the three sections **blocklist**, **cache**, **localhost** of the **Queries answered by** pie chart.
3. Calculate the sum of the three percentages.
4. The sum is bigger than 100 %, see screenshots, in my case 109

## Debug Token

- URL:  https://tricorder.pi-hole.net/89k3p725sy

### Screenshots

![blocklist](https://user-images.githubusercontent.com/7859245/96974926-1fb1a180-151a-11eb-94f4-475f086c86b3.png)
![cache](https://user-images.githubusercontent.com/7859245/96974928-20e2ce80-151a-11eb-936b-664fa8540ab4.png)
![localhost](https://user-images.githubusercontent.com/7859245/96974929-20e2ce80-151a-11eb-9aea-87b609b00158.png)

**Comment by DL6ER** [comment]
Proposed fix is https://github.com/pi-hole/FTL/pull/1057

**Comment by Daxtorim** [comment]
@DL6ER 
> The GC function keeps all the internal counters consistent

Do queries with status types `QUERY_RETRIED` and `QUERY_RETRIED_DNSSEC` increment `counters->forwarded` at some point that I missed? Because they certainly do **not** increment the counter when being read from the database:
https://github.com/pi-hole/FTL/blob/bfa0d996d8e472fcd49d6bfdd49105897fabccdf/src/database/query-table.c#L537-L541

But when those queries are removed, `counters->forwarded` is decremented by *GC*:
https://github.com/pi-hole/FTL/blob/da89cc669f57fcefc6a171a5aa72c874f3ad0e78/src/gc.c#L89-L109

**Comment by DL6ER** [comment]
> Do queries with status types `QUERY_RETRIED` and `QUERY_RETRIED_DNSSEC` increment `counters->forwarded` at some point that I missed?

Yes, the flow is the following:

1. A query is sent upstream: `_FTL_forwarded` is called, it does `counters->forwarded++`
2. Another query with the same ID is received: `FTL_forwarding_retried` is called (it does not modify the counters)
  This function marks the *previous* query as having been retried and doesn't do anything else.
3. The *new* query is sent upstream: `_FTL_forwarded` is called

The database code was incorrect. I pushed a fix to the same branch.

**Comment by DL6ER** [comment]
Pi-hole FTL v5.7 has been released
