### ISSUE TITLE
Portainer container Pi-Hole seems to crash once a day

### ISSUE THREAD

**Issue by uhsa779** [pi-hole/FTL#1073]
> Please open an issue in the `docker` repo and fill out that template, it asks for docker specific things.

Sorry - opened it under "pi-hole/docker-pi-hole/" Issue 805 (https://github.com/pi-hole/docker-pi-hole/issues/805)

**Comment by dschaper** [comment]
> I read somewhere to do a pihole -r

That is for non-docker installations. Doing that inside docker will do bad things. 

Please open an issue in the `docker` repo and fill out that template, it asks for docker specific things.

**Comment by DL6ER** [comment]
Issue is being discussed in the docker namespace: https://github.com/pi-hole/docker-pi-hole/issues/805
