### ISSUE TITLE
Fatal Error with rev-server=172.16.0.0/12 set in Dnsmasq config

### ISSUE THREAD

**Issue by dandjo** [pi-hole/FTL#1074]
### Versions
-  Pi-hole version is v5.2.4 (Latest: v5.2.4)
-  AdminLTE version is v5.4 (Latest: v5.4)
-  FTL version is v5.7 (Latest: v5.7)

### Platform
- OS and version: Ubuntu 20.04
- Platform: Raspberry Pi 4

### Expected behavior

FTL/Dnsmasq not delegating 172.16.0.0/24 to upstream.

### Actual behavior / bug

FTL crashes on startup with:
FATAL ERROR in dnsmasq core: bad prefix at line 5 of /etc/dnsmasq.d/99-private-network.conf

### Steps to reproduce

Include following config in /etc/dnsmasq.d/...

```
# static hosts
addn-hosts=/etc/private-hosts
# disable lookup for IPv4 Intranet (RFC 5735)
rev-server=10.0.0.0/8
rev-server=172.16.0.0/12
rev-server=169.254.0.0/16
rev-server=192.168.0.0/16
# disable lookup for IPv6 Intranet
rev-server=fc00::/7
rev-server=fe80::/10
rev-server=2a02:XXXX:XXXX:XXXX::/60
```

### Discussion

Not sure if this is related to Dnsmasq or the Pi-hole fork.
When using 172.16.0.0/16 there's no problem.

**Comment by dandjo** [comment]
Related to this?

https://www.reddit.com/r/pihole/comments/ih1xtw/conditional_forwarding_for_172160012/

**Comment by dandjo** [comment]
And yes, I know that there is an option preventing RFC6303 addresses from being forwarded.

**Comment by yubiuser** [comment]
It's a dnsmasq limitation.
https://discourse.pi-hole.net/t/support-prefix-12-for-conditonal-forwarding/33975

**Comment by dandjo** [comment]
Thanks, so closing issue.
