### ISSUE TITLE
dns_queries_all_types in the API reports the wrong value

### ISSUE THREAD

**Issue by Yrlish** [pi-hole/FTL#1075]
### Versions

Pi-hole version is v5.2.4 (Latest: v5.2.4)
AdminLTE version is v5.4 (Latest: v5.4)
FTL version is v5.7 (Latest: v5.7)

### Platform

- OS and version:  Ubuntu 18.04

- Platform:  VM

### Expected behavior

The `dns_queries_all_types`  parameter in the API result should report the number of queries of all time.

### Actual behavior / bug

The `dns_queries_all_types` and `dns_queries_today` parameters in the api are the same value.
Both are reporting 11179 through the API.
Web UI - Dashboard - Last 24 hours: 11179
Web UI - Long-Term Data - All Time: 59451

### Steps to reproduce

http://pi.hole/admin/api.php?summaryRaw&overTimeData&topItems&recentItems&getQueryTypes&getForwardDestinations&getQuerySources&jsonForceObject

**Comment by DL6ER** [comment]
> ### Expected behavior
> 
> The `dns_queries_all_types`  parameter in the API result should report the number of queries of all time.

Why is this the expected behavior? Note that it says `all_types` - not `all_times`. This number should, in fact, equal the total number of queries returned by the API for consistency reasons as both numbers are computed differently and mismatch means some queries fell over at some point.

**Comment by Yrlish** [comment]
Hmm, right.

I want to get out the total number of queries in pihole to be used in Grafana as a graph. Any ideas?

**Comment by DL6ER** [comment]
With Pi-hole v6.0 (currently under development), there will be an API endpoint to get the number of queries in the database. It currently looks like https://ftl.pi-hole.net/new/http/docs/#get-/ftl/dbinfo (see `queries: integer :: Number of queries in long-term database`).

A similar endpoint does not exist in Pi-hole v5.x (or earlier).

**Comment by jfb-pihole** [comment]
> I want to get the total number of queries in pihole to be used in Grafana as a graph

If you want just the most recent 24 hours, this command will do it:

`echo ">stats >quit" | nc localhost 4711`

If you want longer term data out of your database, this command will do it:

`sudo sqlite3 /etc/pihole/pihole-FTL.db "SELECT COUNT(*) FROM queries"`

**Comment by Yrlish** [comment]
@jfb-pihole is `pihole-FTL.db` ever cleaned by any maintenance tasks or will it grow forever?

**Comment by DL6ER** [comment]
By default, queries older than 365 days are removed from the database. This can be changed by the user (see [MAXDBDAYS](https://docs.pi-hole.net/ftldns/configfile/#maxdbdays)).

However, there are also two fields which contain the total numbers of queries:
```
sqlite3 /etc/pihole/pihole-FTL.db "SELECT value FROM counters WHERE id = 0"
```
... and blocked queries:
```
sqlite3 /etc/pihole/pihole-FTL.db "SELECT value FROM counters WHERE id = 1"
```

These fields are never cleaned and grow over the entire lifetime of your database.

**Comment by Yrlish** [comment]
Nice @DL6ER! Those two numbers are exactly what I am looking for!

I'll have to make a scraper script for the sqlite database instead for HTTP and push all interesting data to an InfluxDB database.
