### ISSUE TITLE
FTL version is v5.7 will not start

### ISSUE THREAD

**Issue by peterd550** [pi-hole/FTL#1077]
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  v5.4
- FTL:  v5.7

### Platform

- debian 10

- Platform:   Raspberry Pi 4, Docker, user root

### Expected behavior

Pi-Hole FTL to start_

### Actual behavior / bug
pihole    | kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
pihole    | Starting pihole-FTL (no-daemon) as root
pihole    | Stopping pihole-FTL
pihole    | kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
pihole    | Starting pihole-FTL (no-daemon) as root
pihole    | Stopping pihole-FTL
pihole    | kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
pihole    | Starting pihole-FTL (no-daemon) as root
pihole    | Stopping pihole-FTL
pihole    | kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
pihole    | Starting pihole-FTL (no-daemon) as root
pihole    | Stopping pihole-FTL
pihole    | kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]

**Comment by dschaper** [comment]
Please open an issue at https://github.com/pi-hole/docker-pi-hole and fill out the issue template in full.
