### ISSUE TITLE
Black list no longer working?

### ISSUE THREAD

**Issue by Khengsoon** [pi-hole/FTL#1085]
Dear all, I'm running pihole v5.2.4 on raspberry pi. I'm testing the blacklist feature, the domain reg I added is (\.|^)youtube\.com$ how every I still able to go youtube.com. I make sure my DNS is set to my pihole, may I know what I missed out?

**Comment by yubiuser** [comment]
You missed the debug token.

**Comment by yubiuser** [comment]
Duplicate of https://github.com/pi-hole/pi-hole/issues/4087

**Comment by Khengsoon** [comment]
Sorry for that my debug token is https://tricorder.pi-hole.net/wrs0nkkcxy
