### ISSUE TITLE
-bash: pihole-FTL: command not found after binary install

### ISSUE THREAD

**Issue by MattAKAFred** [pi-hole/FTL#11]
Just tried to install FTL on my RPi-0, and I'm unable to get it to run any commands. 

I did the following

```
wget https://github.com/pi-hole/FTL/releases/download/v1.0/pihole-FTL-arm-linux-gnueabi
chmod u+x pihole-FTL*
```
So far so good...
```
./pihole-FTL*
FATAL: Opening of FTL log (/var/log/pihole-FTL.log) failed!
       Make sure it exists
```
Clearly a problem with not having write permissions in /var/log/pihole-FTL.log
```
sudo /usr/downloads/pihole-FTL-arm-linux-gnueabi
FTL started!
```
Woohoo!
```
pihole-FTL
-bash: pihole-FTL: command not found
```
:(

Any suggestions?

**Comment by DL6ER** [comment]
Well, according to
```
FTL started!
```
you are good to go.

If you run this command again, it should now show you
```
FATAL: Another FTL process is already running! Exiting...
```
---

```
pihole-FTL
-bash: pihole-FTL: command not found
```
is shown to you since you have not installed FTL into a location where the system can routinely find it.

Try something like the following:
```
killall pihole-FTL
cd /usr/downloads/
mv pihole-FTL-arm-linux-gnueabi pihole-FTL
sudo install -m 0755 pihole-FTL /usr/bin
sudo touch /var/log/pihole-FTL.log /var/run/pihole-FTL.pid /var/run/pihole-FTL.port
sudo chmod 0666 /var/log/pihole-FTL.log /var/run/pihole-FTL.pid /var/run/pihole-FTL.port
```

This should properly install `FTL` for you so you can start it with `pihole-FTL` afterwards.

Let us know if that worked for you and I will change the README accordingly.

**Comment by MattAKAFred** [comment]
That works, but now I am unable to run any commands (as far as I can tell)

Issuing commands like `>stats` does nothing

I suppose this is why I thought it wasn't working at all when using the prior setup.

**Comment by DL6ER** [comment]
Have you used `telnet` or have to tried typing into the terminal?

see https://github.com/pi-hole/FTL#socket-connections

**Comment by MattAKAFred** [comment]
Ahh, I see now, I was typing directly into the RPi terminal. I thought the telnet connection was just a suggestion for connecting externally, didn't realize it was needed internally. Much better now :) Thank you!

**Comment by technicalpyro** [comment]
a better practice from my experience may be to do the following
```
git clone https://github.com/pi-hole/pi-hole.git /etc/.pihole/
cd /etc/.pihole/
git checkout new/FTL-binary
pihole -up
```

this installs the latest in the test branch 
for the web admin
```
git clone https://github.com/pi-hole/AdminLTE.git  /var/www/html/admin/
cd /var/www/html/admin/
git checkout new/FTL-integration
pihole -up
```

that would install the latest webadmin could do it all then pihole -up once.  also worth noting only have to set this once then every time you run pihole -up with update it with the latest commits 
not saying you did it wrong just my two cents

**Comment by MattAKAFred** [comment]
Set up following your instructions @technicalpyro, works great! Thank you!

Only thing I had to do was also re-bind pihole-FTL command using
`sudo touch /var/log/pihole-FTL.log /var/run/pihole-FTL.pid /var/run/pihole-FTL.port
sudo chmod 0666 /var/log/pihole-FTL.log /var/run/pihole-FTL.pid /var/run/pihole-FTL.port`
and start up FTL with `pihole-FTL`

**Comment by technicalpyro** [comment]
thats my fault i should have had you run `pihole -r` after pihole -up which covers the rebind etc

**Comment by DL6ER** [comment]
Note that `FTL` is now part of the `development` branches on Pi-hole. If you want to continue using it, check out the branches

- `devel` in `/var/www/html/admin/
- `development` in `/etc/.pihole/`

Don't forget to run `pihole -r` afterwards.

**Comment by DL6ER** [comment]
Merged this information into the README with commit 8618947.
