### ISSUE TITLE
Database file location option

### ISSUE THREAD

**Issue by runningman84** [pi-hole/FTL#111]
Please allow us to confiure the database file location which is /etc/pihole by default. This could be a problem for tmpfs deployments...

**Comment by dschaper** [comment]
Please open Feature Requests at https://discourse.pi-hole.net so that they can be tracked and voted upon by other users.

**Comment by dschaper** [comment]
The templates are there for our use and help, if you do not fill them out it causes a lot more work for our volunteer staff to be able to triage and track.

**Comment by DL6ER** [comment]
This is no issue. Closing it.
