### ISSUE TITLE
v6 API reports negative query number

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/FTL#1125]
### Versions

  Pi-hole version is tweak/FTLPID v5.2.4-28-g0743472 (Latest: v5.3.1)
  AdminLTE version is new/FTL_is_my_new_home v5.3.2-41-gee1dc4f9 (Latest: v5.5)
  FTL version is new/http vDev-8e61447 (Latest: v5.8.1)

### Platform

- OS and version:  Debian 10 (Armbian)

- Platform:  NanoPi Neo Plus 2

### Expected behavior

Query count should be positive.

### Actual behavior / bug

Type A is reported as negative. Subsequently, stats at the dashboard are wrong

![Bildschirmfoto zu 2021-04-25 13-30-08](https://user-images.githubusercontent.com/26622301/115991860-c4489500-a5ca-11eb-911f-249d5bff3157.png)

![Bildschirmfoto zu 2021-04-25 13-29-27](https://user-images.githubusercontent.com/26622301/115991863-c7dc1c00-a5ca-11eb-9f10-fedf54948be1.png)

## Debug Token

- URL:  https://tricorder.pi-hole.net/ik47k55x7u

## Additional info

```
nanopi@nanopi:~$ sqlite3 /etc/pihole/pihole-FTL.db "Select type,count(type) from queries where timestamp > strftime('%s','now','-24 hours') group by type order by type;"
1|100
2|8
4|2
6|11
```

**Comment by DL6ER** [comment]
Thanks for the report. This is actually a regression and we haven't addressed this so far. It should be fixed once the most recent changes in FTL (v5.8.1 release) has been merged into the v6.0 development branch. This will result in quite many merge conflicts and will need some time... I'll come back to you and we'll need to re-test this once the updated version is up.

I'll close this now but we can re-open it at any time if the issue persists in the future.

**Comment by ChurchOfNoise** [comment]
> 
> 
> Thanks for the report. This is actually a regression and we haven't addressed this so far. It should be fixed once the most recent changes in FTL (v5.8.1 release) has been merged into the v6.0 development branch. This will result in quite many merge conflicts and will need some time... I'll come back to you and we'll need to re-test this once the updated version is up.
> 
> I'll close this now but we can re-open it at any time if the issue persists in the future.

So that means there will be a moment when we can update the dev branch to the dev-v6 branch?
Will keen an eye on this thread and update to dev-v6 on the 2nd Pi-Hole once it is possible.

**Comment by yubiuser** [comment]
I think the merge v.5.8.1 -> v6.0 happend today. Negative queries are gone and dashboard looks good. However, number of queries for each type via API are not correct (assuming the sum is correct based on the database)

```
{
  "queries": {
    "blocked": 269,
    "percent_blocked": 45.59321975708008,
    "unique_domains": 150,
    "forwarded": 283,
    "cached": 37,
    "types": {
      "A": 24,
      "AAAA": 0,
      "ANY": 5,
      "SRV": 0,
      "SOA": 11,
      "PTR": 4,
      "TXT": 5,
      "NAPTR": 0,
      "MX": 0,
      "DS": 0,
      "RRSIG": 0,
      "DNSKEY": 0,
      "NS": 0,
      "SVCB": 0,
      "HTTPS": 1,
      "OTHER": 0
    },
    "sum": 590,
    "replies": {
      "UNKNOWN": 0,
      "NODATA": 0,
      "NXDOMAIN": 4,
      "CNAME": 0,
      "IP": 0,
      "DOMAIN": 0,
      "RRNAME": 0,
      "SERVFAIL": 0,
      "REFUSED": 0,
      "NOTIMP": 0,
      "OTHER": 0
    }
  }           
```

```
nanopi@nanopi:~$ sqlite3 /etc/pihole/pihole-FTL.db "Select type,count(type) from queries where timestamp > strftime('%s','now','-24 hours') group by type order by type;"
1|541
2|24
4|5
6|13
8|5
```

**Comment by DL6ER** [comment]
> I think the merge v.5.8.1 -> v6.0 happend today.

Yes, the important part of it happened today (I merged in `development` as of today and resolved the merge conflicts). There are still some adaptations I'll have to finish, however, the types should work reliably meanwhile (just pushed another commit).

> So that means there will be a moment when we can update the dev branch to the dev-v6 branch?

Yes. I'm running one Pi-hole already the entire time on this branch, however, there will be some breaking changes coming here soon (so far you can go back and forth however you like, there is no breaking change so far).

**Comment by yubiuser** [comment]
> (I just pushed another commit)

It is correct now.
