### ISSUE TITLE
Pihole donß t show information on Start Page with Apache webserver

### ISSUE THREAD

**Issue by Herr-Bertt** [pi-hole/FTL#1128]
### Versions

- Pi-hole:  5.3.1
- AdminLTE:  5.5
- FTL:  5.8.1

### Platform

- OS and version:  Debian 10

- Platform:  Raspberry Pi

### Expected behavior

_A clear and concise description of what you expected to happen._

Pihole donß t show information on Start Page with Apache webserver. No Total Queries, NoQueries Blocked and No Percent Blocked and No graphical Information

### Actual behavior / bug

_A clear and concise description of what the bug is._

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
Apache is not officially supported, only lighttpd is. Please use https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36 for configuration support by the community.

**Comment by DL6ER** [comment]
We've seen many users having deployed Pi-hole successfully with Apache2 so you are likely missing a few dependencies. Maybe something else. None of the core developers are running a Pi-hole with Apache2 web server so please follow the link suggested by @yubiuser and ask the community over there. Your ticket will just not be seen here.
