### ISSUE TITLE
Update the PiHole Website documeation 

### ISSUE THREAD

**Issue by charlieporth1** [pi-hole/FTL#1139]
https://docs.pi-hole.net/ftldns/configfile/
https://pi-hole.net/2021/04/14/pi-hole-ftl-v5-8-web-v5-5-and-core-v5-3-released/#page-content
These two pages are not up to date with one another

**Comment by yubiuser** [comment]
Could you please be a little detailed what is not up to date?
Please note that there is already an open RP to update the documentation
https://github.com/pi-hole/docs/pull/516

Is anything forgotten there?

**Comment by charlieporth1** [comment]
> Could you please be a little detailed what is not up to date?
> Please note that there is already an open RP to update the documentation
> [pi-hole/docs#516](https://github.com/pi-hole/docs/pull/516)
> 
> Is anything forgotten there?
In Particular this is not mentioned in the documentation 
REPLY_ADDR4 and REPLY_ADDR6
