### ISSUE TITLE
Pihole doesn't resolve top level domains

### ISSUE THREAD

**Issue by Diniboy1123** [pi-hole/FTL#1154]
### Versions

- Pi-hole:  v5.3.1
- AdminLTE:  v5.5
- FTL:  v5.8.1

### Platform

- OS and version:  Raspbian buster armhf

- Platform:  Raspberry Pi Zero W

### Expected behavior

I am using a pihole -> cloudflared (for doh) -> quad9 resolver combination. I noticed that top level TLDs are not resolved by pihole even though cloudflared resolves them:

```
pi@netguard:~ $ dig ai. +short
pi@netguard:~ $ dig ai. +short @127.0.0.1 -p 5053
209.59.119.34
```

Both should return an IP address for the domain.

### Actual behavior / bug

TLDs are seemingly not being resolved.

### Steps to reproduce

```
pi@netguard:~ $ dig ai. +short
pi@netguard:~ $ dig ai. +short @127.0.0.1 -p 5053
209.59.119.34
```

## Debug Token

- URL:  not relevant due to the nature of the issue (very easy to repro on any pihole setup)

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by jfb-pihole** [comment]
What does your dnsmasq log at /var/log/pihole.log show for these transactions?  Query, forward, reply.

**Comment by Diniboy1123** [comment]
Thanks for the quick reaction.

This is all I am seeing for ai.:

```
Jul 28 22:37:34 dnsmasq[4115]: query[A] ai from 127.0.0.1
Jul 28 22:37:34 dnsmasq[4115]: config ai is NODATA-IPv4
```

**Comment by DL6ER** [comment]
Did you enabled the option `Never forward non-FQDNs` (see Settings page on the dashboard)? If so, this is both indented and desired behavior. There is no difference between top-level domains and local hostnames. Both as non-[FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name)s.

**Comment by Diniboy1123** [comment]
Ah, that was it! Nice catch. However I don't think these tlds should be considered as local domains. Have you considered maintaining a local list of hardcoded official tlds? Or any other workaround?

I wouldn't want to send all local fqdn traffic to the upstream dns, but these would be nice to have.

**Comment by DL6ER** [comment]
> Have you considered maintaining a local list of hardcoded official tlds?

There exists a ton of TLD, check out [Wikipedia](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains). New ones are added pretty often and common names like `audio`, `apple`, `camera`, `christmas` and more are among them. Hence, I don't think an exclusion list will be helpful.

In the real workd, your clients should never request TLDs. Why should they? They should only request domains for services out there, like `maps.google.com`. `dig A com` is a pretty useless query for a client machine.

**Comment by Diniboy1123** [comment]
That list is nothing compared to the blocklist pihole loads by default. I believe as an extra feature it could be done.

But you are right, there is probably not much real world use. I wanted to show someone that it's possible to host content even on a TLD and then the page didn't load. 😄 Figured the upstream DNS handles it, but not pihole. However I can just add these as local domains.
