### ISSUE TITLE
pihole dnsmasq configuration only accepts server, not local

### ISSUE THREAD

**Issue by watercrossing** [pi-hole/FTL#1203]
### Versions

- Pi-hole:  v5.5
- AdminLTE:  v5.7
- FTL: v5.10.2 

### Platform

- OS and version:   Ubuntu 20.04

- Platform:  x86 machine

### Expected behavior

I have `local=/fritz.box/192.168.0.1` in my `/etc/dnsmasq.d/02-localdns.conf` config file. This worked fine until upgrading pihole last night. Now all queries to FQDNs such as `google.com` get responded with `google.com.fritz.box` and ip address `192.186.0.1`.

Changing the line to `server=/fritz.box/192.168.0.1` restores the previous handling. However, according to the dnsmasq manpage "--local is a synonym for --server to make configuration files clearer in this case."

### Steps to reproduce

Change `server=` to `local=` in your dnsmasq.d config file, `pihole restartdns` and query from your local network (in my case a windows machine). The problem does not occur when queries from localhost.

**Comment by DL6ER** [comment]
Thanks for your report. This is a regression from the embedded `dnsmasq` server which received a large rewrite in the last version.

@watercrossing Could you please check if the error is solved when running
```
pihole checkout ftl fix/dnsmasq_server_local
```

If this fixes the issue you are describing, I'll forward your bug report together with the proposed bug fix upstream to the `dnsmasq` project if that is okay for you.

**Comment by watercrossing** [comment]
Hi @DL6ER. The branch does indeed fix the issue, thank you!

**Comment by DL6ER** [comment]
Thanks, I sent my patch upstream to the `dnsmasq` project and they accepted it, too.

https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=089a11f3400485f215f5e29c77e41d7730f2c806

**Comment by DL6ER** [comment]
The next version of FTL has been released. Please update and run
```
pihole checkout master
```
to get back on-track. The fix/feature branch you switched to will not receive any further updates.

Thanks for helping us to make Pi-hole better for us all!

If you have any issues, please either reopen this ticket or (preferably) create a new ticket describing the issues in further detail and only reference this ticket. This will help us to help you best.
