### ISSUE TITLE
DNS Resolver randomly crashing after update to latest version

### ISSUE THREAD

**Issue by ja-quinones** [pi-hole/FTL#1211]
### Versions

- Pi-hole:  5.3.1
- AdminLTE:  5.5.1
- FTL:  5.8.1

### Platform

- OS and version:  Ubuntu 20.04.3

- Platform:  Raspberri Pi

### Expected behavior

DNS not randomly Crashing

### Actual behavior / bug

After updating from V4 to V5, The DNS Resolver is randomly crashing, i haven't see any pattern, or an specific hour, but normally twice a day, sometimes by 2:00 am or 9, or 17:00

### Steps to reproduce

totally random crash, only thing i have seen is an increase in memory usage

## Debug Token

- URL:  https://tricorder.pi-hole.net/hJamXR92/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by baskwo** [comment]
I saw a lot of rate limiting in my network (I need to check that), maybe it's the issue you're talking about! I'll try that and let you know in a couple of days

**Comment by DL6ER** [comment]
@baskwo Is it still stable? If so, I'd suggest closing this issue.

**Comment by zombielinux** [comment]
> @baskwo Is it still stable? If so, I'd suggest closing this issue.

Ive not had any issues since switching to the development branch.

**Comment by baskwo** [comment]
Yes pihole has been stable for weeks so I guess it was either the IP stack or the cpu not being able to handle all of those request and creating a queue.

I'm not the original creator of this issue so I can't close it but I guess we can :)

**Comment by DL6ER** [comment]
The original reporter said earlier that it was fixed for them by a clean re-install.
