### ISSUE TITLE
CHecksum error - installing Pi-Hole fresh on raspberry

### ISSUE THREAD

**Issue by rudesome** [pi-hole/FTL#1220]
### Versions

- Pi-hole:  -
- AdminLTE: -  
- FTL:  -

### Platform

- OS and version:  Raspbian 10

- Platform:  Raspberry Pi

### Expected behavior

Smooth installation.
Using the 'One-Step Automated Install'

### Actual behavior / bug

While installing i get the following error:

  [✓] Checking for user 'pihole'

  [i] FTL Checks...

  [✓] Detected ARMv7 processor (with hard-float support)
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (6) Could not resolve host: github.com
sha1sum: pihole-FTL-armv7-linux-gnueabihf.sha1: No such file or directory
  **[✗] Downloading and Installing FTL
  Error: Download of https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-armv7-linux-gnueabihf failed (checksum error)
  [✗] FTL Engine not installed**

### Steps to reproduce

install fresh Raspbian on a raspberry pi
start install script with: curl -sSL https://install.pi-hole.net | bash

**Comment by ParkHost** [comment]
at the moment i clicked to post the bug, i saw the flaw...
couldn't resolv github.com...
checked /etc/resolv.conf, added a secundaire nameserver, done
