### ISSUE TITLE
Wrong CNAME reply time calculation (too fast)

### ISSUE THREAD

**Issue by r2ixuz** [pi-hole/FTL#1232]
For example if I resolve the A record for "alive.github.com" it points to an CNAME record. Which is shown in the Pi-hole reply column as too fast: 13ms in this example where alone the RTT to Google DNS is for me at its best 24ms.

This bug is new since "Docker Tag 2021.10.1 Pi-hole v5.6 FTL v5.11 Web Interface v5.8".

**Comment by DL6ER** [comment]
@r2ixuz The custom docker tag `fix_cached_cname_upstream_dest` will be updated in about half an hour with another fix (#1237) which should also cover the `SERVFAIL`/`REFUSED`/... replies from multiple upstreams.

**Comment by r2ixuz** [comment]
Looks good. Your fix is working! Thanks.

**Comment by DL6ER** [comment]
The next version of FTL has been released. Please update and run
```
pihole checkout master
```
to get back on-track. The fix/feature branch you switched to will not receive any further updates.

Thanks for helping us to make Pi-hole better for us all!

If you have any issues, please either reopen this ticket or (preferably) create a new ticket describing the issues in further detail and only reference this ticket. This will help us to help you best.
