### ISSUE TITLE
FTL for mips64 bigendian needed.

### ISSUE THREAD

**Issue by debiansid** [pi-hole/FTL#126]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_2_

---

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**Log file output [if available]**

```
lscpu
Architecture:          mips64
Byte Order:            Big Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
L1d cache:             16K
L1i cache:             32K
L2 cache:              128K

```

**Device specifics**

Hardware Type: rPi, VPS, etc
OS:
debian wheezy for mips64 big endian

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by technicalpyro** [comment]
have you attempted to compile this manually by copying the repository and running make?

**Comment by debiansid** [comment]
Yep, I got it compiled.but the interesting part is I can not see any numbers on admin webui @3.1
and after I installed webadmin 2.5.2, it works.

so, where I can get help on this.

**Comment by technicalpyro** [comment]
can you provide your debug token? `pihole -d` from the CLI 

my thoughts are that there is a missing file association wheezy is now 2 generations old aand could very well be missing something FTL needs to work correctly.  i am sure one of the devs will be able to chime in after reviewing your debug log

**Comment by debiansid** [comment]
`
04wgs4ef24
`
this my token

**Comment by Mcat12** [comment]
You appear to have many things wrong with your installation, but that may just be because of wheezy. What is the output of these commands when in the `/var/www/html/admin` directory?
```
git status
git show
```

**Comment by debiansid** [comment]
root@usg-3p:/var/www/html/admin-3.1# git status
# On branch master
nothing to commit (working directory clean)

commit f204b717078c89b6401b362f084734350ce13a51
Author: Adam Warner <PromoFaux@users.noreply.github.com>
Date:   Tue Jun 20 22:17:37 2017 +0100


And now admin is from 2.5.2 release tar.gz , so not git working dir.
fatal: Not a git repository (or any of the parent directories): .git

**Comment by Mcat12** [comment]
Why did you install it from the tar.gz instead of choosing to install it via the installer? Also, some things assume that the web interface is at `/admin`

**Comment by debiansid** [comment]
AdminLTE 3.1 from installer could not show any number. So I downloaded the version  2.5.2.

**Comment by debiansid** [comment]
3.1 admin/api.php
Show me
`Operation now in progress`

**Comment by DL6ER** [comment]
Any versions prior to `3.0` do not use `FTL` but compute the statistics using a different method. However, `3.1` will only show statistics when `FTL` is running.

What is the output of

- `tail -n20 /var/log/pihole-FTL.log`
- `sudo service pihole-FTL status`

**Comment by debiansid** [comment]
pihole-FTL.log
```
2017-09-16 01:11:08.545] Finished initial log file parsing
[2017-09-16 01:11:08.545]  -> Total DNS queries: 1596
[2017-09-16 01:11:08.546]  -> Cached DNS queries: 604
[2017-09-16 01:11:08.546]  -> Blocked DNS queries: 115
[2017-09-16 01:11:08.547]  -> Unknown DNS queries: 0
[2017-09-16 01:11:08.547]  -> Unique domains: 440
[2017-09-16 01:11:08.548]  -> Unique clients: 12
[2017-09-16 01:11:08.548] Successfully accessed setupVars.conf
[2017-09-16 01:11:08.550] Listening on port 4711 for incoming connections
```

**Comment by debiansid** [comment]
service pihole-FTL status
`
/etc/init.d/pihole-FTL: line 69: status: command not found
`

**Comment by DL6ER** [comment]
Hmm, how about
```
echo ">stats" | nc -v 127.0.0.1 4711
```

**Comment by debiansid** [comment]
```
root@usg-3p:/var/www/html/admin# echo ">stats" | nc  127.0.0.1 4711
domains_being_blocked 120895
dns_queries_today 1619
ads_blocked_today 115
ads_percentage_today 7.103150
unique_domains 440
queries_forwarded 889
queries_cached 615
unique_clients 12
---EOM---
```

**Comment by DL6ER** [comment]
Okay, so your `FTL` works without problems and the problems are on `PHP`'s side. Please have a look into 
`/var/log/lighttpd/error.log` if there are any problem mentioned there.

**Comment by DL6ER** [comment]
I'm not sure on what kind of device your installation is running so there may be a difference in where PHP logs its errors? As you have tested above, `FTL` is running and you can query data locally, so I doubt it is a firewall issue.

**Comment by Mcat12** [comment]
If you open the developer tools in the browser (F12) and go to the networking tab and then restart the tab, do you see any odd responses? The queries such as `api.php?summary` should be returning data. Perhaps provide screenshots of what you see?

**Comment by debiansid** [comment]
```
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped.  bootstrap.min.css:5:132
Unknown pseudo-class or pseudo-element ‘-webkit-inner-spin-button’.  Ruleset ignored due to bad selector.  bootstrap.min.css:5:1544
Unknown pseudo-class or pseudo-element ‘-webkit-search-cancel-button’.  Ruleset ignored due to bad selector.  bootstrap.min.css:5:1778
Unknown property ‘orphans’.  Declaration dropped.  bootstrap.min.css:5:2691
Unknown property ‘widows’.  Declaration dropped.  bootstrap.min.css:5:2700
Expected color but found ‘auto’.  Expected color but found ‘-webkit-focus-ring-color’.  Expected end of value but found ‘-webkit-focus-ring-color’.  Error in parsing value for ‘outline’.  Declaration dropped.  bootstrap.min.css:5:16251
Error in parsing value for ‘margin-top’.  Declaration dropped.  bootstrap.min.css:5:36624
Expected color but found ‘auto’.  Expected color but found ‘-webkit-focus-ring-color’.  Expected end of value but found ‘-webkit-focus-ring-color’.  Error in parsing value for ‘outline’.  Declaration dropped.  bootstrap.min.css:5:36879
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.  bootstrap.min.css:5:37820
Unknown pseudo-class or pseudo-element ‘-webkit-input-placeholder’.  Ruleset ignored due to bad selector.  bootstrap.min.css:5:37870
Unknown pseudo-class or pseudo-element ‘-ms-expand’.  Ruleset ignored due to bad selector.  bootstrap.min.css:5:37924
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  bootstrap.min.css:5:38266
Error in parsing value for ‘margin-top’.  Declaration dropped.  bootstrap.min.css:5:39387
Unknown property ‘user-select’.  Declaration dropped.  bootstrap.min.css:5:46533
Expected color but found ‘auto’.  Expected color but found ‘-webkit-focus-ring-color’.  Expected end of value but found ‘-webkit-focus-ring-color’.  Error in parsing value for ‘outline’.  Declaration dropped.  bootstrap.min.css:5:46736
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  bootstrap.min.css:5:47088
Expected color but found ‘solid\9 ’.  Expected end of value but found ‘solid\9 ’.  Error in parsing value for ‘border-top’.  Declaration dropped.  bootstrap.min.css:5:56150
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  bootstrap.min.css:5:57537
Expected color but found ‘solid\9 ’.  Expected end of value but found ‘solid\9 ’.  Error in parsing value for ‘border-bottom’.  Declaration dropped.  bootstrap.min.css:5:58098
Error in parsing value for ‘background-image’.  Declaration dropped.  bootstrap.min.css:5:86969
Error in parsing value for ‘background-image’.  Declaration dropped.  bootstrap.min.css:5:87880
Error in parsing value for ‘background-image’.  Declaration dropped.  bootstrap.min.css:5:88510
Error in parsing value for ‘background-image’.  Declaration dropped.  bootstrap.min.css:5:89146
Error in parsing value for ‘background-image’.  Declaration dropped.  bootstrap.min.css:5:89780
Unknown property ‘zoom’.  Declaration dropped.  bootstrap.min.css:5:90222
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  bootstrap.min.css:5:107713
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  bootstrap.min.css:5:107824
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  bootstrap.min.css:5:109053
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  bootstrap.min.css:5:109108
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  bootstrap.min.css:5:110278
Unknown property ‘line-break’.  Declaration dropped.  bootstrap.min.css:5:110315
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  bootstrap.min.css:5:110342
Unknown property ‘line-break’.  Declaration dropped.  bootstrap.min.css:5:112354
Expected media feature name but found ‘transform-3d’.  bootstrap.min.css:5:114234
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  bootstrap.min.css:5:115589
Error in parsing value for ‘background-image’.  Declaration dropped.  bootstrap.min.css:5:115747
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  bootstrap.min.css:5:116006
Error in parsing value for ‘background-image’.  Declaration dropped.  bootstrap.min.css:5:116292
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  bootstrap.min.css:5:116551
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  bootstrap.min.css:5:116778
Expected color but found ‘#\30 00\9 ’.  Error in parsing value for ‘background-color’.  Declaration dropped.  bootstrap.min.css:5:117743
Unknown property ‘user-select’.  Declaration dropped.  pi-hole.css:14:12
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  font-awesome.min.css:4:1947
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  font-awesome.min.css:4:2112
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  font-awesome.min.css:4:2280
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  font-awesome.min.css:4:2453
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  font-awesome.min.css:4:2628
Unknown property ‘speak’.  Declaration dropped.  ionicons.min.css:11:19657
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.  AdminLTE.min.css:7:3168
Unknown pseudo-class or pseudo-element ‘-webkit-input-placeholder’.  Ruleset ignored due to bad selector.  AdminLTE.min.css:7:3251
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.  AdminLTE.min.css:7:24595
Unknown property ‘appearance’.  Declaration dropped.  AdminLTE.min.css:7:24762
Error in parsing value for ‘background-image’.  Declaration dropped.  AdminLTE.min.css:7:27211
Error in parsing value for ‘background-image’.  Declaration dropped.  AdminLTE.min.css:7:27935
Error in parsing value for ‘background-image’.  Declaration dropped.  AdminLTE.min.css:7:28651
Error in parsing value for ‘background-image’.  Declaration dropped.  AdminLTE.min.css:7:29377
Error in parsing value for ‘background-image’.  Declaration dropped.  AdminLTE.min.css:7:30095
Error in parsing value for ‘z-index’.  Declaration dropped.  AdminLTE.min.css:7:31119
Unknown property ‘-moz-box-shadow’.  Declaration dropped.  AdminLTE.min.css:7:41306
Unknown property ‘-moz-box-shadow’.  Declaration dropped.  AdminLTE.min.css:7:41427
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:41731
Unknown property ‘-moz-box-shadow’.  Declaration dropped.  AdminLTE.min.css:7:43489
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:44301
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:44359
Unknown property ‘user-select’.  Declaration dropped.  AdminLTE.min.css:7:70065
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:75811
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:77107
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:77258
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:77313
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:77627
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:77778
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:77833
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:78141
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:78292
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:78347
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:78655
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:78806
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:78861
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:79171
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:79322
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:79377
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:79687
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:79838
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:79893
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:80202
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:80353
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:80408
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:80715
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:80866
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:80921
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:81224
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:81369
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:81421
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:81731
Error in parsing value for ‘background’.  Declaration dropped.  AdminLTE.min.css:7:81882
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:81937
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:82360
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  AdminLTE.min.css:7:82423
```

**Comment by debiansid** [comment]
[https://github.com/debiansid/shadowsocks-libev-archlinux/blob/master/Screen%20Shot%202017-09-16%20at%208.36.56%20AM.png](url)

**Comment by debiansid** [comment]
[](https://raw.githubusercontent.com/debiansid/shadowsocks-libev-archlinux/master/Screen%20Shot%202017-09-16%20at%208.36.56%20AM.png)

**Comment by debiansid** [comment]
[https://raw.githubusercontent.com/debiansid/shadowsocks-libev-archlinux/master/Screen%20Shot%202017-09-16%20at%208.36.56%20AM.png](url)

**Comment by debiansid** [comment]
![Image of Yaktocat](https://raw.githubusercontent.com/debiansid/shadowsocks-libev-archlinux/master/images/Screen%20Shot%202017-09-16%20at%208.36.56%20AM.png)

**Comment by debiansid** [comment]
the device I install pi-hole is Ubnt USG-3p, which is based on Debian wheezy on mips64.

php is 5.4.42
lighttpd 1.4.35

would you developer tell me what php extension must be installed?

**Comment by Mcat12** [comment]
I don't know what lead you to needing a PHP extension? Can you give a screenshot of the Network tab of the developer tools?

**Comment by debiansid** [comment]
@Mcat12
I did not install this via your installer. Because the php and Lighttpd is not normal (not shown by dpkg -l).
So I ran installer on normal x86 Debian 9.1, then copy all files in /etc/pihole /opt/pihole, Cron, sudoers to target box; then git clone pihole adminwebui.

**Comment by WaLLy3K** [comment]
Hey @debiansid! Currently, we don't support installing Pi-hole onto embedded distributions such as routers - and we're definitely aware that [this is something that people would like](https://discourse.pi-hole.net/t/pihole-directly-on-routers-tomato-merlinwrt-dd-wrt-openwrt/1314).

As this issue currently stands, the hardware that you're installing Pi-hole on is unsupported and would be extremely difficult for us to ensure Pi-hole will actually work - primarily because:

* You haven't used the installer script which ensures that the distribution has all the right folders, users, dependencies, permissions, etc
* We don't support Debian Wheezy due to the age of this distrubtion
* We don't know what changes the Ubnt USG-3p has made to this distribution (many embedded distributions use `busybox`, which strips features out of tools we make frequent use of)
* Don't have a compiled version of FTL for MIPS/MIPS64 (due to point 3)

Now what we can do here for you is to try and give a couple of suggestions that might point you in the right direction (because if you can get it working, and can provide the steps you used to make it all work, would be *very* useful information for us, as well as anyone else in your position), but you will need to do the "legwork" yourself.

**Comment by debiansid** [comment]
Thanks! 
I have FTL for mips64 compiled and running correctly.
Now I am trying to make Admin webui 3.1 working. 
2.5.2 working on this device. 
and pihole is working too.

I am wondering the php requirements after admin version 3.0 , is there any documents I can check on this?

**Comment by WaLLy3K** [comment]
`php -v` on my hardware returns `PHP 5.6.30-0+deb8u1`, and [web dependencies are found here](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L141).

@Mcat12 also asked for this, which would be helpful:
> Can you give a screenshot of the Network tab of the developer tools?

**Comment by debiansid** [comment]
that is why I could not understand why admin version 2.5.2 working but 3.1 not on my device.

**Comment by debiansid** [comment]
![screenshot]https://raw.githubusercontent.com/debiansid/shadowsocks-libev-archlinux/master/images/2.png

**Comment by Mcat12** [comment]
When you go to the network tab, you should reload the page instead of clicking on performance analysis:
![screenshot from 2017-09-15 23-34-02](https://user-images.githubusercontent.com/4417660/30508841-953534d2-9a6e-11e7-9da7-15524e009d4a.png)

Then you can click on network requests and see info about them:
![screenshot from 2017-09-15 23-34-38](https://user-images.githubusercontent.com/4417660/30508848-ad9b390e-9a6e-11e7-837e-ab478df7c17d.png)

**Comment by debiansid** [comment]
![screemhost2](https://raw.githubusercontent.com/debiansid/shadowsocks-libev-archlinux/master/images/3.png)

**Comment by DL6ER** [comment]
A short summary after 30 comments on this issue report:

- `Pi-hole core`  is working, see https://github.com/pi-hole/FTL/issues/126#issuecomment-329938932
- `FTL` is working, see https://github.com/pi-hole/FTL/issues/126#issuecomment-329844369
- `PHP` is working as the `admin` page with version < 3.0 runs fine, see https://github.com/pi-hole/FTL/issues/126#issuecomment-329816564

However, what is not working is the interplay between `FTL` and `PHP`. Please try wether this PHP file (place it into the root folder of your `admin v3.1` folder where also `api.php` is located) works fine:
```
<?php
/*   Pi-hole: A black hole for Internet advertisements
*    (c) 2017 Pi-hole, LLC (https://pi-hole.net)
*    Network-wide ad blocking via your own hardware.
*
*    This file is copyright under the latest version of the EUPL.
*    Please see LICENSE file for your rights under this license */

require("scripts/pi-hole/php/FTL.php");

$address = "127.0.0.1"; $port = 4711;

echo "Create a TCP/IP socket\n";
$socket = socket_create(AF_INET, SOCK_STREAM, SOL_TCP) or die("socket_create() failed: reason: " . socket_strerror(socket_last_error()) . "\n");
echo "Set noblock\n";
socket_set_nonblock($socket) or die("Unable to set nonblock on socket\n");
echo "Socket connect\n";
socket_connect($socket, $address, $port);
echo "Set block\n";
socket_set_block($socket) or die("Unable to set block on socket\n");
// Set timeout to 3 seconds
echo "Set timeout R\n";
socket_set_option($socket, SOL_SOCKET, SO_RCVTIMEO, ['sec'=>3, 'usec'=>0]);
echo "Set timeout S\n";
socket_set_option($socket, SOL_SOCKET, SO_SNDTIMEO, ['sec'=>3, 'usec'=>0]);
echo "Send request\n";
sendRequestFTL("stats");
echo "Get Response\n";
print_r(getResponseFTL());
echo "Disconnect\n";
disconnectFTL();
?>
```

It should show you the statistics of `FTL`, e.g.
![screenshot at 2017-09-16 09-29-38](https://user-images.githubusercontent.com/16748619/30510287-a17690a8-9ac1-11e7-8c5c-24b45adecd2c.png)


If it doesn't do that and there is again no error message, have again a look the `lighttpd` `error.log`.

**Comment by debiansid** [comment]
It show me this:
```
Create a TCP/IP socket Set noblock Socket connect Set block Set timeout R Set timeout S Send request Get Response Array ( [0] => domains_being_blocked 120895 [1] => dns_queries_today 5536 [2] => ads_blocked_today 306 [3] => ads_percentage_today 5.527457 [4] => unique_domains 824 [5] => queries_forwarded 3174 [6] => queries_cached 2056 [7] => unique_clients 12 ) Disconnect
```

**Comment by debiansid** [comment]
FYI
I don’t have php-cli installed , just php-cgi shipping with ubnt.

**Comment by DL6ER** [comment]
That is exactly what it should do. Yet, `api.php?summary` doesn't work?

**Comment by debiansid** [comment]
api.php shows 
`Operation now in progress`
Forever

**Comment by DL6ER** [comment]
Does the file `/var/run/pihole-FTL.port` exist and contain `4711`?

**Comment by debiansid** [comment]
`root@usg-3p:/var/www/html/admin# cat /var/run/pihole-FTL.port 
4711`

**Comment by DL6ER** [comment]
What are the permissions on this file? Should be
```
ls -lh /var/run/pihole-FTL.port 
-rw-r--r-- 1 pihole pihole 4 Sep 16 09:24 /var/run/pihole-FTL.port
```
assuming `pihole-FTL` is running as user `pihole`.

**Comment by debiansid** [comment]
```
root@usg-3p:/var/run# ls -lart pihole-FTL.port 
-rw-r--r--    1 pihole   pihole  4 Sep 16 01:11 pihole-FTL.port
```

**Comment by debiansid** [comment]
I found this in error.log
```
017-09-16 15:44:15: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  socket_connect(): unable to connect [150]: Operation now in progress in /var/www/html/admin/1.php on line 18
2017-09-16 15:45:15: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  socket_connect(): unable to connect [150]: Operation now in progress in /var/www/html/admin/1.php on line 18
```
1.php is the file you asked me put into that directory

**Comment by debiansid** [comment]
Can I install adminLTE on the other machine and connect FTL remotely? Will it work?

**Comment by DL6ER** [comment]
> socket_connect(): unable to connect [150]: Operation now in progress

Okay, weird though that it still worked for you. I looked a bit around on the net and this error with non-blocking socket connections does always seem to point to an issue with the networking of your server (however, I haven't seen any solution).

> Can I install adminLTE on the other machine and connect FTL remotely? Will it work?

Yes, that will work, however, as a security measure, `FTL` by default does not allow connections from any remote host. You can change this by adding
```
SOCKET_LISTENING=all
```
to `/etc/pihole/pihole-FTL.conf` (create it if it doesn't exist) and restarting `FTL`. (see also [README#config](https://github.com/pi-hole/FTL#ftls-config-file)).

**Comment by debiansid** [comment]
so, where I can set FTL ip:port in adminLTE?

**Comment by debiansid** [comment]
as my advice, since we have FTL now, it should be more flexible to install pihole-scripts+FTL on a host , and AminLTE+lighttpd+php on another one.

**Comment by DL6ER** [comment]
>  it should be more flexible to install pihole-scripts+FTL on a host , and AminLTE+lighttpd+php on another one.

Well, this Feature Request never came up until now (to the best of my knowledge). You can now basically do three things

1. Open a Feature Request on https://discourse.pi-hole.net
2. Code the feature yourself and submit a pull request here
3. Code it for yourself in a static way

If you want to go No. 3, I'll give you the required hints:
On the system that is running AdminLTE but not FTL, you'll have to go to the file `api_FTL.php` and change line 15 from
```php
$socket = connectFTL("127.0.0.1");
```
to
```php
$socket = connectFTL("pi.hole"); // or the fixed IP address
```

You won't need to create the file `/var/run/pihole-FTL.port` as the port file check will, of course, only be performed if the target host is the local host. For remote hosts, port 4711 is assumed without further changes to the code.

**Comment by Mcat12** [comment]
Many things won't work on the web interface, as it assumes it has filesystem access to the `setupVars.conf` file.

**Comment by debiansid** [comment]
I installed adminLTE on another host, it shows me pihole-FTL is offline.
but telnet FTL:4711 works.
I would guess maybe FTL code  does not work on MIPs64 cpu?

**Comment by DL6ER** [comment]
> I would guess maybe FTL code does not work on MIPs64 cpu?

No, because

> but telnet FTL:4711 works.

The `telnet` interface is everything `FTL` offers to external software. The `PHP` API connects to the exact same interface for querying its data. It seems to be either a networking (firewall, permissions, you name it) or a `PHP` issue.

**Comment by debiansid** [comment]
that's why I was asking the 
`php requirements for the adminLTE.`
firewall, I don't think so, FTL runnig on my router(192.168.88,1) adminLTE on another Linux box (192.168.88.10), I ran telnet FTL:4711 from 192.168.88.10.

**Comment by debiansid** [comment]
I tested again by installing FTL on another normal linux , still can not connect remotely from adminLTE.

**Comment by DL6ER** [comment]
Okay, I have to admit that I never tested that, but I opened a [bug report](https://github.com/pi-hole/AdminLTE/issues/589) for you where you could also post more details if you have them (like error messages from `lighttpd`'s or `PHP`'s log files, etc).

**Comment by DL6ER** [comment]
@debiansid I'll close this issue here. See https://github.com/pi-hole/AdminLTE/issues/589 for further details and progress.
