### ISSUE TITLE
FTL 5.13 - clients timeout

### ISSUE THREAD

**Issue by rnsc** [pi-hole/FTL#1292]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate

**How familiar are you with the codebase?:**

_1_

---

**[BUG | ISSUE] Expected Behaviour:**

Pihole-FTL to reply to clients on the network.

**[BUG | ISSUE] Actual Behaviour:**

Pihole-FTL doesn't reply to clients and requests time out.

**[BUG | ISSUE] Steps to reproduce:**

- Just updated to v5.13 and the issue started to appear.
- Forcing a checkout of FTL v5.12.1 with `pihole checkout ftl v5.12.1` fixes it.
- I have the same exact behaviour on an RPi (Debian 10) and a VPS (Debian 11).

**Log file output [if available]**

When clients aren't getting replies, I do not see errors in the FTL log (/var/log/pihole-FTL.log).
I do see the network requests coming in with `ngrep`.
I understand this isn't much, but I don't know what I can run to have more debug information to debug this issue.

**Device specifics**

Hardware Type: rPi and VPS
OS: Debian 10 and Debian 11

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
> I do see the network requests coming in with ngrep.

Do you also see them in `/var/log/pihole.log` ? Do you have any custom config files in `/etc/dnsmasq.d` or possibly in `/etc/dnsmasq.conf` ?

**Comment by rnsc** [comment]
@DL6ER hey, I did some back and forth between versions to provide you more details, but now, without any configuration change, 5.13 works again, not sure what's going on. Will re-open, or re-create one if I encounter the same issue.
Sorry for the noise!
