### ISSUE TITLE
Special characters in the DHCP's clients' names

### ISSUE THREAD

**Issue by ppapajohn** [pi-hole/FTL#1298]
Hi all, 
First of all congratulation on the tremendous and excellent work you have performed! 

The issue I face is with DHCP clients having special characters in their names. For example my iPad's name is "ppj's iPad" (without the quotes). 

Whenever a device has in its name special characters, then the pi-hole cannot register its name and as such it registers an IP with a name <i>unknown</i>.

Is this normal? I recall that in previous versions, special characters where simply ignored (or replaced with dashes?). 

Thanks and once again excellent work! :) 

Best Regards,
Panos

### Versions
Pi-hole version is v5.8.1 (Latest: v5.8.1)
AdminLTE version is v5.10.1 (Latest: v5.10.1)
FTL version is v5.13 (Latest: v5.13)

### Platform

- OS and version: Ubuntu 20.04.3 LTS

- Platform: Raspberry Pi 4B 4GB 

### Expected behavior

Register the client name even if it includes special characters or substitute them (the special characters) with dashes as it was in previous versions.  

### Actual behavior / bug

As per the above

### Steps to reproduce

Simply register a device with a special character in its name

**Comment by DL6ER** [comment]
Sorry for the delay on this, somehow it got missed when it was transferred from the other repo over to this place.

> Is this normal? I recall that in previous versions, special characters where simply ignored (or replaced with dashes?).

Yes, the domain name you mentioned has a space in it which is forbidden for DNS names. FTL internally replaces this space by a `~`, however, a lot of other features such as internal network resolution won't work reliably (this is an inherited from the embedded `dnsmasq`).

Do you see a warning about invalid domain names in `/var/log/pihole-FTL.log` ?

**Comment by ppapajohn** [comment]
Thanks @DL6ER,

much appreciated and of course I fully understand. :) No invalid domain name entry in the pihole-FTL.log unfortunately. I am aware for the special characters, however in previous versions of the pi-hole those were handled differently. Any space was deprecated and I was able to see the device's registered name with no spaces. You are right this not being safe, but for a home environment the risk of having a conflict is relatively low. 

Is there anything I can do to fix that, without having to change the erroneous devices' names? 

Thanks again and Best Regards,
Panos

**Comment by DL6ER** [comment]
Sorry for the silence Panos, I just wanted to jump in really quickly and tell you that I haven't forgotten about your issue. There is just a lot on the todo but we'll eventually come back to this!

**Comment by ppapajohn** [comment]
@DL6ER Fully understand, don't even mention this! 😄 besides this is not as important as others. Thanks again!
