### ISSUE TITLE
Disabling of rate-limit not being respected

### ISSUE THREAD

**Issue by liamjones** [pi-hole/FTL#1303]
### Versions

  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

### Platform

- OS and version:  Raspbian GNU/Linux 10 (buster)

- Platform:  Raspberry Pi

### Expected behavior

Don't expect any client to be rate-limited

### Actual behavior / bug

Pi-Hole UI (Pi-hole diagnosis) keeps showing clients as rate-limited:

```
022-02-15 22:39:55 | RATE_LIMIT | Client 192.168.1.1 has been rate-limited (current config allows up to 1000 queries in 60 seconds)
```

### Steps to reproduce

1. Edit `/etc/pihole/pihole-FTL.conf` to match this:
```
RATELIMIT=0/0
PRIVACYLEVEL=0
```
2. Restart system
3. Use system
4. See error appear in Pi-hole diagnosis after breaking default(?) limit

## Debug Token

- URL:  https://tricorder.pi-hole.net/1enGQVpe/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by DL6ER** [comment]
The setting should be [`RATE_LIMIT`](https://docs.pi-hole.net/ftldns/configfile/#rate_limit) with an underscore character.

**Comment by liamjones** [comment]
Ugh, I'm an idiot, thank you!
