### ISSUE TITLE
OpenDNS is now hijacking for me

### ISSUE THREAD

**Issue by Mousketeer** [pi-hole/FTL#1308]
OpenDNS seems to be part of Cisco now and at least to me the open resolving service is gone from the previously known addresses and is now replaced by a fixed IP pointing to the cisco umbrella product page.

If my experience is universal, then in my opinion the OpenDNS option should be removed from pi-hole.

### Versions
  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

### Platform
Linux pihole 4.9.0-17-amd64 #1 SMP Debian 4.9.290-1 (2021-12-12) x86_64 GNU/Linux

### Expected behaviour

Hosts not in any blacklist resolve successfully.

### Actual behavior / bug

They resolve to the cisco umbrella at **146.112.61.104**
This worked fine until approx 10h ago as of posting this bug.

### Steps to reproduce

In the settings webinterface, configure OpenDNS (208.67.222.222 and 208.67.220.220) as the sole upstreams.
Or directly:
```dig @208.67.220.220 google.com

; <<>> DiG 9.16.22-Debian <<>> @208.67.220.220 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64607
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		0	IN	A	146.112.61.104

;; Query time: 19 msec
;; SERVER: 208.67.220.220#53(208.67.220.220)
;; WHEN: Fri Feb 25 08:30:35 CET 2022
;; MSG SIZE  rcvd: 55

```
and
```dig @208.67.222.222 microsoft.com

; <<>> DiG 9.16.22-Debian <<>> @208.67.222.222 microsoft.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21428
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;microsoft.com.			IN	A

;; ANSWER SECTION:
microsoft.com.		0	IN	A	146.112.61.104

;; Query time: 15 msec
;; SERVER: 208.67.222.222#53(208.67.222.222)
;; WHEN: Fri Feb 25 08:31:23 CET 2022
;; MSG SIZE  rcvd: 58
```

**Comment by stuXORstu** [comment]
I could not find any news reports that OpenDNS (or OpenDNS Home as it is called technically) is no longer a thing.  When I resolve ```google.com``` via ```208.67.222.222``` and ```208.67.220.220``` I get expected behavior:

```
$ dig @208.67.220.220 google.com +short
142.250.76.110

$ dig @208.67.222.222 google.com +short
142.250.76.110

$ whois 142.250.76.110 | grep NetName
NetName:        GOOGLE
```

Given a few days has passed since, are you still seeing the same issue?

**Comment by Mousketeer** [comment]
At this moment the two Opendns servers are now working as expected again (from the same source-IP even). Not a clue what happened; I will re-open this issue if I notice it again.
