### ISSUE TITLE
negative percentage in Forward Destination pie chart

### ISSUE THREAD

**Issue by spinofdoom** [pi-hole/FTL#1321]
### Versions

  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

### Platform

- OS and version:  DietPi 8.2.2

- Platform:  Raspberry Pi 4 Model B

### Expected behavior

Expected Forward Destination pie chart to show only positive percentages on hover.

### Actual behavior / bug

The `other` entry on the pie chart is a negative percentage:
<img width="635" alt="Screen Shot 2022-03-21 at 6 39 17 PM" src="https://user-images.githubusercontent.com/23316231/159380610-9d0b586f-b27e-4311-8ce6-0b33ceb301f8.png">

### Steps to reproduce

I'm not sure exactly how to go about trying to reproduce this specifically, except to open `pi.hole/admin`, and hover over the slices of the Forward Destination pie chart.

## Debug Token

- URL:  https://tricorder.pi-hole.net/fhe6MH15/

**Comment by yubiuser** [comment]
Thanks for the report. This is a known and already fixed issue.
https://github.com/pi-hole/FTL/pull/1305

**Comment by spinofdoom** [comment]
@yubiuser Thank you for the quick response! So if it's fixed now, that percentage should adjust to positive as more `other` queries occur?

**Comment by yubiuser** [comment]
It's fixed, but only in the `development` version. The fix has not been released yet. This will happen in the next Pi-hole version.

**Comment by spinofdoom** [comment]
Excellent, thanks for your help.
