### ISSUE TITLE
Special domain handling should not return status "OK (cached)"

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/FTL#1334]
Pi-hole FTL v5.15, Web v5.12 and Core v5.10 

Pi-hole FTL has some special domains it blocks internally by default if not configured otherwise: the MOZILLA_CANARY domain `use-application-dns.net` and the BLOCK_ICLOUD_PR domains `mask.icloud.com` and `mask-h2.icloud.com`

The return status for those domains is "OK (cached)" which can be confusing for users as it is not clear that the query was actually blocked and treated in a special way. 

I suggest we return something like "Blocked (FTL special domain)"

See https://github.com/pi-hole/pi-hole/issues/4559#issuecomment-1104623597 for a user reporting the issue.

**Comment by jfb-pihole** [comment]
Although the status is OK, the reply is always NXDOMAIN.  Users don't seem to get over to this column.

**Comment by yubiuser** [comment]
Sure. But it does not indicate why the answer is `NXDOMAIN`

**Comment by jfb-pihole** [comment]
Agree and I concur that a unique status for the special FTL domains is warranted.

**Comment by DL6ER** [comment]
Please try branch `new/query_special_domain` - expected status would be something like `Unknown (16)` (the web interface has to learn the new code in a follow-up PR.
