### ISSUE TITLE
;reply=IP got logged

### ISSUE THREAD

**Issue by regae** [pi-hole/FTL#1339]
when using regex ;reply=IP, when the domain got hit, the action is logged.
isn't it supposed to be a member of DEBUG_QUERIES ?
https://github.com/pi-hole/FTL/blob/4bb0bfe939cc43c23639163deaf15a218e692acb/src/dnsmasq_interface.c#L1451-L1452

it's a small thing, but flooding the logfile when using a popular domain.

**Comment by DL6ER** [comment]
Thanks for the hint. You are right and I just opened #1343 to fix this.
