### ISSUE TITLE
FATAL: create_shm(): Failed to create shared memory object "FTL-lock": Permission denied

### ISSUE THREAD

**Issue by Rychveldir** [pi-hole/FTL#1340]
### Versions

- Pi-hole:  v5.10
- AdminLTE:  v5.12
- FTL:  v5.15

### Platform

- OS and version:  Ubuntu 22.04 LTS

- Platform:  Avalue ECM-APL2(CAPL200S) Mainboard, Intel Celeron CPU

### Expected behavior

pihole-FTL will not start after install

### Actual behavior / bug

status of pihole-FTL service:
● pihole-FTL.service - LSB: pihole-FTL daemon
     Loaded: loaded (/etc/init.d/pihole-FTL; generated)
     Active: active (exited) since Sun 2022-04-24 18:03:17 UTC; 5h 1min ago
       Docs: man:systemd-sysv-generator(8)
    Process: 20503 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)
        CPU: 49ms

Apr 24 18:03:17 kserv systemd[1]: Starting LSB: pihole-FTL daemon...
Apr 24 18:03:17 kserv pihole-FTL[20503]: Not running
Apr 24 18:03:17 kserv su[20513]: (to pihole) root on none
Apr 24 18:03:17 kserv su[20513]: pam_unix(su:session): session opened for user pihole(uid=998) by (uid=0)
Apr 24 18:03:17 kserv su[20513]: pam_unix(su:session): session closed for user pihole
Apr 24 18:03:17 kserv systemd[1]: Started LSB: pihole-FTL daemon.

content of pihole-FTL.log:
`[2022-04-24 18:03:17.174 20515M] ########## FTL started on kserv! ##########
[2022-04-24 18:03:17.174 20515M] FTL branch: master
[2022-04-24 18:03:17.174 20515M] FTL version: v5.15
[2022-04-24 18:03:17.174 20515M] FTL commit: 4bb0bfe
[2022-04-24 18:03:17.174 20515M] FTL date: 2022-04-20 19:35:19 +0100
[2022-04-24 18:03:17.174 20515M] FTL user: pihole
[2022-04-24 18:03:17.174 20515M] Compiled for x86_64 (compiled on CI) using gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
[2022-04-24 18:03:17.174 20515M] FATAL: create_shm(): Failed to create shared memory object "FTL-lock": Permission denied
[2022-04-24 18:03:17.174 20515M] Initialization of shared memory failed.
`

/dev/shm/ is empty

### Steps to reproduce

installed as root via:
PIHOLE_SKIP_OS_CHECK=true bash -c "$(curl -sSfL https://install.pi-hole.net)"
on a freshly installed ubuntu 22.04 LTS server

## Debug Token

- URL:  

When i run the debug command, i get:
Error: in prepare, no such table: message
This:command not found

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

Yes, 22.04 is not yet supported, but people report being able to run it nonetheless.

**Comment by DL6ER** [comment]
What are the permissions on `/dev/shm` on your system?

```
ls -lh /dev | grep shm
```

?

**Comment by Rychveldir** [comment]
Kind of what I expected:

`drwxr-xr-x 2 root root            40 Apr 23 15:57 shm`

does pihole usually change this?

**Comment by Rychveldir** [comment]
I checked a 20.04 version i have running aswell and there it is:

`drwxrwxrwt   2 root root          40 Apr 24 03:15 shm`

hmmm what it the t at the end? can i change that with chmod 777? What else might be missing?

**Comment by Rychveldir** [comment]
Did a fresh install on a 22.04 VM using the same command line, works as expected - no i'm stumped, apparently it's my hardware and not the 22.04 version...

**Comment by rdwebdesign** [comment]
I tried to install in a VM, with Ubuntu 22, using every install method I know (except docker).
I couldn't replicate the issue.

**Comment by DL6ER** [comment]
@Rychveldir we don't mess with the permissions of this important system directory, it must have been something else on your system causing this. I don't think it can be the hardware, really. This is likely an issue with some third-party software you have installed

**Comment by Rychveldir** [comment]
@DL6ER This was a totally fresh ubuntu install. I think the only thing i installed before pihole was samba. I could not replicate it either on other machines. I will do a fresh install and try again! Thanks for the help!

**Comment by DL6ER** [comment]
You're welcome. Feel free to either re-open or create a new issue ticket if you encounter this again and we'll take another look.
