### ISSUE TITLE
summed up pie chart values wrong

### ISSUE THREAD

**Issue by r2ixuz** [pi-hole/FTL#1348]
On current version: Docker Tag [2022.04.3] / Pi-hole [v5.10] / FTL [v5.15]

When using dnsmasq parameter "all-servers" the dashboard pie chart for upstream servers shows too large values:

<img width="257" alt="Bildschirmfoto 2022-05-17 um 19 34 20" src="https://user-images.githubusercontent.com/15087554/168876082-6db1d33f-828b-4c6a-a1d2-6801baf998f4.png">

**Comment by DL6ER** [comment]
Sorry, I haven't seen this issue so far as I wasn't notified of the transferred issue ticket.

@r2ixuz Please try if this bug is resolved after running
```
pihole checkout ftl fix/all-servers
```

**Comment by r2ixuz** [comment]
Not possible with my Docker installation, sorry.

**Comment by yubiuser** [comment]
This will be part of the next Pi-hole release. We will close the issue when we release the next version. Feel free to re-open if the issue persists.

**Comment by yubiuser** [comment]
Fixed with https://github.com/pi-hole/FTL/releases/tag/v5.16
