### ISSUE TITLE
macvendor.py wireshark URL is outdated breaking macvendor.py script

### ISSUE THREAD

**Issue by rshxyz** [pi-hole/FTL#1351]
### Versions
pihole -v
  Pi-hole version is v5.10 (Latest: v5.10)
  AdminLTE version is v5.12 (Latest: v5.12)
  FTL version is v5.15 (Latest: v5.15)

### Platform

- Platform:  Raspberry Pi

### Expected behavior
Running the following python script should create a macvendor.db
https://raw.githubusercontent.com/pi-hole/FTL/master/tools/macvendor.py
### Actual behavior / bug

From what I can tell the URL no longer works
urllib.request.urlretrieve("https://code.wireshark.org/review/gitweb?p=wireshark.git;a=blob_plain;f=manuf", "manuf.data")

I believe the gitlab URL is the new one, I used it and the python script worked
https://www.wireshark.org/tools/oui-lookup.html
https://gitlab.com/wireshark/wireshark/-/raw/master/manuf

### Steps to reproduce

wget https://raw.githubusercontent.com/pi-hole/FTL/master/tools/macvendor.py
python macvendor.py 
Downloading...
Traceback (most recent call last):
  File "/usr/lib64/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib64/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib64/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib64/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib64/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gecko/docker/miniflux/macvendor.py", line 25, in <module>
    urllib.request.urlretrieve("https://code.wireshark.org/review/gitweb?p=wireshark.git;a=blob_plain;f=manuf", "manuf.data")
  File "/usr/lib64/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib64/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib64/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib64/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by DL6ER** [comment]
Thanks for the report! A bugfix is in progress.

**Comment by yubiuser** [comment]
Fixed with https://github.com/pi-hole/FTL/releases/tag/v5.16

**Comment by moritzbeck01** [comment]
Is the `macvendor.db` file even automatically created (in Docker environments) (anymore)?
I cannot find any reference to `macvendor.py`. Do I need to run it myself?

**Comment by yubiuser** [comment]
It's downloaded from our servers during installation.
https://github.com/pi-hole/pi-hole/blob/a28d691387ebbe8bc2e017dd9b10b7a16284541d/automated%20install/basic-install.sh#L2324

The install script runs in Docker too
https://github.com/pi-hole/docker-pi-hole/blob/c784963b83b6f18a7126cd9568c6b89944cb5f68/install.sh#L58

**Comment by DL6ER** [comment]
Furthermore, it is downloaded on every upgrade and regenerated by a cron job running every Monday on the server. Running the same task distributed on all Pi-holes out there seems like a massive waste of resources.

**Comment by moritzbeck01** [comment]
> It's downloaded from our servers during installation. https://github.com/pi-hole/pi-hole/blob/a28d691387ebbe8bc2e017dd9b10b7a16284541d/automated%20install/basic-install.sh#L2324
> 
> The install script runs in Docker too https://github.com/pi-hole/docker-pi-hole/blob/c784963b83b6f18a7126cd9568c6b89944cb5f68/install.sh#L58

Thanks for the fast answer, I can see where my mistake was. I was searching in the FTL (for whatever reason) and Docker repository, where it just references the install script.

> Furthermore, it is downloaded on every FTL update and regenerated by a cron job running every Monday on the server. Running the same task distributed on all Pi-holes out there seems like a massive waste of resources.

You have probably already guessed it, but the file is not there on my current Docker install, even though I can remember that it used to be there on my previous normal install.
Is it possible that it has something to do with container DNS? I automatically set the Pi-hole IP as container DNS in the docker run script for all my containers (because Docker doesn't like if I put localhost lol), maybe it fails since it tries to download the file before it can serve itself DNS?

**Comment by moritzbeck01** [comment]
> Is it possible that it has something to do with container DNS? I automatically set the Pi-hole IP as container DNS in the docker run script for all my containers (because Docker doesn't like if I put localhost lol), maybe it fails since it tries to download the file before it can serve itself DNS? I can see nothing in the Docker logs about that though.

Even when setting a different DNS through Docker the macvendor file is not created on container creation. Should I open a new issue for this?

**Comment by DL6ER** [comment]
Yes, please open an issue in the docker repository

**Comment by moritzbeck01** [comment]
> Yes, please open an issue in the docker repository

Thanks, just did!
