### ISSUE TITLE
'PIHOLE_PTR=false' only used for A and AAAA queries

### ISSUE THREAD

**Issue by Palando** [pi-hole/FTL#1387]
### Versions

- Pi-hole:  Pi-hole version is v5.11.4 (Latest: v5.11.4)
- AdminLTE:  AdminLTE version is 5.13 (Latest: v5.13)
- FTL:  FTL version is v5.16.1 (Latest: v5.16.1)

### Platform

- OS and version:  Debian 11 (Bullseye)

- Platform: x86_64 (Intel Core i5)

### Expected behavior

When the setting 'PIHOLE_PTR=false' is set and the Pi-Hole host makes queries, then in the client column the PTR record should be used as client name. e.G. when the PTR record is homeserver.example.com, it should be listed. 

### Actual behavior / bug

For A and AAAA records the behavior is as expected, but for DS and DNSKEY queries the name pi.hole is used.

### Steps to reproduce

1. Have a PTR record in your other DNS server for the Pi-Hole host
2. Set PIHOLE_PTR=false in the file /etc/pihole/pihole-FTL.conf
3. Restart pihole-FTL
4. From the Pi-Hole host make some A, AAAA and DS queries
5. View the query log. In the DS queries the client name is pi.hole. In the A and AAAA queries the client name is as in the PTR record

## Debug Token

- URL: https://tricorder.pi-hole.net/sUNNnH4F

### Screenshots

![pihole](https://user-images.githubusercontent.com/7053047/178168376-04583056-b224-46a1-a3f3-a26abb1cc96a.png)
(homeserver and pi.hole are the identical computer)

### Additional context

N/A

**Comment by yubiuser** [comment]
Setting `PIHOLE_PTR` to `false` is the same as `none`.

https://github.com/pi-hole/FTL/blob/5ff5bed9f86afe81ba7640170763225fa4cbbcef/src/config.c#L651-L676

https://docs.pi-hole.net/ftldns/configfile/#pihole_ptr

Try if `PIHOLE_PTR=HOSTNAMEFQDN` does solve the issue for you.

**Comment by DL6ER** [comment]
> but for DS and DNSKEY queries the name pi.hole is used.

This this is expected and by design.

The columns shows which client made a request. However, DNSSEC requests are not made by anyone but `pihole-FTL` is generating them internally. In order to distinguish them from queries being made by some third party, they are shown to originate from `::` - this IP address gets the nicer name `pi.hole` merely for displaying.
