### ISSUE TITLE
FTL will not start if ipv6 is disabled via kernel, but report all ok

### ISSUE THREAD

**Issue by piengeng** [pi-hole/FTL#1406]
used pihole for a long time, no issue until recently, `ipv6.disable=1` on raspberry pi 3b+ on `/boot/cmdline.txt` just to load 1 less module on linux kernel.

workaround is to enable back ipv6 using `ipv6.disable=0` on `/boot/cmdline.txt` hope anyone researching why their pihole dns server just won't start, have to enable back ipv6 despite not using ipv6 for their internal network.

**Comment by joshuaseltzer** [comment]
Thanks for tracking this down. My PiHole instance is also crashing and failing to start for the same reason.

FYI 15.16.1 did not have this issue. 15.16.2 introduced this problem.

**Comment by yubiuser** [comment]
> My PiHole instance is also crashing 

Could you please provide the crash report/backtrace from `/var/log/pihole/FTL.log`?

**Comment by Pippin1st** [comment]
Hi, I also posted on the forum.
After enabling ipv6 in
`sudo nano /etc/default/grub`
and doing
`sudo update-grub`
`sudo reboot`
it seems to work again.
This is on Ubuntu server:
`Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-46-generic x86_64)`

**Comment by yubiuser** [comment]
We found the reason why it's failing when no IPv6 is available. We'll prepare a fix for this.

**Comment by joshuaseltzer** [comment]
> We found the reason why it's failing when no IPv6 is available. We'll prepare a fix for this.

Thanks for the update and quick fix. If you still need logs from my machine, let me know and I can provide them later today.

**Comment by yubiuser** [comment]
Thanks for the offer. More logs are not required at the moment. We probably need testers once we have a special branch with the fix

**Comment by joshuaseltzer** [comment]
> Thanks for the offer. More logs are not required at the moment. We probably need testers once we have a special branch with the fix

If the process for testing out something from another branch is easy and instructions are provided, I'd be happy to give it a shot when it's ready.

**Comment by Fossalta** [comment]
Was running into same issue where FTL could no longer start because of IPv6 not being enabled.

Quick fix for now was to revert to previous FTL:

cd /etc/.pihole
sudo pihole checkout ftl v5.16.1

Afterwards it was working again.

**Comment by yubiuser** [comment]
```
cd /etc/.pihole
sudo pihole checkout ftl v5.16.1
```

The `cd` should not be required.

**Comment by PromoFaux** [comment]
> We probably need testers once we have a special branch with the

Just a reminder to @pi-hole/ftl-maintainers (whoever ends up preparing the branch) - if this needs to go out semi-urgently, then base the fix on the `master` branch, please, so that we can easily release it as a hotfix

**Comment by DL6ER** [comment]
Please try if
```
pihole checkout ftl fix/no_telnet_is_okay
```
resolves the issue for you. We still expect an error getting into your log but FTL won't fail hard at this point - but simply accept it cannot serve the API on IPv6.

**Comment by DL6ER** [comment]
The next version of FTL has been released. Please update and run
```
pihole checkout master
```
to get back on-track if you used my command above. The fix/feature branch you switched to will not receive any further updates.

Thanks for helping us to make Pi-hole better for us all!

If you have any issues, please either reopen this ticket or (preferably) create a new ticket describing the issues in further detail and only reference this ticket. This will help us to help you best.
