### ISSUE TITLE
FTL error during pihole -up

### ISSUE THREAD

**Issue by davepae** [pi-hole/FTL#1414]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate

**How familiar are you with the codebase?:**

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---

**[BUG | ISSUE] Expected Behaviour:**
pihole -up completes without FTL error

**[BUG | ISSUE] Actual Behaviour:**
pihole -up exits with following error:
  [✓] Detected ARMv7 processor (with hard-float support)
  [i] Checking for existing FTL binary...
curl: error while loading shared libraries: libhogweed.so.6: cannot open shared object file: No such file or directory
  [i] Downloading and Installing FTL...curl: error while loading shared libraries: libhogweed.so.6: cannot open shared object file: No such file or directory
  [✗] Downloading and Installing FTL
   Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-armv7-linux-gnueabihf not found
  [✗] FTL Engine not installed

  Unable to complete update, please contact Pi-hole Support

**[BUG | ISSUE] Steps to reproduce:**
sudo
pihole -up

-
-
-
-

**Log file output [if available]**

  [✓] Detected ARMv7 processor (with hard-float support)
  [i] Checking for existing FTL binary...
curl: error while loading shared libraries: libhogweed.so.6: cannot open shared object file: No such file or directory
  [i] Downloading and Installing FTL...curl: error while loading shared libraries: libhogweed.so.6: cannot open shared object file: No such file or directory
  [✗] Downloading and Installing FTL
   Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-armv7-linux-gnueabihf not found
  [✗] FTL Engine not installed

  Unable to complete update, please contact Pi-hole Support

**Device specifics**

Hardware Type: rPi4
OS: PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by davepae** [comment]
UG! its my system. curl is throwing a library error. closing.

**Comment by jay-ramani** [comment]
Hi Dave,

I'm facing a similar error (below) after upgrading my packages on Manjaro Linux XFCE (arch based) Edition.

```
pihole-FTL: error while loading shared libraries: libhogweed.so.6: cannot open shared object file: No such file or directory
```

What did you do to resolve the issue? When I query the package manager for libhogweed or libhogweed64, I don't get any result.

Thanks and cheers.

**Comment by dschaper** [comment]
It's a part of the `nettle` crypto libraries.
