### ISSUE TITLE
inconsistent CNAME blocking (due to missing IPv6 entry)

### ISSUE THREAD

**Issue by jpgpi250** [pi-hole/FTL#1421]
### Versions
  Pi-hole version is v5.12 (Latest: v5.12)
  AdminLTE version is v5.14.1 (Latest: v5.14.1)
  FTL version is v5.17 (Latest: v5.17)

**older versions also affected!**

### Platform
Linux raspberrypi 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux

### Expected behavior
consistent cname behaviour (blocking)

### Actual behavior / bug

A queries are blocked due to CNAME detection, AAAA queries are allowed if the IPv6 address is missing.
**A lot of research already done, see [here](https://discourse.pi-hole.net/t/cname-cant-explain-this/57457)**
The problem occurs for all types (gravity entry, exact blacklist, regex blacklist), e.g. no IPv6 for the domain defined -> allowed, even if the domain is blocked (works for IPv4 entries

### Steps to reproduce
dig +short AAAA www.metrotime.be
g.ezoic.net.
dig +short A www.metrotime.be
0.0.0.0

**Comment by DL6ER** [comment]
Discussion is continuing in [the linked Discourse discussion](https://discourse.pi-hole.net/t/cname-cant-explain-this/57457). Thanks for cross-posting it here.

**Comment by DL6ER** [comment]
Related branch is [`tweak/CNAME_inspection`](https://github.com/pi-hole/FTL/tree/tweak/CNAME_inspection).

**Comment by jpgpi250** [comment]
see the [topic](https://discourse.pi-hole.net/t/cname-cant-explain-this/57457/13), FTL crash when visiting site (https://nl.metrotime.be/), but the test script reports all OK (ran this before browsing to the site).

**Comment by jpgpi250** [comment]
bug solved / tweak/CNAME_inspection /  FTL version is tweak/CNAME_inspection vDev-d7c5519

will continue running this branch, and report problems.

**can't emphasize this enough: thanks a lot, again, for your time, effort and dedication**

**Comment by rdwebdesign** [comment]
I will close the issue, since you reported it's solved.

Feel free to reopen, if you need.

**Comment by jpgpi250** [comment]
Now running (as per your instructions):
  Pi-hole version is v5.12 (Latest: v5.12)
  AdminLTE version is v5.14.1 (Latest: v5.14.2)
  FTL version is tweak/cnamea_and_regexes vDev-2ab8434 (Latest: v5.17)

It will take some time to report, MAXDBDAYS=8, additional_info needs to be populated again...

I've further updated my test scenario with the additional CNAME and IPv6 tests included -> 100% OK with this branch (tweak/CNAME_inspection / FTL version is tweak/CNAME_inspection vDev-d7c5519)

In case your interested:

- the zone files (NSD)
[zones.zip](https://github.com/pi-hole/FTL/files/9488870/zones.zip)

- the gravity entries (file:///\<wherever\>/testftl.txt)
[gravity entries.zip](https://github.com/pi-hole/FTL/files/9488881/gravity.entries.zip)

- the test scenario (json)
[testftl scenario (json).zip](https://github.com/pi-hole/FTL/files/9488885/testftl.scenario.json.zip)

- the sql script to test database locked
[status15.zip](https://github.com/pi-hole/FTL/files/9488894/status15.zip)

- the domainlist entries (disabled by default - I enable them when running the script)
```
# exact
sudo sqlite3 /etc/pihole/gravity.db "insert or ignore into domainlist (domain, type, enabled, comment) values ('exact-blocked.test.ftl', 1, 0, 'CNAME detection type 11 (test.ftl)');"
sudo sqlite3 /etc/pihole/gravity.db "insert or ignore into domainlist (domain, type, enabled, comment) values ('exact-46-blocked.test.ftl', 1, 0, 'CNAME detection type 11 (test.ftl)');"
# regex
sudo sqlite3 /etc/pihole/gravity.db "insert or ignore into domainlist (domain, type, enabled, comment) values ('(\.|^)regex-blocked.+\.ftl$', 3, 0, 'CNAME detection type 10 - regex (test.ftl)');"
sudo sqlite3 /etc/pihole/gravity.db "insert or ignore into domainlist (domain, type, enabled, comment) values ('(\.|^)regex-46-blocked.+\.ftl$', 3, 0, 'CNAME detection type 10 - regex (test.ftl)');"
# regex to test cloaked CNAME
sudo sqlite3 /etc/pihole/gravity.db "insert or ignore into domainlist (domain, type, enabled, comment) values ('(\.|^)cloaked\.ftl$', 3, 0, 'CNAME detection type 10 (test.ftl)');"
```

I haven't included any unbound and nsd configuration files, since you are using PowerDNS...

**Comment by yubiuser** [comment]
Fix released with https://discourse.pi-hole.net/t/pi-hole-ftl-v5-18-web-v5-15-and-core-v5-12-1-released/57894
