### ISSUE TITLE
api/api.c: compilation warning in listInterfaces

### ISSUE THREAD

**Issue by sbinet** [pi-hole/FTL#1424]
### Versions

-  Pi-hole version is v5.14.2 (Latest: v5.12)
-  AdminLTE version is v5.14.2 (Latest: v5.14.2)
-  FTL version is v5.17 (Latest: v5.17)

### Platform

- OS and version:  ArchLinux

- Platform:  RPi4

### Expected behavior

A clean compilation.

### Actual behavior / bug

Compiling the latest release of FTL, I see:
```
[ 87%] Building C object src/api/CMakeFiles/api.dir/api.c.o
/home/pi/.cache/yay/pi-hole-ftl/src/FTL-5.17/src/api/api.c: In function ‘listInterfaces’:
/home/pi/.cache/yay/pi-hole-ftl/src/FTL-5.17/src/api/api.c:1554:20: warning: the comparison will always evaluate as ‘true’ for the address of ‘d_name’ will never be NULL [-Waddress]
 1554 |                 if(!dp->d_name || strcmp(dp->d_name, ".") == 0 || strcmp(dp->d_name, "..") == 0)
      |                    ^
In file included from /usr/include/dirent.h:61,
                 from /home/pi/.cache/yay/pi-hole-ftl/src/FTL-5.17/src/api/api.c:1525:
/usr/include/bits/dirent.h:33:10: note: ‘d_name’ declared here
   33 |     char d_name[256];           /* We must not include limits.h! */
      |          ^~~~~~
```
https://github.com/pi-hole/FTL/blob/be3bad3/src/api/api.c#L1553..L1556

it seems indeed that, as `d_name` is an array, `!dp->d_name` won't ever be `false`.

**Comment by DL6ER** [comment]
Thanks, you are right that the first condition can be removed without replacement in this case. Out of curiosity: What compiler (which version) showed this error and what is the operating system (+ version) you are compiling on?

**Comment by sbinet** [comment]
```
$> gcc --version
gcc (GCC) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

on an (up-to-date) ArchLinux-ARM, so there's no version to speak of :)

**Comment by yubiuser** [comment]
Fixed in https://github.com/pi-hole/FTL/releases/tag/v5.19
