### ISSUE TITLE
[BUG] special/CI_development branch

### ISSUE THREAD

**Issue by giulio-coa** [pi-hole/FTL#1433]
The last commit broke something, so the checks on the various architectures fail.

**Comment by PromoFaux** [comment]
Where are you seeing this? And/Or what are you using that branch for?

The only place that special branch is used is when building the build containers:

https://github.com/pi-hole/docker-base-images/actions/runs/3030214407

**Comment by giulio-coa** [comment]
I'm trying to add Alpine Linux in the list of supported OS
To do this, I must to add `musl` architectures to the docker-base-images repo.

**Comment by giulio-coa** [comment]
![Screenshot_20220916_183820](https://user-images.githubusercontent.com/34110430/190687853-2286df80-f4a0-4de8-83b2-7c12c7ebb6a1.png)

**Comment by PromoFaux** [comment]
Just merged dev into that branch.. I guess try and see if that makes a difference...

**Comment by giulio-coa** [comment]
It doesn't work

**Comment by giulio-coa** [comment]
> It doesn't work ![Screenshot_20220917_094233](https://user-images.githubusercontent.com/34110430/190846295-baba42c8-6958-432a-935c-eab4bfc3590e.png)



> It doesn't work ![Screenshot_20220917_094233](https://user-images.githubusercontent.com/34110430/190846295-baba42c8-6958-432a-935c-eab4bfc3590e.png)

Obviously, I tried with an arch that I didn't develop

**Comment by giulio-coa** [comment]
@PromoFaux any news ?

**Comment by PromoFaux** [comment]
The branche `special/CI_development` is working, as can be seen here: https://github.com/pi-hole/docker-base-images/actions/runs/3120568609

Clearly the changes you have made on your fork are causing some issues with the build process. Have you tried to manually run the steps inside a container and see what happens?
