### ISSUE TITLE
Audit log empty in v5.15.

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/FTL#1435]
Even if not a single domain is audited, the log is completely empty.

Needs  investigation.

**Comment by rube200** [comment]
I'm having the same problem. It starts some weeks ago after a update, currently i have the latest version installed (v5.18.1).

```root@Host:~# echo ">top-domains for audit >quit" | nc -v 127.0.0.1 4711
Connection to 127.0.0.1 4711 port [tcp/*] succeeded!

root@Host:~# echo ">top-domains >quit" | nc -v 127.0.0.1 4711
Connection to 127.0.0.1 4711 port [tcp/*] succeeded!
0 370 raw.githubusercontent.com
1 293 grafana.com
2 202 lb._dns-sd._udp.0.1.168.192.in-addr.arpa
3 198 discord.com
4 190 lb._dns-sd._udp.0.0.0.100.in-addr.arpa
5 187 lb._dns-sd._udp.198.6.126.100.in-addr.arpa
6 186 www.google.com
7 183 graph.facebook.com
8 178 lb._dns-sd._udp.lan
9 151 teams.events.data.microsoft.com```

**Comment by Eddie-BS** [comment]
Same problem here, since a week or so, after updating pihole. the audit log is empty

**Comment by Copysiper** [comment]
Same issue. Is there a way to temporarily downgrade to older version of ftl until it's fixed? Liked that feature a lot

Pi-hole [v5.12.2](https://github.com/pi-hole/pi-hole/releases/v5.12.2)
FTL [v5.18.1](https://github.com/pi-hole/FTL/releases/v5.18.1)
Web Interface [v5.15.1](https://github.com/pi-hole/AdminLTE/releases/v5.15.1)

**Comment by GvY85** [comment]
Same problem here

**Comment by DL6ER** [comment]
Sorry for the massive delay - I just found the time to work on this (and, yes, I forgot about it meanwhile so thanks for the reminders @Copysiper @GvY85). This bug is an unintended side-effect of https://github.com/pi-hole/FTL/pull/1409.

Please try
```
pihole checkout ftl fix/audit_log
```
and report back if this restores the audit log feature for you.

**Comment by Eddie-BS** [comment]
YES,
this brings me info in the audit log screen !

**Comment by Eddie-BS** [comment]
will this 
pihole checkout ftl fix/audit_log
automaticly change back to "master" 
or do I/we need to do something ?

**Comment by Copysiper** [comment]
Yes, that fix worked properly, thank you!

**Comment by yubiuser** [comment]
> automaticly change back to "master"

No.You need to change back to master by `pihole checkout ftl master` before performing the next Pi-hole update

**Comment by yubiuser** [comment]
Fixed with https://github.com/pi-hole/FTL/releases/tag/v5.18.2
