### ISSUE TITLE
Pi keeps spamming the same errors about inaccessible Adlists in  "pi-hole diagnosis"

### ISSUE THREAD

**Issue by Knuschberkeks** [pi-hole/FTL#1475]
### Versions

- Pi-hole:  v5.13
- AdminLTE:  v5.16
- FTL:  v5.18.2

### Platform

- OS and version:  Raspberry Pi OS 11 (Bullseye)

- Platform:  Rapsberry Pi Zero W

### Expected behavior

_Show errors once in the pi-hole diagnosis list until they occur again._

### Actual behavior / bug

_In my last gravity run (the normal scheduled one on sunday night) there were 2 adlists inaccessible. Since then the same messages about the two adlists keep piling on in the "Pi-hole diagnosis" tab. I am now up to 158 messages without a gravity run in between._

### Steps to reproduce

I have no idea.

## Debug Token

- URL:  https://tricorder.pi-hole.net/3VY4zNqu/

**Comment by Knuschberkeks** [comment]
> We can tweak this a bit. Moving in the right repo.

do you mean this is actually expected behaviour?

**Comment by PromoFaux** [comment]
How often are you running pihole -g (do you have a cron job for this, maybe?)

It may be an oversight that the message shows up multiple times, however removing the defunct adlists from your install will stop the message from appearing. There is no sense in keeping inaccessible lists 🤷‍♂️

**Comment by Knuschberkeks** [comment]
> How often are you running pihole -g (do you have a cron job for this, maybe?)
> 
> 
> 
> It may be an oversight that the message shows up multiple times, however removing the defunct adlists from your install will stop the message from appearing. There is no sense in keeping inaccessible lists 🤷‍♂️

I only run the gravity update that pihole does anyway every week.

The lists seem to only have been unavailable temporarily. I can access them nö if I click on them.

**Comment by rdwebdesign** [comment]
If the lists are available, the warnings should be gone after a `pihole-FTL` restart. They are reappearing?

**Comment by Knuschberkeks** [comment]
Ok i think I have to clarify what is happening, it seems like I didn't explain it good enough, I'll try again:
Pi hole did update Gravity on Sunday night, as it always does. Then on Monday I log into the admin interface. There are already about 40 identical messages about the same two lists, according to the times they came in they were just minutes apart. I delete them all. I log out. I log back in a few hours later. There are now over 100 of those same messages, again they came in just minutes apart. I am 100% certain that gravity has not been updated since sunday.
My problem is that I think I should me informed once about the list. If I delete the messages I clearly read them. It should only inform me again if the lists are still unavailable during the next gravity update.

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/FTL/releases/tag/v5.19.2
