### ISSUE TITLE
There was a problem applying your settings. Debugging information: PHP error (2): fsockopen(): unable to connect to 127.0.0.1:4711 (Connection refused) in /var/www/html/admin/scripts/pi-hole/php/FTL.php:47

### ISSUE THREAD

**Issue by defisit** [pi-hole/FTL#1526]
### Versions

- Pi-hole:  5.14.2
- AdminLTE:  5.20
- FTL:  5.18

### Platform
- OS and version:  Debian 10
- Platform:  LXC on Proxmox

### Expected behavior

Updating to the latest version of pi-hole results in 'unable to complete update'

  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.31-1~deb10u2
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:     update available
  [i] Web Interface:    update available
  [i] FTL:              update available

  [i] Pi-hole core files out of date, updating local repo.
  [✓] Check for existing repository in /etc/.pihole
  [i] Update repo in /etc/.pihole...HEAD is now at 9048429b v5.15 (#5082)
  [✓] Update repo in /etc/.pihole

  [i] If you had made any changes in '/etc/.pihole/', they have been stashed using 'git stash'

  [i] Pi-hole Web Admin files out of date, updating local repo.
  [✓] Check for existing repository in /var/www/html/admin
  [i] Update repo in /var/www/html/admin...HEAD is now at 30668d4d v5.18.1 (#2493)
  [✓] Update repo in /var/www/html/admin

  [i] If you had made any changes in '/var/www/html/admin/', they have been stashed using 'git stash'

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] SELinux not detected
  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.31-1~deb10u2

  [✗] Checking apt-get for upgraded packages
      Kernel update detected. If the install fails, please reboot and try again
  [i] Checking for / installing Required dependencies for OS Check...
  [✓] Checking for grep
  [✓] Checking for dnsutils

  [✓] Supported OS detected
  [i] Checking for / installing Required dependencies for this install script...
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Performing unattended setup, no dialogs will be displayed
  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Checking for / installing Required dependencies for Pi-hole software...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for iputils-ping
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for idn2
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [✓] Checking for netcat-openbsd
  [✓] Checking for procps
  [✓] Checking for jq
  [✓] Checking for lighttpd
  [✓] Checking for php7.3-common
  [✓] Checking for php7.3-cgi
  [✓] Checking for php7.3-sqlite3
  [✓] Checking for php7.3-xml
  [✓] Checking for php7.3-intl
  [✓] Checking for php7.3-json

  [✓] Enabling lighttpd service to start on reboot...
  [✓] Checking for user 'pihole'

  [i] FTL Checks...

  [✓] Detected x86_64 processor
  [i] Checking for existing FTL binary...
  [✓] Downloading and Installing FTL
  [✓] Installing scripts from /etc/.pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf

  [✓] Installing sudoer file

  [✓] Installing latest Cron script

  [i] Installing latest logrotate script...
        [i] Existing logrotate file found. No changes made.
  [i] Backing up /etc/dnsmasq.conf to /etc/dnsmasq.conf.old
  [✓] man pages installed and database updated
  [i] Testing if systemd-resolved is enabled
  [i] Systemd-resolved is not enabled
  [✓] Restarting lighttpd service...
  [✓] Enabling lighttpd service to start on reboot...
  [i] Restarting services...
  [✓] Enabling pihole-FTL service to start on reboot...
  [i] Restarting pihole-FTL service...
  Unable to complete update, please contact Pi-hole Support

>>Furthermore: loading the admin page shows below:

**There was a problem applying your settings.
Debugging information:
PHP error (2): fsockopen(): unable to connect to 127.0.0.1:4711 (Connection refused) in /var/www/html/admin/scripts/pi-hole/php/FTL.php:47**

_A clear and concise description of what you expected to happen._

I would expect the update to complete succesfully. Never had any issues with updating.

### Actual behavior / bug

pihole status shows DNS service isnt running.

[✗] DNS service is NOT running

### Steps to reproduce

I have attempted to update pi-hole also on my other pi-hole instance on Proxmox, Same issue.
However, updating pihole on my Raspberry 4 went fine. Same configuration as the linux container.

Reboot the LXC doesnt solve the issue.

## Debug Token

- URL:  https://tricorder.pi-hole.net/lD8cPW1B/

### Screenshots

![image](https://user-images.githubusercontent.com/61313374/213191346-a3dcd19d-62e1-4637-893f-654f8179e64e.png)

**Comment by defisit** [comment]
> There is a warning about problems with the database:
> 
> ```
> *** [ DIAGNOSING ]: Pi-hole FTL Query Database
> -rw-rw-r-- 1 pihole pihole 87M Jan 18 14:41 /etc/pihole/pihole-FTL.db
> [i] Checking integrity of /etc/pihole/pihole-FTL.db ... (this can take several minutes)
> [✗] Integrity errors in /etc/pihole/pihole-FTL.db found.
> 
>     TEXT value in query_storage.additional_info
>     TEXT value in query_storage.additional_info
>     TEXT value in query_storage.additional_info
>     TEXT value in query_storage.additional_info
>     TEXT value in query_storage.additional_info
> ```
> 
> Can you try to rename the database file to something like `/etc/pihole/pihole-FTL.db.backup` and try again?

Renamed, but FTL still wont start. After reboot host same.

-rw-rw-r--  1 pihole pihole 90955776 Jan 18 14:41 pihole-FTL-db.backup
-rw-r--r--  1 root   root          0 Jan 18 20:04 pihole-FTL.db

root@pi4:/etc/pihole# pihole restartdns
  [✗] Job for pihole-FTL.service failed because the control process exited with error code.
See "systemctl status pihole-FTL.service" and "journalctl -xe" for details.

**Comment by rdwebdesign** [comment]
This seems to be a permission problem.

The new file was created using a different user.

**Comment by jfb-pihole** [comment]
"Renamed, but FTL still wont start. After reboot host same."

Use this method to create a new database with the correct permissions:

`sudo service pihole-FTL stop`

`sudo mv /etc/pihole/pihole-FTL.db /etc/pihole/pihole-FTL-old.db`

`sudo service pihole-FTL start`

**Comment by DL6ER** [comment]
FTL is designed to run just fine even when the database is corrupted or if there are permission errors. From your debug log there seems to be no error in FTL. It is just stopped. Please run
```
sudo service pihole-FTL start
```
and then check the last lines of the log using
```
tail /var/log/pihole/FTL.log
```
a few times, say, a second, one minute and three minutes. What do you see?

**Comment by defisit** [comment]
nothing is written in FTL.log

root@pi4:/var/log/pihole# pihole status               
  [✗] DNS service is NOT running
root@pi4:/var/log/pihole# sudo service pihole-FTL start
Job for pihole-FTL.service failed because the control process exited with error code.
See "systemctl status pihole-FTL.service" and "journalctl -xe" for details.
root@pi4:/var/log/pihole# tail /var/log/pihole/FTL.log
root@pi4:/var/log/pihole# tail /var/log/pihole/FTL.log
root@pi4:/var/log/pihole# tail /var/log/pihole/FTL.log
root@pi4:/var/log/pihole# ls -latr
total 256
drwxr-xr-x 6 root   root     4096 Jul 10  2022 ..
-rw-r----- 1 pihole pihole 100619 Jan 15 00:00 pihole.log.5.gz
-rw-r--r-- 1 pihole pihole   1326 Jan 15 00:00 FTL.log.3.gz
-rw-r--r-- 1 root   root     7126 Jan 15 03:38 pihole_updateGravity.log
-rw-r----- 1 pihole pihole  55697 Jan 16 17:16 pihole.log.4.gz
-rw-r----- 1 pihole pihole  17847 Jan 17 00:00 pihole.log.3.gz
-rw-r--r-- 1 pihole pihole   3256 Jan 17 00:00 FTL.log.2.gz
-rw-r----- 1 pihole pihole  26015 Jan 18 20:40 pihole.log.2.gz
-rw-r----- 1 pihole pihole   7471 Jan 19 00:00 pihole.log.1
-rw-r----- 1 pihole pihole      0 Jan 19 00:00 pihole.log
-rw-r--r-- 1 pihole pihole  20417 Jan 19 00:00 FTL.log.1
-rw-r--r-- 1 pihole pihole      0 Jan 19 00:00 FTL.log
drwxr-xr-x 2 pihole pihole   4096 Jan 19 00:00 .

**Comment by DL6ER** [comment]
From your output:

> `See "systemctl status pihole-FTL.service" and "journalctl -xe" for details.`

Can you do this? You'll probably need `sudo` in front to get meaningful output.

**Comment by defisit** [comment]
root@pi4:/var/log/pihole# sudo service pihole-FTL start
Job for pihole-FTL.service failed because the control process exited with error code.
See "systemctl status pihole-FTL.service" and "journalctl -xe" for details.
root@pi4:/var/log/pihole# systemctl status pihole-FTL.service
* pihole-FTL.service - Pi-hole FTL
   Loaded: loaded (/etc/systemd/system/pihole-FTL.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2023-01-20 11:19:50 CET; 2s ago
  Process: 240835 ExecStartPre=/opt/pihole/pihole-FTL-prestart.sh (code=exited, status=226/NAMESPACE)
  Process: 240836 ExecStopPost=/opt/pihole/pihole-FTL-poststop.sh (code=exited, status=226/NAMESPACE)


root@pi4:/var/log/pihole# journalctl -xe
Jan 20 11:20:06 pi4 systemd[1]: pihole-FTL.service: Service RestartSec=5s expired, scheduling restart.
Jan 20 11:20:06 pi4 systemd[1]: pihole-FTL.service: Scheduled restart job, restart counter is at 5.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Automatic restarting of the unit pihole-FTL.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Jan 20 11:20:06 pi4 systemd[1]: Stopped Pi-hole FTL.
-- Subject: A stop job for unit pihole-FTL.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A stop job for unit pihole-FTL.service has finished.
-- 
-- The job identifier is 961 and the job result is done.
Jan 20 11:20:06 pi4 systemd[1]: pihole-FTL.service: Consumed 2ms CPU time.
-- Subject: Resources consumed by unit runtime
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit pihole-FTL.service completed and consumed the indicated resources.
Jan 20 11:20:06 pi4 systemd[1]: pihole-FTL.service: Start request repeated too quickly.
Jan 20 11:20:06 pi4 systemd[1]: pihole-FTL.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit pihole-FTL.service has entered the 'failed' state with result 'exit-code'.
Jan 20 11:20:06 pi4 systemd[1]: Failed to start Pi-hole FTL.
-- Subject: A start job for unit pihole-FTL.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit pihole-FTL.service has finished with a failure.
-- 
-- The job identifier is 961 and the job result is failed.
lines 2113-2149/2149 (END)

**Comment by defisit** [comment]
root@pi4:/var/log/pihole# sudo service pihole-FTL start
Job for pihole-FTL.service failed because the control process exited with error code.
See "systemctl status pihole-FTL.service" and "journalctl -xe" for details.
root@pi4:/var/log/pihole# systemctl status pihole-FTL.service
* pihole-FTL.service - Pi-hole FTL
   Loaded: loaded (/etc/systemd/system/pihole-FTL.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2023-01-20 11:19:50 CET; 2s ago
  Process: 240835 ExecStartPre=/opt/pihole/pihole-FTL-prestart.sh (code=exited, status=226/NAMESPACE)
  Process: 240836 ExecStopPost=/opt/pihole/pihole-FTL-poststop.sh (code=exited, status=226/NAMESPACE)
      CPU: 2ms


----
root@pi4:/var/log/pihole# journalctl -xe
Jan 20 11:20:06 pi4 systemd[1]: pihole-FTL.service: Service RestartSec=5s expired, scheduling restart.
Jan 20 11:20:06 pi4 systemd[1]: pihole-FTL.service: Scheduled restart job, restart counter is at 5.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Automatic restarting of the unit pihole-FTL.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Jan 20 11:20:06 pi4 systemd[1]: Stopped Pi-hole FTL.
-- Subject: A stop job for unit pihole-FTL.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A stop job for unit pihole-FTL.service has finished.
-- 
-- The job identifier is 961 and the job result is done.
Jan 20 11:20:06 pi4 systemd[1]: pihole-FTL.service: Consumed 2ms CPU time.
-- Subject: Resources consumed by unit runtime
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit pihole-FTL.service completed and consumed the indicated resources.
Jan 20 11:20:06 pi4 systemd[1]: pihole-FTL.service: Start request repeated too quickly.
Jan 20 11:20:06 pi4 systemd[1]: pihole-FTL.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit pihole-FTL.service has entered the 'failed' state with result 'exit-code'.
Jan 20 11:20:06 pi4 systemd[1]: Failed to start Pi-hole FTL.
-- Subject: A start job for unit pihole-FTL.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit pihole-FTL.service has finished with a failure.
-- 
-- The job identifier is 961 and the job result is failed.
lines 2113-2149/2149 (END)

**Comment by defisit** [comment]
apologies for the large and bold font

**Comment by defisit** [comment]
I believe something is not right between the host system (proxmox) and the LXC. With every attempt, the pi-hole updater mentions there's a kernel-update available, but there's isn't. For the time being I've moved to a VM rather than LXC for pi-hole/unbound.

**Comment by DL6ER** [comment]
Sorry for coming back to you earlier (let me be totally honest: I simply forgot... :disappointed:  ) but good that you found some other approach that works for you. My own experience with LXC and networking weren't great either, for instance, it is completely impossible to install `wireguard` in LXC containers because they are just too lightweight for some networking things. If you want containerization I can only recommend using the official Pi-hole `docker` image which is well maintained and offers trivial extensibility to `unbound` containers (e.g. using `docker compose`).

**Comment by defisit** [comment]
Thank for the advice. I have plans to learn docker and pi-hole would be a very good reason to start that.
