### ISSUE TITLE
DNS name tel.t-online.de only resolved once

### ISSUE THREAD

**Issue by chhe** [pi-hole/FTL#1529]
### Versions

- Pi-hole:  v5.15.3
- AdminLTE:  v5.18.3
- FTL:  v5.20.1

### Platform
- OS and version:  Debian GNU/Linux 11 (bullseye)
- Platform:  Docker via https://github.com/pi-hole/docker-pi-hole/blob/master/examples/docker-compose.yml.example, only host ports are modified (pi-hole DNS port is 5300)

### Expected behavior

`tel.t-online.de` always resolves:
```
$ kdig tel.t-online.de @localhost -p 5300
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 31405
;; Flags: qr rd ra; QUERY: 1; ANSWER: 0; AUTHORITY: 1; ADDITIONAL: 0

;; QUESTION SECTION:
;; tel.t-online.de.             IN      A

;; AUTHORITY SECTION:
tel.t-online.de.        1286    IN      SOA     ns1.edns.t-ipnet.de. hostmaster.t-ipnet.net. 2018022700 43200 1800 1209600 21600

;; Received 108 B
;; Time 2023-02-08 15:33:33 CET
;; From 127.0.0.1@5300(UDP) in 15.9 ms
```

### Actual behavior / bug

`tel.t-online.de` only resolves on first request after a restart of `pihole-FTL`:
```
$ kdig tel.t-online.de @localhost -p 5300
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 31405
;; Flags: qr rd ra; QUERY: 1; ANSWER: 0; AUTHORITY: 1; ADDITIONAL: 0

;; QUESTION SECTION:
;; tel.t-online.de.             IN      A

;; AUTHORITY SECTION:
tel.t-online.de.        1286    IN      SOA     ns1.edns.t-ipnet.de. hostmaster.t-ipnet.net. 2018022700 43200 1800 1209600 21600

;; Received 108 B
;; Time 2023-02-08 15:33:33 CET
;; From 127.0.0.1@5300(UDP) in 15.9 ms
```
Every following request (answered from cache) gets this result:

```
$ kdig tel.t-online.de @localhost -p 5300
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 64891
;; Flags: qr rd ra; QUERY: 1; ANSWER: 0; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; tel.t-online.de.             IN      A

;; Received 33 B
;; Time 2023-02-08 16:01:53 CET
;; From 127.0.0.1@5300(UDP) in 0.7 ms
```

### Steps to reproduce

1. restart `pihole-FTL` 
2. execute `kdig tel.t-online.de @localhost -p 5300` in shell to get non-empty result
3. execute `kdig tel.t-online.de @localhost -p 5300` in shell again to get empty result

## Debug Token

- URL:  https://tricorder.pi-hole.net/iFKfP27u/

### Screenshots

No screenshot.

### Additional context

The same happens with my pi-hole installation on a raspberry pi.

**Comment by dschaper** [comment]
That domain is broken.

https://www.whatsmydns.net/#A/tel.t-online.de

**Comment by dschaper** [comment]
To give more detail, I am able to reproduce what you are seeing but I don't think it's FTL that is wrong.

The initial query returns NOERROR, and not something like NXDOMAIN or an error. 

```plain
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1828
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
```

Additional queries come from cache, as you can see from the very short query time and is identical to the initial query response. It doesn't have the SOA Authority information because it is from cache and is not authoritative. 

```plain
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42114
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
```

So, the domain looks misconfigured.
