### ISSUE TITLE
ABP style entries are not counted as "number" of domains

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/FTL#1573]
Adlist ABP style entries are not added to `gravity.db` as `numbers` because only `exact_domains` are considered here:
https://github.com/pi-hole/FTL/blob/d201776e293e921cb5be00bce89dcd4e997689bb/src/tools/gravity-parseList.c#L293

On ABP style-only lists (e.g. https://small.oisd.nl/) this leads to `0` being added as `numbers`. The web interface will show this as

```
Number of domains on this list:   | 0
```

Which is kind of correct, but certainly not what one would expect. The web text would need a bit tweaking as well (e.g. Number of valid entries on this list) but i think we should add the sum of `exact_domains` and `abp_domains`

**Comment by rdwebdesign** [comment]
I agree with your comment about changing the text (domains => entries).

The old gravity parsed only domains.
The current gravity evolved and now it parses domains and ABP entries.

**Comment by DL6ER** [comment]
Thanks!

https://github.com/pi-hole/FTL/commit/a7f47a5e1fe19b81961c018d91c734d989365845 https://github.com/pi-hole/AdminLTE/commit/3e4a7699f87dabdd4dffd816fb9fa7360c4e15c5

**Comment by yubiuser** [comment]
Closing as fixed in v6 with https://github.com/pi-hole/FTL/commit/a7f47a5e1fe19b81961c018d91c734d989365845
