### ISSUE TITLE
dynamic-host via tailscale resolving/returning interface IP not configured IP in conf.

### ISSUE THREAD

**Issue by rudaki** [pi-hole/FTL#1575]
### Versions

```
~ $ pihole -v
  Pi-hole version is v5.17.1 (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: v5.20.1)
  FTL version is v5.23 (Latest: v5.23)
```

### Platform
```
~ $ uname -a
Linux pi-hole 5.10.103+ 1529 Tue Mar 8 12:19:18 GMT 2022 armv6l GNU/Linux
```

```
~ $ raspinfo
Raspberry Pi Model B Rev 2
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
```

```
~ $ tailscale version
1.44.0
  tailscale commit: 5d008cd8350247adebabd966933e23fe334e9d74
  other commit: 6dac82fa03e9212fb13ce7252dac41745629356a
  go version: go1.20.5-ts40dc4d8
```

### Network Configuration
_Pi-Hole device configuration_
```
192.168.1.5 - local network IP
100.xx.xx.5 - Tailscale IP
```

_localserver.custom.lan device configuration_
```
192.168.1.100 - local network IP
100.xx.xx.110 - Tailscale IP
```

### Pi-Hole Configuration

```
/etc/dnsmasq.d/01-pihole.conf 
localise-queries (confirmed this entry was present)
```

```
~ $ cat /etc/dnsmasq.d/03-dynamic-hosts.conf
interface=tailscale0
dynamic-host=localserver.custom.lan,192.168.1.100,eth0
dynamic-host=localserver.custom.lan,100.xx.xx.110,tailscale0
```

#### via tailscale0 interface (either locally on Pi-Hole or via other machines on network)
```
$ dig +short @100.xx.xx.5 localserver.custom.lan
100.xx.xx.110                (the IP specified in the .conf above)
``` 

#### via eth0 interface (either locally on Pi-Hole or via other machines on network)
```
$ dig +short @192.168.1.5 localserver.custom.lan
192.168.1.100
```

#### via tailscale0 interface (either locally on Pi-Hole or via other machines on network)
```
$ dig +short @100.xx.xx.5 localserver.custom.lan
100.xx.xx.5               (the IP of the tailscale0 interface on the Pi-Hole)
```

#### via eth0 interface (either locally on Pi-Hole or via other machines on network)
```
$ dig +short @192.168.1.5 localserver.custom.lan
192.168.1.100           (Correct)
```

### Steps to reproduce

Configure as above.

## Debug Token

- URL:  not provided.

### Screenshots

Not provided. See above .conf and terminal extracts.

### Additional context

I've tried pulling the latest development branch via `pihole checkout ftl dev` with the same results, and thus reverted back to `pihole checkout ftl master`

I'm sure I've had this working previously, but I haven't been able to downgrade the version (if possible) to test.

For reference, this appears to be a similar issue to that described in the following:
Dynamic-Host on dnsmasq is broken #1531

As described in the link above, the expected behaviour is that if there are multiple entries list for particular domain, that a different IP is returned dependant on the receiving interface. In my submitted case, the IP returned to satisfy the domain lookup is the local interface IP (incorrect) and not the IP listed in the dynamic-host config entry.

**Comment by DL6ER** [comment]
This is an issue that should best be brought up at the `dnsmasq-discuss` mailing list as that's where the experts on this topic are. How does the subnet of your tailscale interface look like? If it is a `/32` interface (I seem to remember something like this from the discussion we've had previously), then replying with the "local" interface address could be seen as the actual expected behavior as it is the only valid address on this interface. I don't think `dynamic-host` is able to give you what you want in this case (`dnsmasq` doesn't know that the address belongs to this interface as it is on a different subnet, `dnsmasq` does not inspect routes to my knowledge).
