### ISSUE TITLE
Serverside Pagination not sending correct data for paging

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/FTL#1597]
I have some experience in this so might be able to dig into the code myself, I just need to refresh my memory.

Short version, the datatable on the admin page is not showing the correct information. For example, the screenshot should be showing `Showing 1 to 10 of 8488 entries`, filter should not come into it, and the number of pages should be calculated correctly

![Image](https://github.com/pi-hole/FTL/assets/1998970/a5447522-0add-440d-abd7-108be913f01a)

Here is a working one from another project I've worked on

![Image](https://github.com/pi-hole/FTL/assets/1998970/a9ffc2c9-b71f-4910-9c1f-bdee437fc194)

Opening here because I'm pretty sure the information is supposed to be in the response packet from the server. I'll look into it if you don't get to it before me... 😉

**Comment by PromoFaux** [comment]
Gif from v5 web interface that probably better shows how the "filtered from" part should work

![pagination](https://github.com/pi-hole/FTL/assets/1998970/11ba6a26-780c-4ad5-9d83-104d81118430)

**Comment by rdwebdesign** [comment]
I think this table (or the idea of server side pagination) will need a complete redesign.

`v5` version loads all records on the browser and the datatables plugin filters the results on the page.

The new `v6` pagination will filter on the server, before the results gets to the browser.

**Comment by PromoFaux** [comment]
Have had a little internal discussion and some personal playing about with this. Need to sleep and think about it better when I'm not sleepy
