### ISSUE TITLE
FTL Failing to Update

### ISSUE THREAD

**Issue by LazerDickMcCheese** [pi-hole/FTL#1619]
### Versions

  Pi-hole version is v5.15.3 (Latest: N/A)
  AdminLTE version is v5.18.3 (Latest: N/A)
  FTL version is v5.20.1 (Latest: N/A)

### Platform

- OS and version:  DietPi v8.20

- Platform:   RPi  3 Model B (aarch64)

### Expected behavior

pihole -up
Update Pi-hole

### Actual behavior / bug

pihole -up fails and I get this reassuring error:
Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-aarch64-linux-gnu not found

### Steps to reproduce

Type 'pihole -up'...?

## Debug Token

I cannot provide one, please see the awesome error I was given:
curl: (7) Failed to connect to tricorder.pi-hole.net port 443: No route to host

### Additional context

I apologize in advance, but in case it isn't obvious: I'm not a Linux person...this kind of problem is exactly why. Any help is appreciated, I just want this thing (that I set up years ago) to update as intended. I'm not even sure if this is the correct place to type this out, but posting to Github is the only recommendation I've been given.

**Comment by rdwebdesign** [comment]
> Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-aarch64-linux-gnu not found

I think this was a temporary issue (network issue or maybe a server side issue).

Can you please try again?

**Comment by LazerDickMcCheese** [comment]
Hey, thank you for the response. I just tried again and got the same error: "Unable to complete update, please contact Pi-hole Support." I fully assume this is an error on my side, I could have easily set something up to unknowingly fail...but I have no idea.

**Comment by rdwebdesign** [comment]
> ## Debug Token
> 
> I cannot provide one, ...

Why? Are you seeing an error message? _(maybe this is related)_

**Comment by LazerDickMcCheese** [comment]
> Why? Are you seeing an error message? _(maybe this is related)_

Exactly, this is the error i get:

"curl: (7) Failed to connect to tricorder.pi-hole.net port 443: No route to host"

**Comment by LazerDickMcCheese** [comment]
I attempted another update, the issue persists.

**Comment by rdwebdesign** [comment]
Are you able to connect to the repo using this link on your browser?
https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-aarch64-linux-gnu

If you are, the problem is on your Raspberry Pi.

**Comment by LazerDickMcCheese** [comment]
Yes, I can connect to it in my browser. Is it possible to force an update via the SD card?

**Comment by rdwebdesign** [comment]
> Is it possible to force an update via the SD card?

No.

If you can connect via browser, we need find out why your Raspberry Pi is not able to connect.

On your RP, what is the output of `sudo cat /etc/resolv.conf`?

**Comment by LazerDickMcCheese** [comment]
# Generated by dhcpcd from eth0.dhcp6, eth0.ra
# /etc/resolv.conf.head can replace this line
search attlocal.net
nameserver 2600:1700:c560:5c50::1
# /etc/resolv.conf.tail can replace this line

**Comment by rdwebdesign** [comment]
Another question:

Do you have any firewall rules in place, that could block the `curl` command?

**Comment by LazerDickMcCheese** [comment]
I don't even know how to check...It used to update just fine, and I haven't changed any rules like that. Any idea how to check on Windows?

**Comment by LazerDickMcCheese** [comment]
Please see the referenced issue above, this has been solved.
