### ISSUE TITLE
Regression: input multiple domains in domain input field adds them as a single domain

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/FTL#1621]
Expected behavior is like it was in v5: domains separated by space should be added as individual entries.

**Comment by DL6ER** [comment]
https://github.com/pi-hole/FTL/pull/1629 adds handling in FTL. I'm currently developing away from my test environment and am not keen to break it from remote so this PR is - so far - entirely untested (you are welcomed to do this :-) ).

This will need a subsequent web change. Sending a space-separated domain seems a dirty hack. The PR above makes FTL accept *either* a string *or* an array of strings for domains, clients, group names and lists. The web interface will need to split the input itself and send a proper array to the API in this case.

**Comment by rdwebdesign** [comment]
> Sending a space-separated domain seems a dirty hack. 

I never said we should do that. I just said this is how it is done in v5.

---

OK, now the web interface will accept a domain or a list of domains separated by spaces (maybe we could also accept line breaks). The javascript code will need to split the "domain" field and send the result as an array.
