### ISSUE TITLE
pihole-FTL will not return SOA records if NXDOMAIN is cached for A records

### ISSUE THREAD

**Issue by schuettecarsten** [pi-hole/FTL#1638]
Try to guery message-waiting-indication02.service.sipgate.net from pi-hole. On the first try, it will return a SOA record in the authority section and a NXDOMAIN for the A record:

```
pi@raspberrypi:~ $ dig message-waiting-indication02.service.sipgate.net
[...]

;; QUESTION SECTION:
;message-waiting-indication02.service.sipgate.net. IN A

;; AUTHORITY SECTION:
sipgate.net.            10610   IN      SOA     ns1.netzquadrat.de. dnsadmin.netzquadrat.de. 2023083100 10800 3600 604800 86400

;; Query time: 15 msec
```

On the second and all subsequent tries, it will return NXDOMAIN. This seems to happen because pi-hole caches the NXDOMAIN for the A record and does not handle any SOA any more:

```
pi@raspberrypi:~ $ dig message-waiting-indication02.service.sipgate.net
[...]

;; QUESTION SECTION:
;message-waiting-indication02.service.sipgate.net. IN A

;; Query time: 3 msec
```

When querying google.dns or quad9 directly, I always get a SOA response. I am not sure if this is really a bug, I just can see that I have connection issues with sipgate and siproxd when usin Pi-Hole without any blocking lists. The only difference that I can see is the SOA record.

**Comment by DL6ER** [comment]
SOA (start of authority) records contain administrative information about the zone. They are (mostly) always reported by recursive resolvers. Caching DNS servers (such as `pihole-FTL`) are not supposed to cache and thereafter distribute it from cache. The reasons why SOA records exist is that they needed for zone transfers. Caching resolvers will, however, never (or only in very rare circumstances) have a full copy of a zone available and, hence, are unsuitable for zone transfers to begin with. Accordingly, missing `SOA` information in cached replies is actually expected and not a bug.

**Comment by schuettecarsten** [comment]
Thank you for explanation.
