### ISSUE TITLE
Segmentation Fault after startup

### ISSUE THREAD

**Issue by mohamed-essam** [pi-hole/FTL#1723]
### Versions

  Pi-hole version is v5.17.2 (Latest: v5.17.2)
  web version is v5.20.2 (Latest: v5.20.2)
  FTL version is v5.23 (Latest: v5.23) 

### Platform

- OS and version:  Ubuntu 22.04.1
- Platform:  VM
- 2VCPUs, 2GB RAM

### Expected behavior

Normal startup and activity

### Actual behavior / bug

FTL Crashes with segmentation Fault after startup by a minute.

### Steps to reproduce

Not sure how to exactly reproduce this issue, but I suspect the cause is the large size of clients.

## Debug Token

- URL:  https://tricorder.pi-hole.net/3RPYHVuh/

### Screenshots

N/A

### Additional context

N/A

**Comment by yubiuser** [comment]
Could you please provide the part of `´/var/log/pihole/FTL.log` that shows the crash?

**Comment by curtHendzell** [comment]
@DL6ER Yup....firewall misconfiguration.  Not great on a hosted Linode.  Fixed it and no issues since.

**Comment by DL6ER** [comment]
Sounds like the underlying issue will be fixed by https://github.com/pi-hole/FTL/pull/1777
