### ISSUE TITLE
pihole-ftl api (4711) all commands unknown

### ISSUE THREAD

**Issue by lduesing** [pi-hole/FTL#1741]
### Versions
Pi-hole version is v5.17.2 (Latest: v5.17.2)
web version is v5.20.2 (Latest: v5.20.2)
FTL version is v5.23 (Latest: v5.23)

### Platform
- OS and version:  
Debian 12
- Platform:  
amd64, proxmox container

### Expected behavior
answer api commands

### Actual behavior / bug

> telnet 0 4711
Trying 0.0.0.0...
Connected to 0.
Escape character is '^]'.
stats
unknown command: stats

---EOM---

top-domains
unknown command: top-domains

---EOM---

### Steps to reproduce

"telnet 0 4711" on pi-hole shell

## Debug Token

- URL:  
https://tricorder.pi-hole.net/mMtyrK1N/

**Comment by DL6ER** [comment]
Commands to the Telnet-API should a leading `>` on them, see https://docs.pi-hole.net/ftldns/telnet-api/

**Comment by lduesing** [comment]
ouch. sorry.
