### ISSUE TITLE
Selective teleporter restoration not possible.

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/FTL#1802]
Teleporter backups can only be restored entirely, but sometimes only some data needs to be restored. This is possible with v5, but not v6

**Comment by DL6ER** [comment]
As some fundamental data structures need to be modified, this can only be done after https://github.com/pi-hole/FTL/pull/1766 had been reviewed + merged. It will have to be done for both and, otherwise, a ton of merge conflicts would be unavoidable.

**Comment by DL6ER** [comment]
It is available now as per https://github.com/pi-hole/FTL/pull/1874. Web PR outstanding, though.

**Comment by DL6ER** [comment]
Implemented
