### ISSUE TITLE
FTL Update does not match

### ISSUE THREAD

**Issue by guldhammer72** [pi-hole/FTL#1825]
### Versions

- Pi-hole:  Version is v5.17.1-253-g719ce801 (Latest: v5.17.2)
    Branch is development-v6
    Hash is 719ce801 (Latest: 719ce801)

- AdminLTE:   Version is v5.19-595-g2889bb5a (Latest: v5.21)
    Branch is development-v6
    Hash is 2889bb5a (Latest: 2889bb5a)

- FTL:  Version is vDev-17a2038 (Latest: v5.23)
    Branch is development-v6
    Hash is 17a2038b (Latest: 8eef4d81)

### Platform

- OS and version:  

- Platform:  NUC, Debian 12.

### Expected behavior

Pihole tells me there is a update to FTL, og the homepage, but everything is up to date.
My latest FTL is: 
Version is vDev-17a2038 (Latest: v5.23)
but the latest FTL is
FTL vDev (development-v6, 17a2038b.

### Actual behavior / bug

_A clear and concise description of what the bug is._

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
Please try `pihole -up` again.

**Comment by guldhammer72** [comment]
Thanks, now it worked.
How do i close this thread?
