### ISSUE TITLE
Pi-hole 6 API: POST /list documentation issue

### ISSUE THREAD

**Issue by akordowski** [pi-hole/FTL#1834]
The documentation for the `POST /list` [action](https://192.168.178.21/api/docs/#post-/lists) describes when passing multiple lists that the parameter `list` should be used. But actually the name of the parameter is also `address` but of type `array`.

![grafik](https://github.com/pi-hole/pi-hole/assets/9746197/1f499736-cad5-4aef-8299-f7d38cb12406)

I also think the currly braces are misleading as they indicating a new object. But the `address` parameter is on the same level as the other parameters.

**Comment by DL6ER** [comment]
The `lists` should really be renamed to `address`: #1835 

However, the curly braces is not an error but how OpenAPI encloses the `ONE OF` choice and nothing we can do about. It seems to be left to the reader that in `"key": { [ONE OF] [1] "value", [2] "other-value" }` the curly braces are meant for the `[ONE OF]` and **not** meant to be used in the final payload

**Comment by akordowski** [comment]
Thank you for the clarification and fixing the issue!
