### ISSUE TITLE
Pihole-FTL v6 crash when ipv6 disabled and ipv6 dns given.

### ISSUE THREAD

**Issue by edgd1er** [pi-hole/FTL#1935]
### Versions

- Pi-hole:  latest v6 version
- AdminLTE:  
- FTL:  

### Platform

- OS and version:  Debian 12 + container (alpine 3.19)

- Platform:  raspberry pi4

### Expected behavior

as until latest build, even when an ipv6 dns was set in env and ipv6 disabled, pihole-FTL did not crash.

### Actual behavior / bug

Since 18/04, pihole FTL crash at boot time. 

pihole-1  | 2024-04-20 05:01:09.836 [152M] WARNING: Connection error (fd0f:ee:b0::1#53): failed to send UDP request (Network unreachable)
pihole-1  | 2024-04-20 05:01:09.837 [152M] INFO: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
pihole-1  | 2024-04-20 05:01:09.837 [152M] INFO: ---------------------------->  FTL crashed!  <----------------------------
pihole-1  | 2024-04-20 05:01:09.838 [152M] INFO: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
pihole-1  | 2024-04-20 05:01:09.838 [152M] INFO: Please report a bug at https://github.com/pi-hole/FTL/issues
pihole-1  | 2024-04-20 05:01:09.838 [152M] INFO: and include in your report already the following details:
pihole-1  | 2024-04-20 05:01:09.838 [152M] INFO: FTL has been running for 12 seconds
pihole-1  | 2024-04-20 05:01:09.838 [152M] INFO: FTL branch: development-v6
pihole-1  | 2024-04-20 05:01:09.838 [152M] INFO: FTL version: vDev-4734e01
pihole-1  | 2024-04-20 05:01:09.838 [152M] INFO: FTL commit: 4734e01b
pihole-1  | 2024-04-20 05:01:09.838 [152M] INFO: FTL date: 2024-04-18 21:28:52 +0200
pihole-1  | 2024-04-20 05:01:09.839 [152M] INFO: FTL user: started as pihole, ended as pihole
pihole-1  | 2024-04-20 05:01:09.839 [152M] INFO: Compiled for linux/arm64/v8 (compiled on CI) using cc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924
pihole-1  | 2024-04-20 05:01:09.839 [152M] INFO: Process details: MID: 152
pihole-1  | 2024-04-20 05:01:09.839 [152M] INFO:                  PID: 152
pihole-1  | 2024-04-20 05:01:09.839 [152M] INFO:                  TID: 152
pihole-1  | 2024-04-20 05:01:09.839 [152M] INFO:                  Name: pihole-FTL
pihole-1  | 2024-04-20 05:01:09.839 [152M] INFO: Received signal: Segmentation fault
pihole-1  | 2024-04-20 05:01:09.839 [152M] INFO:      at address: 0x2
pihole-1  | 2024-04-20 05:01:09.839 [152M] INFO:      with code:  SEGV_MAPERR (Address not mapped to object)
pihole-1  | 2024-04-20 05:01:09.839 [152M] INFO: !!! INFO: pihole-FTL has not been compiled with glibc/backtrace support, not generating one !!!
pihole-1  | 2024-04-20 05:01:09.840 [152M] INFO: ------ Listing content of directory /dev/shm ------
pihole-1  | 2024-04-20 05:01:09.840 [152M] INFO: File Mode User:Group      Size  Filename
pihole-1  | 2024-04-20 05:01:09.840 [152M] INFO: rwxrwxrwx root:root       280   .
pihole-1  | 2024-04-20 05:01:09.840 [152M] INFO: rwxr-xr-x root:root       320   ..
pihole-1  | 2024-04-20 05:01:09.840 [152M] INFO: rw------- pihole:pihole   560K  FTL-fifo-log
pihole-1  | 2024-04-20 05:01:09.841 [152M] INFO: rw------- pihole:pihole     4K  FTL-per-client-regex
pihole-1  | 2024-04-20 05:01:09.841 [152M] INFO: rw------- pihole:pihole    98K  FTL-dns-cache
pihole-1  | 2024-04-20 05:01:09.841 [152M] INFO: rw------- pihole:pihole     8K  FTL-overTime
pihole-1  | 2024-04-20 05:01:09.841 [152M] INFO: rw------- pihole:pihole    14M  FTL-queries
pihole-1  | 2024-04-20 05:01:09.841 [152M] INFO: rw------- pihole:pihole    29K  FTL-upstreams
pihole-1  | 2024-04-20 05:01:09.842 [152M] INFO: rw------- pihole:pihole    86K  FTL-clients
pihole-1  | 2024-04-20 05:01:09.842 [152M] INFO: rw------- pihole:pihole    66K  FTL-domains
pihole-1  | 2024-04-20 05:01:09.842 [152M] INFO: rw------- pihole:pihole   123K  FTL-strings
pihole-1  | 2024-04-20 05:01:09.843 [152M] INFO: rw------- pihole:pihole    16   FTL-settings
pihole-1  | 2024-04-20 05:01:09.843 [152M] INFO: rw------- pihole:pihole   292   FTL-counters
pihole-1  | 2024-04-20 05:01:09.843 [152M] INFO: rw------- pihole:pihole    88   FTL-lock
pihole-1  | 2024-04-20 05:01:09.843 [152M] INFO: ---------------------------------------------------
pihole-1  | 2024-04-20 05:01:09.843 [152M] INFO: Please also include some lines from above the !!!!!!!!! header.
pihole-1  | 2024-04-20 05:01:09.844 [152M] INFO: Thank you for helping us to improve our FTL engine!
pihole-1  | 2024-04-20 05:01:09.844 [152M] INFO: Waiting for threads to join
pihole-1  | 2024-04-20 05:01:09.844 [152M] INFO: Thread database (0) is idle, terminating it.
pihole-1  | 2024-04-20 05:01:09.844 [152M] INFO: Thread housekeeper (1) is idle, terminating it.
pihole-1  | 2024-04-20 05:01:09.845 [152M] INFO: Thread DNS client (2) is idle, terminating it.
pihole-1  | 2024-04-20 05:01:09.845 [152M] INFO: All threads joined
pihole-1  | 2024-04-20 05:01:09.846 [152M] INFO: Stored 0 API sessions in the database
pihole-1  | 2024-04-20 05:01:11.916 [152M] INFO: ########## FTL terminated after 14s  (code 1)! ##########

### Steps to reproduce

1. add an ipv6 dns: - FTLCONF_dns_upstreams=80.67.169.40;80.67.169.12;fd0f:ee:b0::1
2. disable ipv6 :  FTLCONF_resolver_resolveIPv6=no
3. start the container. 

## Debug Token

- URL:  

### Screenshots

no screenshots as pihole-FTL did not start.

### Additional context

if fd0f:ee:b0::1 is removed from FTLCONF_dns_upstreams, pihole-FTL is starting as usual.

**Comment by DL6ER** [comment]
Thank you, this was an incompatibility created by an issue between https://github.com/pi-hole/FTL/pull/1930 and https://github.com/pi-hole/FTL/pull/1928. While each PR worked perfectly fine on its own, a change made in the latter caused a conflict with new code added in the former. As this was new code, `git` had no way to detect the conflict automatically.

Bugfix here: https://github.com/pi-hole/FTL/pull/1936

**Comment by DL6ER** [comment]
The fix has been merged. Anyone still experiencing this, please update to the latest version of the `development-v6` branch. No other branch should be affected.
