### ISSUE TITLE
Obsolete MAC Vendor DB Script

### ISSUE THREAD

**Issue by subfission** [pi-hole/FTL#1982]
Hello, I stumbled into this bug when looking through your codebase.

### Obsolete Script

The script at [FTL/tools/macvendor.py](https://github.com/pi-hole/FTL/blob/master/tools/macvendor.py) references the former wireshark [manuf](https://gitlab.com/wireshark/wireshark/-/raw/master/manuf) database of MAC vendors and has been  obsolete for some time.

I found this commit on Wireshark which notes this change:

* https://gitlab.com/wireshark/wireshark/-/commit/0b5791b08d0e8a4aa49719dcaf98c96f31a6aa48

### Possible Solution

The suggestion is to leverage the IEEE database.  Wireshark has this script you might be able to leverage: 

* https://gitlab.com/wireshark/wireshark/-/blob/master/tools/make-manuf.py

**Comment by DL6ER** [comment]
We always used the already processed list offered by the Wireshark team and merely have to update the location where it is hosted so no need for big changes on our side. Thanks for the pointer, I didn't even notice this!

Fixed by https://github.com/pi-hole/FTL/pull/1983
