### ISSUE TITLE
OS Reboot during pihole temporary blocking issue

### ISSUE THREAD

**Issue by kuitog** [pi-hole/FTL#2020]
### Versions

- Pi-hole:  5.18.3
- AdminLTE:  5.21
- FTL:  5.25.2

### Platform

- OS and version:  Ubuntu 22.04

- Platform:  Ubuntu install

### Expected behavior

I enable a temporary pause of blocking of 10  minutes.
I do a terminal sudo reboot.
When rebooting pihole should check if 10 minutes have passed and resume blocking.

### Actual behavior / bug

When rebooting pihole loses the countdown and restarts with filtering permanently disabled. You have to manually go to the dashboard and reenable blocking.

### Steps to reproduce

1.Set a 1 minute temporary filtering pause on the pihole dashboard
2. Ssh sudo reboot linux
3. Go to the pihole dashboard. The countdown is gone and blocking is disabled for good.

I suggest that when starting the countdown, the countdown end time should be written to the db, so that even if rebooting the countdown can be resumed.

**Comment by yubiuser** [comment]
With v6 the behavior is: A disabled time will survive the reboot, but the timer is "forgotten" and blocking is disabled indefinitely.

**Comment by kuitog** [comment]
Ok, maybe not the best design.. Today I rebooted during a 10 minute pause and I was 3 hours without filtering. It could have been 3 days until I realized.

Doesn't make much sense to "forget" and disable something completely just because the system was rebooted.
For me pihole is very similar to a firewall, and you wouldn't want your firewall to do this..
