### ISSUE TITLE
v6 changes to webserver.api.cli_pw should trigger a FTL restart

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/FTL#2040]
When this feature was enabled and changed to disabled, `/etc/pihole/cli_pw` is not deleted (misleading output generated by https://github.com/pi-hole/pi-hole/pull/5736). 
When the feature was disabled, file was manually deleted and feature is now enabled, the file is not created until FTL is restarted. 

In both cases, I think a automatic FTL restart would solve this issues.

**Comment by DL6ER** [comment]
Fixed by #2041
