### ISSUE TITLE
pihole appears to rate limit the wrong client

### ISSUE THREAD

**Issue by bp0** [pi-hole/FTL#2069]
### Versions

  Pi-hole version is v5.18.3 (Latest: v5.18.3)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.25.2 (Latest: v5.25.2)

### Platform

- OS and version:  Debian 12.6 LXC

- Platform: Proxmox 8.2.5

### Actual behavior / bug

After turning on a Samsung TV (192.168.2.108), it made ~29000 A/AAAA queries for logs.netflix.com. 
Pihole responded by rate limiting a different machine, 192.168.2.20, that had only made 67 queries.
I don't know which was actually rate limited, maybe the log message is just incorrect?

### Steps to reproduce

I'm not sure I can reproduce this exact situation.

## Debug Token

- URL:  https://tricorder.pi-hole.net/aSbvSyjP/

### Screenshots

![image](https://github.com/user-attachments/assets/420336d9-5058-4e74-9f53-1b6ebbf5d25c)
![image](https://github.com/user-attachments/assets/041a8492-b3de-4218-8172-245ab2ef672b)

**Comment by bp0** [comment]
> Do you know what client `192.168.2.20 ` is?

Yes, it is a regular desktop PC running Pop OS.

**Comment by DL6ER** [comment]
> What I don't understand is why it was blocked, but the database did not contain any entries in that time frame.

It may be a timezone issue. The browser may know that it is, e.g., some US time with +6 hours while the server may be using UTC. In this scenario the screenshot and the `sqlite3` query would work in entirely different timeslots.

@bp0 Did this ever happen again?
