### ISSUE TITLE
query log unresponsive 

### ISSUE THREAD

**Issue by technicalpyro** [pi-hole/FTL#207]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_{3}_

---

**[BUG | ISSUE] Expected Behaviour:**
ability to view all queries in the query log when selected

**[BUG | ISSUE] Actual Behaviour:**
when clicking the all queries (instead of queries for the last 10 minutes) the web interface freezes

**[BUG | ISSUE] Steps to reproduce:**

-go to query log
-filter if you wish
-select the link at the top to view all rather than just the last 10 minutes
-

**Log file output [if available]**

` kqwkw2i045`

**Device specifics**

Hardware Type: rPi2B
OS: Raspbian stretch

i believe this to be an FTL error as it would seem to me to be the page hangs while trying to load the data my other thought is it is an admin interface issue but unsure f which 

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Issue moved to [pi-hole/AdminLTE #672](https://github.com/pi-hole/AdminLTE/issues/672) via [**ZenHub**](https://www.zenhub.com/)
