### ISSUE TITLE
Empty value for dns.domain not accept from GUI

### ISSUE THREAD

**Issue by schuettecarsten** [pi-hole/FTL#2111]
`dns.domain` setting description i GUI says that I can disable the feature by setting the value to an empty string.
But empty value is not accept:

![Image](https://github.com/user-attachments/assets/e1ae4018-4e67-45d8-adc1-fb72e83a91ee)

Docker Tag nightly
Core vDev (development, 112b9617)
FTL vDev (development, 54b4ad93)
Web interface vDev (development, c689fdc7)

**Comment by DL6ER** [comment]
This is a validation bug and should be fixed as of [848367f](https://github.com/pi-hole/FTL/commit/848367fab38740b7785bd536c2dfe8e2f90546b4)

**Comment by schuettecarsten** [comment]
Thank you, that works now. There is another validation issue with setting `dns.revServers`. Description says that format is `<enabled>,<ip-address>[/<prefix-len>],<server>[#<port>][,<domain>]`, expecting `domain to be optional:

![Image](https://github.com/user-attachments/assets/84470dbd-3d6a-409e-8339-dff6c3f34888)

However, values without the domain parameter are not accepted:

![Image](https://github.com/user-attachments/assets/f698778c-7960-457e-a580-b4ca2ab61932)

**Comment by DL6ER** [comment]
Original issue is resolved, created a new issue ticket for the ... well ... new issue.
