### ISSUE TITLE
List all clients from UI

### ISSUE THREAD

**Issue by borpin** [pi-hole/FTL#220]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1_

---

**[ISSUE] Expected Behaviour:**
It would be useful to be able to list all clients that are requesting DNS lookup through Pi-hole not just Top 10.  It would show if a particular client was configured to use Pi-hole correctly as well as looking for rouge clients.

My C is not great but looking at the code I believe https://github.com/pi-hole/FTL/blob/master/request.c#L457 is where this lookup is handled.

If the function was made more general to include the 'count' as a parameter, it looks as if the function could be made more general (even offer a UI to display more items) or simply use 0 to display all clients in the logs.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Issue moved to [pi-hole/AdminLTE #679](https://github.com/pi-hole/AdminLTE/issues/679) via [**ZenHub**](https://www.zenhub.com/)
