### ISSUE TITLE
FTL Does not start

### ISSUE THREAD

**Issue by C4Wiz** [pi-hole/FTL#232]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**
5

---

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**
pihole-FTL: no process found

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**Log file output [if available]**

`output`

**Device specifics**

Hardware Type: rPi, VPS, etc
OS:

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by C4Wiz** [comment]
Fixed by running the following:

sudo rm /usr/bin/pihole-FTL
pihole -r

**Comment by dschaper** [comment]
Thanks for the workaround, we might add that to the announcement post if we find this to be common.

**Comment by C4Wiz** [comment]
no problem, glad to help out

**Comment by p1r473** [comment]
That trick worked for me too, thanks

sudo rm /usr/bin/pihole-FTL
pihole -r
