### ISSUE TITLE
Error on binding on Unix socket /var/run/pihole/FTL.sock: No such file or directory 

### ISSUE THREAD

**Issue by smitdol** [pi-hole/FTL#233]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1_

---

**[BUG | ISSUE] Expected Behaviour:**
FTL online

**[BUG | ISSUE] Actual Behaviour:**
after restart FTL goes offline after a few seconds

**[BUG | ISSUE] Steps to reproduce:**
pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] FTL:              up to date
  [i] Web Interface:    up to date

followed debug instructions from https://github.com/pi-hole/FTL#debugging-pihole-ftl showed Error on binding on Unix socket /var/run/pihole/FTL.sock: No such file or directory (2)

**Log file output [if available]**

```
[2018-02-16 07:31:28.792] New domain: avatars0.githubusercontent.com (126/1000)
[2018-02-16 07:31:28.809] New domain: camo.githubusercontent.com (127/1000)
[2018-02-16 07:31:30.023] Finished initial log file parsing
[2018-02-16 07:31:30.025]  -> Total DNS queries: 45350
[2018-02-16 07:31:30.028]  -> Cached DNS queries: 17283
[2018-02-16 07:31:30.030]  -> Forwarded DNS queries: 28036
[2018-02-16 07:31:30.031]  -> Exactly blocked DNS queries: 30
[2018-02-16 07:31:30.034]  -> Wildcard blocked DNS queries: 0
[2018-02-16 07:31:30.036]  -> Unknown DNS queries: 1
[2018-02-16 07:31:30.044]  -> Unique domains: 128
[2018-02-16 07:31:30.046]  -> Unique clients: 8
[2018-02-16 07:31:30.048]  -> Known forward destinations: 2
[2018-02-16 07:31:30.050] Successfully accessed setupVars.conf
[New Thread 0xb6aa2470 (LWP 3476)]
[2018-02-16 07:31:30.058] Listening on port 4711 for incoming IPv4 telnet connections
[2018-02-16 07:31:30.061] Found 5 IPv4 and 1 IPv6 capable interfaces
[2018-02-16 07:31:30.067] Listening on port 4711 for incoming IPv6 telnet connections
[2018-02-16 07:31:30.070] Error on binding on Unix socket /var/run/pihole/FTL.sock: No such file or directory (2)
[Thread 0xb6aa2470 (LWP 3476) exited]
[Inferior 1 (process 3468) exited with code 01]
```

**Device specifics**

Hardware Type: rPi, VPS, etc
lscpu
Architecture:          armv6l
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
Model:                 7
Model name:            ARMv6-compatible processor rev 7 (v6l)
CPU max MHz:           850.0000
CPU min MHz:           700.0000
BogoMIPS:              697.95
Flags:                 half thumb fastmult vfp edsp java tls
OS:
cat /etc/*-release
PRETTY_NAME="Open Source Media Center"
NAME="OSMC"
VERSION="January 2018"
VERSION_ID="2018.01-1"
ID=osmc
ID_LIKE=debian

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Does the directory `/var/run/pihole/` exist and is owned by user `pihole`?

**Comment by Mcat12** [comment]
Does running this command change anything?
```
sudo service pihole-FTL restart
```

**Comment by 0xERR0R** [comment]
Ich have the same issue after update yesterday. FTL does not start. I tried pihole -r and reboot.
Directory /var/run/pihole/ does not exist. `sudo service pihole-FTL restart`prints nothing. In web ui ist still "FTL offline". After service restart i can see in "/var/log/pihole-FTL-log: Error on binding on Unix socket /var/run/pihole/FTL.sock: No such file or directory (2)

**Comment by DL6ER** [comment]
@0xERR0R See my question above. How is it for you?

**Comment by 0xERR0R** [comment]
@DL6ER As I wrote, the directory /var/run/pihole/ does not exist.

**Comment by DL6ER** [comment]
Oh, I missed that.
- Does the directory `/var/run/` exist?
- Does `sudo service pihole-FTL restart` create the directory `/var/run/pihole/` ?
- Is there anything special concerning your `/var/run` ?
 What is the output of `mount | grep '/var'` ?

**Comment by smitdol** [comment]
`ls /var/run`

`avahi-daemon        dnsmasq        motd.dynamic     rpcbind.lock     systemd
connman-vpn         fb_resolution  mount            rpcbind.sock     tmpfiles.d
crond.pid           initctl        ntpd.pid         samba            udev
crond.reboot        initramfs      openvpn          screen           user
dbus                lighttpd       pihole-FTL.pid   sendsigs.omit.d  utmp
dhcpcd              lighttpd.pid   pihole-FTL.port  shm
dhcpcd.pid          lirc           plymouth         sshd
dhcpcd.sock         lock           rpc_pipefs       sshd.pid
dhcpcd.unpriv.sock  log            rpcbind          sysconfig
`

` sudo service pihole-FTL restart
`

`ps -ef | grep pihole
`

`pihole   19524     1  3 11:19 ?        00:00:00 /lib/systemd/systemd --user`
`pihole   19525 19524  0 11:19 ?        00:00:00 (sd-pam)`
`pihole   19530     1 66 11:19 ?        00:00:05 /usr/bin/pihole-FTL`
`osmc     19534 19405  0 11:19 pts/1    00:00:00 grep pihole`

although that is for the few seconds

`ls /var/run/pihole
`

`ls: cannot access '/var/run/pihole': No such file or directory
`

`sudo ls /var/run/pihole
`

`ls: cannot access '/var/run/pihole': No such file or directory
`

`mount | grep '/var'`

does not return anything, neither does 

`sudo mount | grep '/var'
`

`ls -al /var/run`
`lrwxrwxrwx 1 root root 4 Jan  1  1970 /var/run -> /run`

**Comment by DL6ER** [comment]
Ah, that is interesting. How about
```
mount | grep '/run'
```

**Comment by smitdol** [comment]
` mount | grep '/run'`

`tmpfs on /run type tmpfs (rw,relatime)`
`tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)`
`sunrpc on /run/rpc_pipefs type rpc_pipefs (rw,relatime)`
`tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=36116k,mode=700,uid=1000,gid=1000)`
`tmpfs on /run/user/999 type tmpfs (rw,nosuid,nodev,relatime,size=36116k,mode=700,uid=999,gid=999)`

**Comment by DL6ER** [comment]
So that is different to what I'm seeing on Raspbian Stretch:
```
$ mount | grep '/run'
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
```

Can you create the folders manually or is there an error when you try that?
```
sudo touch /var/log/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port
sudo chown pihole:pihole /var/log/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port /etc/pihole
sudo chmod 0644 /var/log/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port
```

**Comment by smitdol** [comment]
maybe this solves the issue:
` sudo mkdir /var/run/pihole`
`sudo chown pihole:pihole /var/run/pihole`
`sudo service pihole-FTL restart`

looks like it is running for more that the couple of seconds
`ls /var/run/pihole` now returns
`FTL.sock`

**Comment by DL6ER** [comment]
What is the content of your `/etc/init.d/pihole-FTL` file?
It should be identical to https://github.com/pi-hole/pi-hole/blob/master/advanced/pihole-FTL.service

**Comment by smitdol** [comment]
not identical ...
start service is different
lines 29, 30 and 32 are missing:
29 `mkdir -p /var/run/pihole`
30 `mkdir -p /var/log/pihole`
32 `rm /var/run/pihole/FTL.sock`

**Comment by smitdol** [comment]
`ls -al /etc/init.d/pihole-FTL`
`-rwxr-xr-x 1 root root 1650 Feb 16 07:08 /etc/init.d/pihole-FTL`
`sudo pihole -up`
`  [i] Checking for updates...`
`  [i] Pi-hole Core:     up to date`
`  [i] FTL:              up to date`
`  [i] Web Interface:    up to date`
``
`  [▒] Everything is up to date!`

**Comment by DL6ER** [comment]
Well, this explains it then. Try running `pihole -r` to have this file fixed for you. Please give us feedback if it worked.

**Comment by smitdol** [comment]
`sudo pihole -r`
repair option selected 
`...`
` [i] FTL Checks...`
`  [▒] Detected ARM-hf architecture (armv6 or lower) Using ARM binary`
`  [i] Checking for existing FTL binary...`
`  [i] Latest FTL Binary already installed (v3.0). Confirming Checksum...`
`  [i] Checksum correct. No need to download!`
`  [i] Restarting services...`
`...`
as this excerpt shows, the FTL binary is not updated, and the /etc/init.d/pihole-FTL is left unchanged 
`ls -al /etc/init.d/pihole-FTL`
`-rwxr-xr-x 1 root root 1650 Feb 16 07:08 /etc/init.d/pihole-FTL`

**Comment by DL6ER** [comment]
Okay, I see that `pihole -r` does fix the file only when it reinstalls `FTL`.

So you could try
```
sudo rm /usr/bin/pihole-FTL
sudo pihole -r
```

**Comment by 0xERR0R** [comment]
This solution worked for me. Thanks.

**Comment by smitdol** [comment]
this solution indeed downloads and installs FTL library and also `/etc/init.d/pihole-FTL` now is up to date (contains the previously missing lines).
Although I think the upgrade may need some tweaking to avoid this issue to re-occur in the future, I'll close this issue.

**Comment by DL6ER** [comment]
We already have a fix for this.

https://github.com/pi-hole/pi-hole/pull/1981

**Comment by geekcroft** [comment]
I too had this issue and removing the service file and pihole -r fixed it immediately.

**Comment by 0x98364** [comment]
I have the same issue @Mastermjr . Did you fgound any solution? Thanks
