### ISSUE TITLE
FTL fails to install with SSL read error

### ISSUE THREAD

**Issue by BasculethiTellur** [pi-hole/FTL#236]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1_

---

**[BUG | ISSUE] Expected Behaviour:**
Installing Pi-Hole on an RPi3, should and previously did proceed with no errors. Fresh install of Raspbian Stretch.

**[BUG | ISSUE] Actual Behaviour:**
The Pi-Hole installation script generates the following error:
 [i] Checking for existing FTL binary...
 [i] Downloading and Installing FTL000curl: (56) SSL read: error:00000000:lib(0}:func(0):reason(0), errno 104
 [x] Downloading and installing FTL
 Error: URL not found

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**Log file output [if available]**

`output`

**Device specifics**

Hardware Type: rPi, VPS, etc
OS:

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by BasculethiTellur** [comment]
Ah, now fixed. A second run of the curl -sSL https://install.pi-hole.net | bash with the repair option seemed to fix it. Weirdly, pihole -r did not.¯\_(ツ)_/¯

**Comment by Mcat12** [comment]
Sounds like it might have been a temporary network error.
