### ISSUE TITLE
FTL API - listen on single interface/ip only

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [pi-hole/FTL#242]
At the moment, my Pihole-FTL listens on IPv6 wildcard, IPv4 wildcard and creates an unix socket.
Would be cool if there is a config option to actually control the listeners.

**Comment by DL6ER** [comment]
Closing in favour of #243

**Comment by Unkn0wn-MDCLXIV** [comment]
This issue is about the FTL daemon to get the stats, the other one is about the DNS listener.

**Comment by DL6ER** [comment]
By default, FTL's API does does only listen on `lo`. You have to have set a config option to allow listening to any origin. Please open a feature request on [Discourse](https://discourse.pi-hole.net/c/feature-requests) if you want to see this feature added to FTL.
