### ISSUE TITLE
FTLDNS Beta - Top Clients Showing Numeric Addresses Only (ipv4/ipv6)

### ISSUE THREAD

**Issue by iamperson347** [pi-hole/FTL#248]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

1

---

**[BUG | ISSUE] Expected Behaviour:**
In the Pihole Web Admin page, there is a "top clients" graph. In this graph, I would expected that client names would be resolved to hostnames/fqdn if there is an entry in DNS for that client (e.g. once DHCP assigns an IP, etc.). However, all displayed values are numeric (ipv4 or ipv6).

This may be by design? If so, this issue can be closed. 

**[BUG | ISSUE] Actual Behaviour:**
If this is not by design, I would expect that client names are resolved. It appears there may be some code that is called to resolve client names (getClientNames), but this is just a guess (not very familiar with the code).

I do have a slightly odd configuration that might not be supported. I have my router set up to announce the pihole ipv4/ipv6 address to clients. Under normal circumstances, this may cause local client names to not be resolved. However, I have the following line in a separate config file (under dnsmasq.d) to send queries with the ".lan" domain back to my router (since it handles dhcp/dns for the local network).

server=/lan/192.168.1.1

My local clients can resolve each other correctly with this setup.

**[BUG | ISSUE] Steps to reproduce:**

See above - please let me know if more info is needed.

**Log file output [if available]**

N/A? - If there is something I can run to help, please let me know.

**Device specifics**

Hardware Type: old 32bit netbook
OS: Ubuntu 17.10

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
> My local clients can resolve each other correctly with this setup.

have you checked out the FTLDNS branch for the web? The issue here is that you cannot use the resolver when you are yourself the resolver (that would lead to deadlocking yourself), so FTL cannot resolve the hostnames itself. However, PHP should do the resolving work each time you query a set of data and this seems to work fine for me...

Do you have host names in the "Top Clients" table?

**Comment by iamperson347** [comment]
I do have the FTLDNS branch for web. I didn't realize it was PHP itself
attempting to resolve names. Currently, my clients table contains all
numeric values (except for localhost).

**Comment by DL6ER** [comment]
Can you run `dig -x 192.168.1.2 +short` (replace the IP with one of your clients) and run this command on the Pi-hole server itself. Is it able to resolve the correct host name?

**Comment by iamperson347** [comment]
Sorry for the late response - It looks like reverse lookups aren't working correctly on my network. They work on the router (openwrt), but not on clients.

Thank you for taking the time to help with this.

**Comment by iamperson347** [comment]
For those that may be interested in the future:

For reverse lookups to be forwarded to another nameserver with dnsmasq, you must have something similar to the following in your dnsmasq config:

server=/168.192.in-addr.arpa/192.168.1.1
server=/d.f.ip6.arpa/192.168.1.1

(The first entry says forward any reverse lookup with address 192.168.x.x to nameserver 192.168.1.1. The second entry is similar, but for ipv6. You may have to adjust the first entry based on the type of networking your are on - class c, b, or a.)

**Comment by Mcat12** [comment]
Relevant web and core PR for conditional forwarding:
pi-hole/AdminLTE#653
pi-hole/pi-hole#1915
