### ISSUE TITLE
Setting "AAAA_QUERY_ANALYSIS=no" doesn't seem to have any effect

### ISSUE THREAD

**Issue by EngieDev** [pi-hole/FTL#250]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**
3
---

**[BUG | ISSUE] Expected Behaviour:**
```
AAAA_QUERY_ANALYSIS=no
resolve_ipv6=no
```
After adding these lines to the file and restarting FTL, I'd expect no ipv6 queries to show in the query log/stats.

**[BUG | ISSUE] Actual Behaviour:**
AAAA dns queries are still being shown and responded to according to the query log.
![chrome_2018-04-05_11-01-21](https://user-images.githubusercontent.com/26211184/38359901-2b07e37e-38c1-11e8-9097-2f8277ae6a5d.png)

**[BUG | ISSUE] Steps to reproduce:**
Add the following to `/etc/pihole/pihole-ftl.conf` and restart FTL.

```
AAAA_QUERY_ANALYSIS=no
RESOLVE_IPV6=no
```
Done the following without any effect:
- `pihole -r` and checked/unchecked ipv6 
- Deactivated DNSSEC (#244)

**Log file output [if available]**
Running `pihole -d` reveals that the settings are actually being loaded into FTL.
```
   [2018-04-05 00:35:40.805] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
   [2018-04-05 00:35:40.805]    SOCKET_LISTENING: only local
   [2018-04-05 00:35:40.806]    AAAA_QUERY_ANALYSIS: Hide AAAA queries
   [2018-04-05 00:35:40.806]    MAXDBDAYS: max age for stored queries is 365 days
   [2018-04-05 00:35:40.806]    RESOLVE_IPV6: Don't resolve IPv6 addresses
   [2018-04-05 00:35:40.807]    RESOLVE_IPV4: Resolve IPv4 addresses
   [2018-04-05 00:35:40.807]    DBINTERVAL: saving to DB file every minute
   [2018-04-05 00:35:40.807]    DBFILE: Using /etc/pihole/pihole-FTL.db
   [2018-04-05 00:35:40.808]    MAXLOGAGE: Importing up to 24.0 hours of log data
   [2018-04-05 00:35:40.808]    PRIVACYLEVEL: Set to 0

```

**Device specifics**

Hardware Type: Raspberry Pi, Model B Gen 1 (Arm6)
OS: Raspbian Stretch;

Have to manually build updates from git because of issue #244. Last done yesterday evening.
Was initially just trying to hide the ipv6 requests from stats/query log since I do not have a ipv6 router.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by technicalpyro** [comment]
you still see the AAAA queries because the devices are still trying to make them as far as the status or returns that could be down to the backwards compatability baked into IPv6

**Comment by EngieDev** [comment]
[This](https://discourse.pi-hole.net/t/why-do-blacklisted-domains-show-ipv4-as-pi-holed-but-not-ipv6-in-the-query-log/3652?source_topic_id=3581) says that adding `AAAA_QUERY_ANALYSIS=no` should hide the AAAA queries from the log, though of course they still occur in the background.

I would have expected `RESOLVE_IPV6=no` to deny all ipv6 queries though.

**Comment by DL6ER** [comment]
`pihole-ftl.conf` should be `pihole-FTL.conf`

**Comment by EngieDev** [comment]
Ah, made a mistake with the title there, the actual file on the raspi is `pihole-FTL.conf`, and it is loading the right settings according to the logs.

**Comment by DL6ER** [comment]
Yeah, I see this now. Looking at the code, everything seems fine. I'll try it myself in a bit.

**Comment by DL6ER** [comment]
Okay, there was a space where it shouldn't have been. I fixed this in 1d6a339969e1585246a47adf6a2d99a543561c12. I also disabled importing of AAAA queries from the databse (on startup) if this setting is set (003371fcd3a7541bffad911e858ab78c745f35d9).

Unfortunately, you will have to clone and compile the most recent version now.

**Comment by EngieDev** [comment]
Rebuilt the binary (make caches stuff) and it works perfectly, thanks!

**Comment by DL6ER** [comment]
I was more worried that you might have to rebuild the sqlite module. I had to do it today and it took like 5 minutes even on a Raspberry Pi v3...

**Comment by EngieDev** [comment]
Ah that, I did that yesterday, took about 15 minutes...
