### ISSUE TITLE
Pihole-FTL stats get reset

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [pi-hole/FTL#263]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_6_

---

**[BUG | ISSUE] Expected Behaviour:**
Increased values for blocked queries / queries.

**[BUG | ISSUE] Actual Behaviour:**
Queried & Blocked queried get reset to 0 after an unknown amount of time. The MAXDBDAYS of the daemon is set to 0, but the daemon does not get restarted so it shouls not affect those values.

**[BUG | ISSUE] Steps to reproduce:**

- Pihole-FTLDNS branch
- Disable Pihole-FTL Database
- Query pihole stats over tcp a few times for a few hours
- check the stats

**Device specifics**

Hardware Type: RasPi 3B
OS: Raspbian

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Thank you for your bug report. We do not read from the database while FTL is running. The only time FTL reads from the database is on start up to fill the history.

- Do you see the same happen when you enable the database and let it collect up to at least one day of history?
- Have you verified that there isn't maybe some process on your machine that is restarting `pihole-FTL` by itself? Have you checked `/var/log/pihole-FTL.log`? It would tell you if the daemon was restarted.

**Comment by Unkn0wn-MDCLXIV** [comment]
@DL6ER 
I just checked the FTL log. The last entry is from 8 hours ago and the stats just got reset.
I'll try it with the database enabled.

**Comment by Unkn0wn-MDCLXIV** [comment]
@DL6ER 
I've done some more testing.
When I use the default settings for pihole-FTL, the statistics are kept.
Once I set the pihole-FTL.conf to 

`SOCKET_LISTENING=localonly`
`TIMEFRAME=today`
`MAXDBDAYS=0`
`MAXLOGAGE=0`

the stats get reset regularly.

**Comment by DL6ER** [comment]
Thanks for testing.

- `TIMEFRAME` is deprecated and has no effect any more
- `MAXDBDAYS=0` means FTL should not save anything to the database
- `MAXLOGAGE=0` mean FTL should not import anything from the database on start up and the log should never contain more than zero hours of data

The latter means that whenever garbage collection is run (once an hour), it will remove everything from FTL's internal memory. This is intended behaviour (you should not set this value to zero) but I fully agree that is it somehow inconsistently described in https://github.com/pi-hole/FTL/tree/FTLDNS#ftls-config-file

**Comment by Unkn0wn-MDCLXIV** [comment]
Ah, that was the issue then I guess.
Thanks
