### ISSUE TITLE
/opt/pihole/updatecheck.sh: line 56: /usr/bin/pihole-FTL: Operation not permitted

### ISSUE THREAD

**Issue by Freekers** [pi-hole/FTL#280]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

2

---

**[BUG | ISSUE] Expected Behaviour:**
Pi-hole should install or repair without error messages

**[BUG | ISSUE] Actual Behaviour:**
Pi-hole installs / repairs but before finishing displays the following error message:
`/opt/pihole/updatecheck.sh: line 56: /usr/bin/pihole-FTL: Operation not permitted`

**[BUG | ISSUE] Steps to reproduce:**
Run either `pihole -r` or `pihole checkout core FTLDNS `

**Log file output [if available]**
Please check: http://termbin.com/ielh

**Device specifics**
Hardware Type: VPS
OS: Ubuntu 16.04.4 LTS (GNU/Linux 2.6.32-042stab127.2 x86_64)

**Comment by DL6ER** [comment]
> /usr/bin/pihole-FTL: Operation not permitted

this means that either your hypervisor or your filesystem don't like capabilities. Can you explore on the type of VPS as well as the filesystem you're using?

I doubt it will be the filesystem, but it doesn't hurt to ask.

**Comment by Freekers** [comment]
The filesystem is ext4. The hypervisor is OpenVZ.

**Comment by DL6ER** [comment]
So this seems to be indeed an OpenVZ problem. Websearching gives some forum messages such as https://forum.proxmox.com/threads/openvz-containers-on-nfs.22170/

If you cannot get `setcap` working inside OpenVZ then you could edit the init.d file manually and remove the calling of pihole-FTL  as process of an unprivileged user (let it be started as `root` process)...

**Comment by Freekers** [comment]
Thanks. I'll try and report back to you by the end of this week.

**Comment by Mcat12** [comment]
@Freekers did you find anything?

**Comment by Freekers** [comment]
@Mcat12 Sorry, I was short on time. Please give me some more time to test this for you guys. I should have time to do so by the beginning of next week.

**Comment by Freekers** [comment]
I've tried changing `FTLUSER=pihole` to `FTLUSER=root` in /etc/init.d/pihole-FTL but the issue persists on OpenVZ virtualization.

On KVM, everything works fine, without any adjustments.

**Comment by DL6ER** [comment]
@Freekers how is the current status?

**Comment by Freekers** [comment]
The same as on the 8th June. I didn't spent any more time on troubleshooting this, I am now moving everything to the Docker image.

**Comment by DL6ER** [comment]
Okay, I will close this issue then. We're looking at a possible solution with https://github.com/pi-hole/pi-hole/pull/2378.
