### ISSUE TITLE
FTL runs at 100% CPU usage eventually system hangs

### ISSUE THREAD

**Issue by dine909** [pi-hole/FTL#293]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**
Not looked at it

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_
1

**[BUG | ISSUE] Expected Behaviour:**
BUG

**[BUG | ISSUE] Actual Behaviour:**
BUG - FTL runs at 100% CPU usage eventually system hangs

**[BUG | ISSUE] Steps to reproduce:**
Leave on from boot. 

[2018-05-30 12:13:08.876] Notice: Increasing queries struct size from 180000 to 190000 (8.82 MB)
[2018-05-30 12:13:09.737] Notice: Increasing overTime struct size from 3500 to 3600 (8.83 MB)
[2018-05-30 12:13:12.712] Notice: Increasing overTime struct size from 3600 to 3700 (8.83 MB)
[2018-05-30 12:13:13.765] Notice: Increasing queries struct size from 190000 to 200000 (9.28 MB)
[2018-05-30 12:13:13.860] Notice: Increasing overTime struct size from 3700 to 3800 (9.28 MB)

this happens every few seconds until it falls over.

**Device specifics**

Hardware Type: BeagleBone
OS: Ubuntu 16.04

**Comment by Mcat12** [comment]
It sounds like you either have a device making massive amounts of DNS requests or you set up a loop in your DNS resolution path. What does the log look like (`/var/log/pihole.log`)?

**Comment by dine909** [comment]
Here an excerpt of `/var/log/pihole.log`

It looks pretty normal if i'm honest - 

If I `sudo systemctl stop pihole-FTL` (obviously) the process stops and CPU is normal, but (obviously) i have no data on the UI - however the unit no longer crashes.

I have tried `pihole -r` and `-up` so we are up-to-date and it hasn't appeared to resolve the issue - 

It happens from startup, more than happy to let someone in and investigate.

Cheers

`
Feb 11 16:28:23 dnsmasq[535]: 20 192.168.1.66/56465 query[A] ssl.gstatic.com from 192.168.1.66
Feb 11 16:28:23 dnsmasq[535]: 20 192.168.1.66/56465 cached ssl.gstatic.com is 216.58.213.99
Feb 11 16:28:23 dnsmasq[535]: 21 192.168.1.66/27968 query[A] m.google.com from 192.168.1.66
Feb 11 16:28:23 dnsmasq[535]: 21 192.168.1.66/27968 forwarded m.google.com to 1.0.0.1
Feb 11 16:28:23 dnsmasq[535]: 22 192.168.1.66/15173 query[A] www.gstatic.com from 192.168.1.66
Feb 11 16:28:23 dnsmasq[535]: 22 192.168.1.66/15173 forwarded www.gstatic.com to 1.0.0.1
Feb 11 16:28:23 dnsmasq[535]: 23 192.168.1.66/26879 query[A] www.reddit.com from 192.168.1.66
Feb 11 16:28:23 dnsmasq[535]: 23 192.168.1.66/26879 cached www.reddit.com is <CNAME>
Feb 11 16:28:23 dnsmasq[535]: 23 192.168.1.66/26879 cached reddit.map.fastly.net is 151.101.17.140
Feb 11 16:28:23 dnsmasq[535]: 16 192.168.1.66/59076 reply imap.gmail.com is <CNAME>
Feb 11 16:28:23 dnsmasq[535]: 16 192.168.1.66/59076 reply gmail-imap.l.google.com is 64.233.184.108
Feb 11 16:28:23 dnsmasq[535]: 16 192.168.1.66/59076 reply gmail-imap.l.google.com is 64.233.184.109
Feb 11 16:28:23 dnsmasq[535]: 24 127.0.0.1/49574 query[PTR] 8.8.8.8.in-addr.arpa from 127.0.0.1
Feb 11 16:28:23 dnsmasq[535]: 24 127.0.0.1/49574 forwarded 8.8.8.8.in-addr.arpa to 1.0.0.1
Feb 11 16:28:23 dnsmasq[535]: 21 192.168.1.66/27968 reply m.google.com is <CNAME>
Feb 11 16:28:23 dnsmasq[535]: 21 192.168.1.66/27968 reply mobile.l.google.com is 216.58.213.107
Feb 11 16:28:23 dnsmasq[535]: 22 192.168.1.66/15173 reply www.gstatic.com is 216.58.204.67
Feb 11 16:28:23 dnsmasq[535]: 25 192.168.1.66/49326 query[A] m.google.com from 192.168.1.66
Feb 11 16:28:23 dnsmasq[535]: 25 192.168.1.66/49326 cached m.google.com is <CNAME>
Feb 11 16:28:23 dnsmasq[535]: 25 192.168.1.66/49326 cached mobile.l.google.com is 216.58.213.107
Feb 11 16:28:23 dnsmasq[535]: 24 127.0.0.1/49574 reply 8.8.8.8 is google-public-dns-a.google.com
Feb 11 16:28:23 dnsmasq[535]: 26 192.168.1.66/38902 query[A] www.gstatic.com from 192.168.1.66
Feb 11 16:28:23 dnsmasq[535]: 26 192.168.1.66/38902 cached www.gstatic.com is 216.58.204.67
Feb 11 16:28:23 dnsmasq[535]: 27 127.0.0.1/35731 query[A] 0.debian.pool.ntp.org from 127.0.0.1
Feb 11 16:28:23 dnsmasq[535]: 27 127.0.0.1/35731 cached 0.debian.pool.ntp.org is 85.199.214.98
Feb 11 16:28:23 dnsmasq[535]: 27 127.0.0.1/35731 cached 0.debian.pool.ntp.org is 217.114.59.66
Feb 11 16:28:23 dnsmasq[535]: 27 127.0.0.1/35731 cached 0.debian.pool.ntp.org is 178.79.160.57
Feb 11 16:28:23 dnsmasq[535]: 27 127.0.0.1/35731 cached 0.debian.pool.ntp.org is 139.59.199.215
Feb 11 16:28:23 dnsmasq[535]: 28 127.0.0.1/35731 query[AAAA] 0.debian.pool.ntp.org from 127.0.0.1
`

**Comment by Mcat12** [comment]
Do you have many queries per second, and do they all seem legit? (no hammering of domains)
What are your summary stats like? `echo ">stats" | nc 127.0.0.1 4711`

**Comment by dine909** [comment]
```
>stats
domains_being_blocked 122748
dns_queries_today 12288
ads_blocked_today 1499
ads_percentage_today 12.198894
unique_domains 1407
queries_forwarded 6829
queries_cached 2506
clients_ever_seen 9
unique_clients 9
status enabled
---EOM---
```

stats look as i'd expect, although i'm thinking this is something else now..

The 100% CPU usage i observed was right after a restart (it must be indexing or something) but it did subside when i started the service to get those stats right then.

Closing as the issue isn't relevant to the report in its current state.

**Comment by Mcat12** [comment]
It does read from the database on startup, so maybe you just had a lot of queries in the database.
