### ISSUE TITLE
RPI2 testing [closed]

### ISSUE THREAD

**Issue by technicalpyro** [pi-hole/FTL#3]
was going to attempt my first PR but i either dont have it setup right or my account is not able either way here is the info i was attempting to add 

| Raspberry Pi 2 | Raspbian Jessie | armv7l | `arm-linux-gnueabihf`  | [@Technicalpyro](https://github.com/technicalpyro) |

**Comment by dschaper** [comment]
If you were trying to PR to make changes to an existing file, the easiest way is to fork the repo, make the changes on a local branch of your local repo and then submit a PR against the master branch. (Unless that is what you already tried to do, but creating a PR from a fork of the repo shouldn't require any permissions on the repo itself.)

**Comment by technicalpyro** [comment]
ok will attempt that the tutorial that taught me how tried to get me to branch and not fork and thats probably the problem

**Comment by dschaper** [comment]
Yes, non Pi-hole members do not have write access to the FTL repo branches, so you would need to fork to make any changes. I see now that you are adding to the README.md file, so that should be able to have a PR submitted against it.

**Comment by technicalpyro** [comment]
ok kinda exhilarating for me a total non coder(i can troubleshoot just suck at writing it from scratch) even to be able to do something this small ... i know how sad i am lol

**Comment by dschaper** [comment]
:) We all had to start at the beginning at one time or another.

**Comment by technicalpyro** [comment]
so now another idiot question how would i change binaries ? im willing to do it just unsure how

**Comment by dschaper** [comment]
Just download the other binary files and run them. Try passing on the debug flag along with the binary to see if there is any information passed along. `./pihole-FTL-arm-linux-gnueabi debug` (after you chmod +x the file of course.)

**Comment by technicalpyro** [comment]
may give it a shot tomorrow but right now its doing my head in ... im sure with fresh eyes i will be able to manage it

**Comment by technicalpyro** [comment]
thinking testing the arm-linux-gnuabi might be a pipe dream for me i have not been successfully able to get any of the packages it requires nor have i been able to find any files within the project containing the files every time i attempt to install the packages i get an unable to install

**Comment by DL6ER** [comment]
I don't know what you mean, you can get the binaries here:

https://github.com/pi-hole/FTL/releases/tag/v0.2

Download (one of) them and make the file executable

**Comment by technicalpyro** [comment]
there we go i knew it was here somewhere  think i was trying to get the tools used from apt-get not the actual binaries

**Comment by technicalpyro** [comment]
SUCCESS you guys put up with me way too much but go it working and no error flags thrown modifying my local copy of the fork readme now

**Comment by technicalpyro** [comment]
closing because i learned what  needed i love you guys
