### ISSUE TITLE
Problem with the Queries Answered by Graphic when using all-servers in dnsmasq.conf

### ISSUE THREAD

**Issue by Iridahonda** [pi-hole/FTL#303]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

5

**[BUG | ISSUE] Expected Behaviour:**
The queries answered by graphic on the dashboard does not seem to report the right server(s) when using the all-servers option. Seems to always show the last server listed in the .conf file

**[BUG | ISSUE] Actual Behaviour:**
Only the last server listed is displayed when using all-servers option

**[BUG | ISSUE] Steps to reproduce:**

Add all-servers to dnsmasq.conf.  
Restart pihole-FTL 
Observe the queries answered by graphic after a few hours
Change the order list of servers in 01-pihole.conf
Restart pihole-FTL
Observe the queries answered by graphic after a few hours. 

**Device specifics**

Hardware Type: rPi, VPS, etc
OS: Readynas Linux version 4.4.116.x86_64.1 (root@TimsNewMegaNas) (gcc version 8.1.1 20180602 (GCC) ) #7 SMP Sat Jun 2 22:12:44 CEST 2018

**Comment by DL6ER** [comment]
FTL only analyzes the first server that a query gets forwarded to. I have never tested the `all-servers` option, but it seems that the first server is the last one in the config file. I don't think this is an issue, as the current way of doing it is motivated by performance reasons (we ignore subsequent "forwarded to" messages instead of analyzing all of them).

**Comment by Iridahonda** [comment]
Ah ok makes sense-thanks.  The all-servers option makes a big difference in performance for me.


/Tim

**Comment by DL6ER** [comment]
Why is this the case? Do you have largely varying latencies to the servers you've configured? 

We don't really like this option as it will generate a maximum of network traffic, linearly scaling with the number of forwarding destinations. 

I'll look if I can improve FTL's behavior in FTLDNS.

**Comment by DL6ER** [comment]
I looked into this yesterday night and it would require some substantial addition of bookkeeping to ensure consistency in the statistics. This is not something that can be hacked together in 10 minutes.

Please open a feature request on [Discourse](https://discourse.pi-hole.net) if you really want this feature. I'm now closing this issues as it seems that there is, in fact, no bug in FTL.
