### ISSUE TITLE
pihole-FTL.conf won't use new settings

### ISSUE THREAD

**Issue by cokeflash** [pi-hole/FTL#318]
Hi!

I edited /etc/pihole/pihole-FTL.conf:

SOCKET_LISTENING=localonly
QUERY_DISPLAY=no
AAAA_QUERY_ANALYSIS=no
MAXDBDAYS=0
RESOLVE_IPV6=no
RESOLVE_IPV4=yes
DBINTERVAL=1.0
DBFILE=
MAXLOGAGE=744

then:
sudo service pihole-FTL stop
sudo service pihole-FTL start
sudo pihole -d

Output of pihole-FTL:
NOTICE: Received signal SIGHUP - re-reading gravity files
Gravity list entries: 893617
No blacklist present
No wildcard blocking list present
-> Total DNS queries: 0
-> Cached DNS queries: 0
-> Forwarded DNS queries: 0
-> Exactly blocked DNS queries: 0
-> Wildcard blocked DNS queries: 0
-> Unknown DNS queries: 0
-> Unique domains: 0
-> Unique clients: 0
-> Known forward destinations: 0
FTL branch: v3.0
FTL version: v3.0
FTL commit: a1b2fa03f8f3e3713b57a26a4e9a062fec0573d7
FTL date: 2018-02-14 12:45:47 -0800
FTL user: root
Starting pihole-FTL directly is not recommended.
Instead, use system commands for starting pihole-FTL as service (systemctl / service).
Starting config file parsing (/etc/pihole/pihole-FTL.conf)
SOCKET_LISTENING: all destinations
QUERY_DISPLAY: Show queries
AAAA_QUERY_ANALYSIS: Show AAAA queries

How I can get pihole-FTL uses the new edited pihole-FTL.conf?
How can I change FTL user: root to pihole?

**Comment by technicalpyro** [comment]
what is the result of `pihole -v` ?

**Comment by technicalpyro** [comment]
> FTL branch: v3.0
> FTL version: v3.0
> FTL commit: a1b2fa0
> FTL date: 2018-02-14 12:45:47 -0800

you need to be on either FTLDNS or the Development branch to use these features.  

To use it, you’ll need to be running the FTLDNS beta (pihole -up if you’re already on it):

echo "FTLDNS" | sudo tee /etc/pihole/ftlbranch
pihole checkout core FTLDNS 
pihole checkout web FTLDNS

You can also checkout the development branches, but if you want the most up-to-date code, use the FTLDNS branches.

**Comment by cokeflash** [comment]
pihole -v
  Pi-hole version is v3.3.1 (Latest: v3.3.1)
  AdminLTE version is v3.2.1 (Latest: v3.3)
  FTL version is v3.0 (Latest: v3.0)

**Comment by technicalpyro** [comment]
see my above comment regarding branches

**Comment by cokeflash** [comment]
I'll try that out tomorrow, going offline now, thanks for help :-)

**Comment by Mcat12** [comment]
You don't run `pihole-FTL` direclty, as it notes in its output. Have you checked its log? `/var/log/pihole-FTL.log`

**Comment by cokeflash** [comment]
Now, FTLdns works with dnscrypt-proxy V2, also t0r is working.

What about this options:
PRIVACYLEVEL = 0
BLOCKINGREGEX: Not set

Are there more options to tweak FTLdns with more security features?

Must I open Port 4711 in my firewall/router?

/var/log/pihole-FTL.log
########## FTL started! ##########
FTL branch: FTLDNS
FTL version: 
FTL commit: 5ecab0a
FTL date: 2018-05-18 10:24:07 +0100
FTL user: pihole
Starting config file parsing (/etc/pihole/pihole-FTL.conf)
SOCKET_LISTENING: only local
AAAA_QUERY_ANALYSIS: Hide AAAA queries
MAXDBDAYS: --- (DB disabled)
RESOLVE_IPV6: Don't resolve IPv6 addresses
RESOLVE_IPV4: Resolve IPv4 addresses
DBINTERVAL: saving to DB file every minute
DBFILE: Not using database due to empty filename
MAXLOGAGE: Importing up to 744.0 hours of log data
PRIVACYLEVEL: Set to 0
IGNORE_LOCALHOST: Show queries from localhost
BLOCKINGMODE: Pi-hole's IPs for blocked domains
BLOCKINGREGEX: Not set
Finished config file parsing
-> Total DNS queries: 0
-> Cached DNS queries: 0
-> Forwarded DNS queries: 0
-> Exactly blocked DNS queries: 0
-> Wildcard blocked DNS queries: 0
-> Unknown DNS queries: 0
-> Unique domains: 0
-> Unique clients: 0
-> Known forward destinations: 0
Successfully accessed setupVars.conf
PID of FTL process: 44564
Listening on port 4711 for incoming IPv4 telnet connections
Listening on Unix socket
No wildcard blocking list present
/etc/pihole/gravity.list: parsed 742655 domains (took 811.7 ms)
Notice: Increasing queries struct size from 0 to 10000 (640.14 KB)
Notice: Increasing overTime struct size from 0 to 100 (648.14 KB)
Notice: Increasing domains struct size from 0 to 1000 (680.17 KB)
Notice: Increasing clients struct size from 0 to 10 (680.60 KB)
New forward server: 127.0.0.3 (0/0)
Notice: Increasing forwarded struct size from 0 to 4 (680.77 KB)

**Comment by cokeflash** [comment]
...found it :-)  PRIVACYLEVEL=3

**Comment by Mcat12** [comment]
You don't have to open port 4711 on your firewall. There is also documentation available (for the dev version of FTLDNS) here: https://docs.pi-hole.net/

**Comment by cokeflash** [comment]
ok, thanks! :-)
