### ISSUE TITLE
How to move pihole logs to tmpfs?

### ISSUE THREAD

**Issue by cokeflash** [pi-hole/FTL#321]
Hi!
How can i set all pihole logs to ram with tmpfs?

In /etc/dnsmasq.d/ I set: (01-pihole.conf)

log-queries
log-facility=/var/tmp/pihole.log

pihole-log output:  warning: failed to change owner of /var/tmp/pihole.log: Operation not permitted
but the pihole.log file is working.

How can I change the owner of the pihole.log in tmpfs.
After reboot it will be reseted.

Must i set also logrotate in /etc/pihole to:
/var/tmp/pihole.log {
	su root syslog
	daily
	copytruncate
	rotate 5
	compress
	delaycompress
	notifempty
	nomail
}

/var/tmp/pihole-FTL.log {
	su root syslog
	weekly
	copytruncate
	rotate 3
	compress
	delaycompress
	notifempty
	nomail
}

and in /etc/init.d: (pihole-FTL)

# Start the service
start() {
  if is_running; then
    echo "pihole-FTL is already running"
  else
    touch /var/tmp/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port /var/tmp/pihole.log ???
    mkdir -p /var/run/pihole
    mkdir -p /var/tmp/pihole ???
    chown pihole:pihole /var/run/pihole /var/tmp/pihole ???
    rm /var/run/pihole/FTL.sock 2> /dev/null
    chown pihole:pihole /var/tmp/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port ???
    chown pihole:pihole /etc/pihole /etc/pihole/dhcp.leases /var/tmp/pihole.log ???
    chmod 0644 /var/tmp/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port /var/tmp/pihole.log ???
    setcap CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_NET_ADMIN+eip "$(which pihole-FTL)"
    echo "nameserver 127.0.0.1" | /sbin/resolvconf -a lo.piholeFTL
    su -s /bin/sh -c "/usr/bin/pihole-FTL" "$FTLUSER"
    echo
  fi
}

??? 
Please help, thanks!

**Comment by Mcat12** [comment]
Don't modify that file. Instead, mount `/var/log` under tmpfs.

**Comment by cokeflash** [comment]
is this correct in fstab?
tmpfs   				  /var/log		tmpfs		defaults,noatime,mode=1777			0	0

**Comment by Mcat12** [comment]
It might be, but there are plenty of online tutorials that will tell you if it is. Since this isn't an FTL problem I will close the issue.
