### ISSUE TITLE
No resolve via Pihole LOG but Internet works with FTLdns + dnscrypt

### ISSUE THREAD

**Issue by cokeflash** [pi-hole/FTL#322]
No resolve via Pihole LOG but Internet works with FTLdns + dnscrypt

Hi!

What is wrong with my configs?
Internet with dnscrypt+pihole works, blocking works but why I get the error message in
pihole debug?

Which all values must I change for correct config?

pihole log shows me:

Ports in use
[4711] is in use by pihole-FTL
[53] is in use by dnsmasq
[9050] is in use by tor
[53] is in use by dnsmasq
[53] is in use by dnsmasq

dnscrypt-proxy will showed in pihole debug log when I change port 53 to 513 @
listen_addresses = ['127.0.0.1:53'] to 127.0.0.1:513 and under
dnscrypt-proxy.socket to 513

[✗] Failed to resolve  via localhost (127.0.0.1)
[✗] Failed to resolve  via Pi-hole (192.168.178.100)
[✓] doubleclick.com is 172.217.16.78 via a remote, public DNS server (8.8.8.8)

Pi-hole processes
[✗] dnsmasq daemon is inactive
[✗] lighttpd daemon is inactive
[✓] pihole-FTL daemon is active

my configz:

In NetworkManager (UbuntuMate) = 127.0.0.1

/etc/dnsmasq.d/
###############
01-pihole.conf:

addn-hosts=/etc/pihole/gravity.list
addn-hosts=/etc/pihole/black.list
addn-hosts=/etc/pihole/local.list
localise-queries
#no-resolv
cache-size=10000
log-queries=extra
log-facility=/var/log/pihole.log
local-ttl=2
log-async
server=127.0.2.1
dnssec
trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5
trust-anchor=.,20326,8,2,E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D
interface=enp4s0

/etc/dnsmasq.d/
###############
02-dnscrypt-proxy.conf:

server=127.0.2.1
#no-resolv
proxy-dnssec

/etc/dnscrypt-proxy/
####################
dnscrypt-proxy.toml

listen_addresses = ['127.0.0.1:53']

/lib/systemd/system/
dnscrypt-proxy.socket:

ListenStream=127.0.2.1:53
ListenDatagram=127.0.2.1:53

/etc/pihole/
############
pihole-FTL.conf:

SOCKET_LISTENING=all
RESOLVE_IPV4=yes
RESOLVE_IPV6=no
QUERY_DISPLAY=yes
AAAA_QUERY_ANALYSIS=yes
MAXDBDAYS=1
MAXLOGAGE=24.0
DBFILE=/etc/pihole/pihole-FTL.db
DBINTERVAL=1.0
FTLPORT=4711
PRIVACYLEVEL=3
IGNORE_LOCALHOST=no
BLOCKINGMODE=NULL

/etc/pihole/
############
setupVars.conf:

DNSSEC=true
PIHOLE_INTERFACE=enp4s0
IPV4_ADDRESS=192.168.178.100/24
IPV6_ADDRESS=
PIHOLE_DNS_1=
PIHOLE_DNS_2=
QUERY_LOGGING=true
INSTALL_WEB=false
INSTALL_WEB_SERVER=false
INSTALL_WEB_INTERFACE=false
LIGHTTPD_ENABLED=0

/etc/
#####
dnsmasq.conf:

listen-address=127.0.0.1
port=5353
domain-needed
bogus-priv
dnssec
proxy-dnssec
strict-order
no-resolv
no-poll
server=127.0.2.1
#cache-size=1000
neg-ttl=3600
dns-forward-max=150
bind-interfaces

/etc/network/
#############
interfaces:

# [INTERFACE] FILE used by IFUP and IFDOWN:
auto lo
iface lo inet loopback

#### STATIC // [!LAN!]
allow-hotplug enp4s0
iface enp4s0 inet static
 address 192.168.178.100
 netmask 255.255.255.0
 gateway 192.168.178.1
 dns-nameservers 127.0.0.1

Please help, thanks!

**Comment by Mcat12** [comment]
Run `pihole -d` for a debug token, and share the output of these commands:
```
sudo service dnsmasq status -l
sudo service lighttpd status -l
```

**Comment by cokeflash** [comment]
dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; disabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/dnsmasq.service.d
           └─resolved-fix.conf
   Active: inactive (dead)

I don't use lighttpd and web-interface of pihole.

dnsmasq is disabled by FTLDNS.

*** [ INITIALIZING ] Sourcing setup variables
[i] Sourcing /etc/pihole/setupVars.conf...

*** [ DIAGNOSING ]: Core version
[i] Core: v3.3.1 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Branch: FTLDNS (https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#checkout)
[i] Commit: v3.3.1-136-ga7e7680

*** [ DIAGNOSING ]: Web version

*** [ DIAGNOSING ]: FTL version
[✓] FTL: v3.0

*** [ DIAGNOSING ]: dnsmasq version
[i] 2.79

*** [ DIAGNOSING ]: lighttpd version
[i] opt

*** [ DIAGNOSING ]: php version
[i] 7.2.7

*** [ DIAGNOSING ]: Operating system
[✓] Ubuntu 18.04 LTS

*** [ DIAGNOSING ]: SELinux
[✓] Default SELinux: disabled
/opt/pihole/piholeDebug.sh: line 442: getenforce: command not found
[✓] Current SELinux: 

*** [ DIAGNOSING ]: Processor
[i] x86_64

*** [ DIAGNOSING ]: Networking
[✓] IPv4 address(es) bound to the enp4s0 interface:
   192.168.178.100/24 matches the IP found in /etc/pihole/setupVars.conf
   169.254.56.37/16 does not match the IP found in /etc/pihole/setupVars.conf (https://discourse.pi-hole.net/t/use-ipv6-ula-addresses-for-pi-hole/2127)

[✗] No IPv6 address(es) found on the enp4s0 interface.

[i] Default IPv4 gateway: 192.168.178.1
   * Pinging 192.168.178.1...
[✓] Gateway responded.

*** [ DIAGNOSING ]: Ports in use
[4711] is in use by pihole-FTL
[53] is in use by dnsmasq
[9050] is in use by tor
[9665] is in use by java
[9666] is in use by java
[53] is in use by dnsmasq
[53] is in use by dnsmasq

*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
dig: '' is not a legal name (unexpected end of input)
[✗] Failed to resolve  via localhost (127.0.0.1)
dig: '' is not a legal name (unexpected end of input)
[✗] Failed to resolve  via Pi-hole (192.168.178.100)
[✓] doubleclick.com is 172.217.19.78 via a remote, public DNS server (8.8.8.8)

*** [ DIAGNOSING ]: Pi-hole processes
[✗] dnsmasq daemon is inactive
[✗] lighttpd daemon is inactive
[✓] pihole-FTL daemon is active

*** [ DIAGNOSING ]: Setup variables
    DNSSEC=true
    PIHOLE_INTERFACE=enp4s0
    IPV4_ADDRESS=192.168.178.100/24
    IPV6_ADDRESS=
    #PIHOLE_DNS_1=
    #PIHOLE_DNS_2=
    QUERY_LOGGING=true
    INSTALL_WEB=false
    INSTALL_WEB_SERVER=false
    INSTALL_WEB_INTERFACE=false
    LIGHTTPD_ENABLED=0

*** [ DIAGNOSING ]: Dashboard and block page
[✗] Block page X-Header: X-Header does not match or could not be retrieved.

[✗] Web interface X-Header: X-Header does not match or could not be retrieved.


*** [ DIAGNOSING ]: Gravity list
-rw-r--r-- 1 root root 2940953 Jul  5 12:50 /etc/pihole/gravity.list
   -----head of gravity.list------
   0.0.0.0
   0.r.msn.com
   0.start.bz
   000.0x1f4b0.com

   -----tail of gravity.list------
   zzz.clickbank.net
   zzzezeroe.fr
   zzzpooeaz-france.com
   zzzrtrcm2.com

*** [ DIAGNOSING ]: contents of /etc/pihole

-rw-r--r-- 1 root root 381 Jul  5 12:49 /etc/pihole/adlists.list
   https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
   https://mirror1.malwaredomains.com/files/justdomains
   http://sysctl.org/cameleon/hosts
   https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
   https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
   https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
   https://hosts-file.net/ad_servers.txt

-rw-r--r-- 1 root root 44 Jun 25 17:28 /etc/pihole/local.list
   192.168.178.100 amd
   192.168.178.100 pi.hole

-rw-r--r-- 1 root root 238 Jul  5 12:49 /etc/pihole/logrotate
   /var/log/pihole.log {
   	su root syslog
   	daily
   	copytruncate
   	rotate 5
   	compress
   	delaycompress
   	notifempty
   	nomail
   }
   /var/log/pihole-FTL.log {
   	su root syslog
   	weekly
   	copytruncate
   	rotate 3
   	compress
   	delaycompress
   	notifempty
   	nomail
   }

*** [ DIAGNOSING ]: contents of /etc/dnsmasq.d

-rw-r--r-- 1 root root 1677 Jul  7 12:33 /etc/dnsmasq.d/01-pihole.conf
   addn-hosts=/etc/pihole/gravity.list
   addn-hosts=/etc/pihole/black.list
   addn-hosts=/etc/pihole/local.list
   localise-queries
   no-resolv
   cache-size=10000
   log-queries=extra
   log-facility=/var/log/pihole.log
   local-ttl=2
   log-async
   dnssec
   trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5
   trust-anchor=.,20326,8,2,E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D
   interface=enp4s0

*** [ DIAGNOSING ]: contents of /etc/lighttpd
/etc/lighttpd does not exist.
ls: cannot access '/etc/lighttpd': No such file or directory

*** [ DIAGNOSING ]: contents of /etc/cron.d

-rw-r--r-- 1 root root 1496 Jul  5 12:49 /etc/cron.d/pihole
   45 4   * * 7   root    PATH="$PATH:/usr/local/bin/" pihole updateGravity
   00 00   * * *   root    PATH="$PATH:/usr/local/bin/" pihole flush once quiet
   @reboot root /usr/sbin/logrotate /etc/pihole/logrotate
   */10 *  * * *   root    PATH="$PATH:/usr/local/bin/" pihole updatechecker local
   37 13  * * *   root    PATH="$PATH:/usr/local/bin/" pihole updatechecker remote
   @reboot root    PATH="$PATH:/usr/local/bin/" pihole updatechecker remote reboot

*** [ DIAGNOSING ]: contents of /var/log/lighttpd
/var/log/lighttpd does not exist.
ls: cannot access '/var/log/lighttpd': No such file or directory

*** [ DIAGNOSING ]: contents of /var/log

-rw-r--r-- 1 pihole pihole 40233 Jul  7 12:33 /var/log/pihole-FTL.log
   -----head of pihole-FTL.log------
   [2018-07-05 19:42:03.799] FATAL: FTL received SIGTERM from PID/UID 21240/0, exiting gracefully
   [2018-07-05 19:42:03.799] Shutting down...
   [2018-07-05 19:42:03.810] Finished final database update
   [2018-07-05 19:42:03.810] ########## FTL terminated after 11.6 ms! ##########
   [2018-07-05 19:42:15.960] ########## FTL started! ##########
   [2018-07-05 19:42:15.960] FTL branch: v3.0
   [2018-07-05 19:42:15.960] FTL version: v3.0
   [2018-07-05 19:42:15.960] FTL commit: a1b2fa03f8f3e3713b57a26a4e9a062fec0573d7
   [2018-07-05 19:42:15.960] FTL date: 2018-02-14 12:45:47 -0800
   [2018-07-05 19:42:15.960] FTL user: pihole
   [2018-07-05 19:42:15.960] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
   [2018-07-05 19:42:15.960]    SOCKET_LISTENING: all destinations
   [2018-07-05 19:42:15.960]    QUERY_DISPLAY: Show queries
   [2018-07-05 19:42:15.960]    AAAA_QUERY_ANALYSIS: Show AAAA queries
   [2018-07-05 19:42:15.960]    MAXDBDAYS: max age for stored queries is 1 days
   [2018-07-05 19:42:15.960]    RESOLVE_IPV6: Don't resolve IPv6 addresses
   [2018-07-05 19:42:15.960]    RESOLVE_IPV4: Resolve IPv4 addresses
   [2018-07-05 19:42:15.960]    DBINTERVAL: saving to DB file every minute
   [2018-07-05 19:42:15.960]    DBFILE: Using /etc/pihole/pihole-FTL.db
   [2018-07-05 19:42:15.960]    MAXLOGAGE: Importing up to 24.0 hours of log data
   [2018-07-05 19:42:15.960] Finished config file parsing
   [2018-07-05 19:42:15.963] Found no other running pihole-FTL process
   [2018-07-05 19:42:15.963] PID of FTL process: 21380
   [2018-07-05 19:42:16.009] Gravity list entries: 742656
   [2018-07-05 19:42:16.009] No blacklist present
   [2018-07-05 19:42:16.009] No wildcard blocking list present
   [2018-07-05 19:42:16.009] Database initialized
   [2018-07-05 19:42:16.009] Imported 0 queries from the long-term database
   [2018-07-05 19:42:16.009] Starting initial log file parsing
   [2018-07-05 19:42:16.009] Reading from /var/log/pihole.log (rw-r--r--)
   [2018-07-05 19:42:16.009] Finished initial log file parsing
   [2018-07-05 19:42:16.009]  -> Total DNS queries: 0
   [2018-07-05 19:42:16.009]  -> Cached DNS queries: 0
   [2018-07-05 19:42:16.009]  -> Forwarded DNS queries: 0
   [2018-07-05 19:42:16.009]  -> Exactly blocked DNS queries: 0

**Comment by cokeflash** [comment]
Failed to resolve via localhost (127.0.0.1)

Do I need to change in NetworkManager = 127.0.2.1 = dnscryp-proxy?

**Comment by cokeflash** [comment]
01-pihole.conf = noresolv
02-dnscrypt-proxy.conf = noresolv
setupVars.conf = pihole_dns = empty
(FTLDNS) pihole-FTL.conf = RESOLVE_IPV4=yes 
dnsmasq.conf = server=127.0.2.1 + listen-address=127.0.0.1 + port=5353

**Comment by cokeflash** [comment]
...in the past, it worked with dnsmasq without FTLDNS.

**Comment by Mcat12** [comment]
That output is expected at the moment. There are some fixes in dev for the debug log, such as the "Failed to resolve" issue. Also, since you are not using the web interface, lighttpd will not be running and therefore will show up as not running in the debug log.
