### ISSUE TITLE
Upgrading from v3 to v4 cant install FTL: curl 404

### ISSUE THREAD

**Issue by pixelshaded** [pi-hole/FTL#343]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

0

---

**[BUG | ISSUE] Expected Behaviour:**
pihole -up is able to upgrade FTL from v3 to v4

**[BUG | ISSUE] Actual Behaviour:**
It detects a new version of FTL but fails to download binary.

**[BUG | ISSUE] Steps to reproduce:**

install pihole 3. Run pihole -up. Note that installing pihole from wget in documentation installed 3 instead of 4.

**Log file output [if available]**

Downloading and Installing FTL...curl: (22) The request URL returned error: 404 Not Found

**Device specifics**

Hardware Type: rPi2
OS: Ubuntu Mate 16

**Comment by dschaper** [comment]
We are aware of this and are working on repairing it.

**Comment by pixelshaded** [comment]
it worked. thank you.
