### ISSUE TITLE
FTL not found 404

### ISSUE THREAD

**Issue by jxer** [pi-hole/FTL#346]
as previously stated ftl does not upgrade due to 404 error

**Comment by DL6ER** [comment]
Duplicate of #229 and not actually a problem of the FTL daemon. Please contribute to the issue ticket under https://github.com/pi-hole/pi-hole/issues/2336

**Comment by jxer** [comment]
@DL6ER 
i was literally told to open this??????

**Comment by Mcat12** [comment]
@PromoFaux asked you to open a new issue in a different repo (pi-hole/pi-hole), not this one (pi-hole/FTL):
https://github.com/pi-hole/FTL/issues/229#issuecomment-411475244

**Comment by Mcat12** [comment]
It would also help if you linked what you were referencing with "as previously stated".
