### ISSUE TITLE
Allow foreground execution for s6 style service

### ISSUE THREAD

**Issue by diginc** [pi-hole/FTL#35]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_6_

---

Simple request: since backgrounding/daemonizing is the default of pihole-FTL, please provide a `-f` argument to run it in the foreground to provide some more versatility with other supervisor style service managers like s6.

I just converted the pi-hole docker image to use s6-overlay, all my other services for the docker-pi-hole container have a option to run them int he foreground so that s6-supervisor can properly watch the long running process (also intake logs) and restart it if something goes wrong.

More details on s6 services: http://www.skarnet.org/software/s6/servicedir.html see the bullet points, the 5th in particular:

>  execute into the long-lived process that is to be supervised by s6-supervise, i.e. the real foo daemon. That process must not "background itself": being run by a supervision tree already makes it a "background" task. 

s6 will just restart a service over and over when the process goes into background mode (learned this with php-fpm) since it is a supervisor style service manager, the exit of the `run` script means the service stopped in s6's mind and it triggers another run unless it was just told to stop the service.

I can work around this for now with something silly like `while pgrep pihole-FTL ; do sleep 5 ; done` at the end of my s6 service run script, so no rush.

**Comment by dschaper** [comment]
So you need a `no-daemon` mode to get things working correctly? I could see this helping out with debugging and possibly with some of the test in the Travis build matrix to smoke test builds in the x86 platform.

**Comment by technicalpyro** [comment]
starting FTL with the command `service pihole-FTL debug start` should prevent it from going into daemon mode

**Comment by diginc** [comment]
ah yup `pihole-FTL debug` is what I need, thanks.  Next time I'll RTFM.  I tried `pihole -h` but there was no help there :(

**Comment by DL6ER** [comment]
Although you have been able to achieve what you need using `debug` this also enabled the ultra-verbose mode (your log file will grow quickly). I'll reopen this issue to remind myself to implement 

- a `no-daemon, -f`, and
- a `help, -h` flag
