### ISSUE TITLE
DNS resolve from machine fails

### ISSUE THREAD

**Issue by Swaagie** [pi-hole/FTL#359]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

0
---

**[BUG | ISSUE] Expected Behaviour:**
`ping google.com` from the machine should resolve to the IP of website.

**[BUG | ISSUE] Actual Behaviour:**
`ping google.com` results in `ping: unknown host google.com`

**[BUG | ISSUE] Steps to reproduce:**

- Updated pi-hole to version 4 including FTL. 
- FTLDNS runs on port 53 and dnsmasq is not running at all because of it. 
- Resolving DNS from pi-hole itself seems to work fine. Resolving from terminal ssh-ed in the machine does not work. 
- Simple `ping` will fail.
- Stopping FTL and starting dnsmasq will fix the resolving from terminal but breaks pi-hole/FTL.

**Device specifics**

Hardware Type: rPi, VPS, etc
OS: `Linux raspberrypi 4.14.24-v7+#1097 SMP Mon Mar 5 16:42:05 GMT 2018 armv7l GNU/Linux`

**Comment by Swaagie** [comment]
As a result of DNS not resolving, `pihole -d` fails to upload logs as well. I could manually grab and paste them here/pastebin if needed.

**Comment by DL6ER** [comment]
English is not my first language, so just to make sure that with

> Resolving DNS from pi-hole itself seems to work fine. Resolving from terminal ssh-ed in the machine does not work.

Means that when you ssh to your Pi-hole everything works *there* but name resolution doesn't work on any other machine in your network?

Are there any visible differences in `/var/log/pihole.log` if you start `pihole-FTL` vs. `dnsmasq`?

**Comment by Swaagie** [comment]
> Means that when you ssh to your Pi-hole everything works there but name resolution doesn't work on any other machine in your network?

Sorry I should have been more clear:
- Pi-hole DNS works, so every machine in the network can resolve fine (since the router has pi-hole's IP as dedicated DNS)
- When I'm ssh-ed into the machine I can't resolve any domains.

I'll check the logs for any differences.

**Comment by Mcat12** [comment]
What is the content of `/etc/resolv.conf` on the Pi-hole? Also share the output of `dig google.com @127.0.0.1`

**Comment by Swaagie** [comment]
Content of `/etc/resolv.conf`
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
```

dig

```
; <<>> DiG 9.9.5-9+deb8u15-Raspbian <<>> google.com@127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 5782
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com\@127.0.0.1.		IN	A

;; Query time: 95 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Aug 21 08:41:32 CEST 2018
;; MSG SIZE  rcvd: 49
```

**Comment by DL6ER** [comment]
@Swaagie You missed a space, the command should have been:
```
dig google.com @127.0.0.1
```

**Comment by war59312** [comment]
Think I'm having similar issue. :(

Was fine before v4 upgrade. Bummer.

> pi@raspberrypi:~ $ sudo systemctl status pihole-FTL.service
> ● pihole-FTL.service - LSB: pihole-FTL daemon
>    Loaded: loaded (/etc/init.d/pihole-FTL; generated; vendor preset: enabled)
>    Active: active (exited) since Sat 2018-08-25 16:13:39 EDT; 4min 49s ago
>      Docs: man:systemd-sysv-generator(8)
>   Process: 402 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)
>    CGroup: /system.slice/pihole-FTL.service
> 
> Aug 25 16:13:26 raspberrypi systemd[1]: Starting LSB: pihole-FTL daemon...
> Aug 25 16:13:26 raspberrypi pihole-FTL[402]: Not running
> Aug 25 16:13:27 raspberrypi pihole-FTL[402]: chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
> Aug 25 16:13:38 raspberrypi su[1085]: Successful su for pihole by root
> Aug 25 16:13:38 raspberrypi su[1085]: + ??? root:pihole
> Aug 25 16:13:38 raspberrypi su[1085]: pam_unix(su:session): session opened for user pihole by (uid=0)
> Aug 25 16:13:39 raspberrypi pihole-FTL[402]: FTL started!
> Aug 25 16:13:39 raspberrypi systemd[1]: Started LSB: pihole-FTL daemon.

> pi@raspberrypi:/etc/pihole $ dig google.com @127.0.0.1
> 
> ; <<>> DiG 9.10.3-P4-Raspbian <<>> google.com @127.0.0.1
> ;; global options: +cmd
> ;; connection timed out; no servers could be reached

> pi@raspberrypi:/etc/pihole $ ping google.com
> ping: google.com: Temporary failure in name resolution

**Comment by Swaagie** [comment]
My bad, sorry have been out for work a bit

```
; <<>> DiG 9.9.5-9+deb8u15-Raspbian <<>> google.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 30895
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; Query time: 28 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Aug 31 09:32:11 CEST 2018
;; MSG SIZE  rcvd: 39
```

**Comment by DL6ER** [comment]
No worries. I assume that you have no valid upstream DNS server configured. What's the content of
`/etc/dnsmasq.d/01-pihole.conf`?

**Comment by Swaagie** [comment]
Totally forgot about the upstream DNS option, the first two (199 range) are from Norton but those machines appear to be dead or moved. Perhaps it didn't get to fallback to the other 3?

**Comment by Swaagie** [comment]
Figured it out by fiddling with config/options a bit, after turning of DNSSEC manual resolves from the command line started working again.

**Comment by Swaagie** [comment]
Going to close this ticket as there is not a single identified bug as result of it, will keep an eye on the feature improvements. 

Also awesome work btw 👏 !
