### ISSUE TITLE
Memory Leak in insetupVarsArray/setupVars.c

### ISSUE THREAD

**Issue by stumpylog** [pi-hole/FTL#36]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1_

---

**[BUG] Expected Behaviour:**
All allocated memory should be freed.

**[BUG] Actual Behaviour:**
In [setupVars.c:156](https://github.com/pi-hole/FTL/blob/89fab7888a4dafae0d1a6fd9be205b68930dd6b8/setupVars.c#L156), if the condition is false (ie ststr == NULL), the allocated `domain` will not be freed before the return and the pointer will be lost.

**[BUG] Steps to reproduce:**
Essentially, if insetupVarsArray is called with these values (for my own ease, I really just copied the function to my main.c):

```
int setupVarsElements = 1;
char * setupVarsArray[] = {"*test.com\0"};

int main(int argc, char* argv[])
{	
    insetupVarsArray("");
}
```

**Log file output**

```==2670== Memcheck, a memory error detector
==2670== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==2670== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==2670== Command: ./test
==2670== 
==2670== 
==2670== HEAP SUMMARY:
==2670==     in use at exit: 9 bytes in 1 blocks
==2670==   total heap usage: 1 allocs, 0 frees, 9 bytes allocated
==2670== 
==2670== LEAK SUMMARY:
==2670==    definitely lost: 9 bytes in 1 blocks
==2670==    indirectly lost: 0 bytes in 0 blocks
==2670==      possibly lost: 0 bytes in 0 blocks
==2670==    still reachable: 0 bytes in 0 blocks
==2670==         suppressed: 0 bytes in 0 blocks
==2670== Rerun with --leak-check=full to see details of leaked memory
==2670== 
==2670== For counts of detected and suppressed errors, rerun with: -v
==2670== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Device specifics**

Hardware Type: rPi, VPS, etc
OS: Ubuntu 17.04, gcc 6.3.  There are several other memory leaks also reported by [scan-build](https://clang-analyzer.llvm.org/scan-build.html).  The steps to reproduce them are rather complicated, so I might leave that up to someone more familiar with the code base.  I could zip up the results, if needed

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by technicalpyro** [comment]
on the same instance (if possible) does [valgrind ](http://valgrind.org/) return? reason i ask is if the memory leak testing already in place is not sufficient (i don't know for sure it isnt) would be very important to know

**Comment by stumpylog** [comment]
So, I'm guessing by "instance", you mean installing Pi-Hole on the VM and running it?

Doing so, then following the "Debugging instructions", with `gdb` essentially replaced with `valgrind --leak-check=full ./pihole-FTL debug`, I don't see anything reported that is not in a library (and so likely wrong I think?).  Most likely, any cases aren't being hit.

The scan-build output traces a path of 23+ steps for the other leaks, which seem unlikely to be reached normally.

**Comment by stumpylog** [comment]
I'm not following how shipping precompiled would avoid a memory leak?  This one in particular seems like it could be triggerable.  I'm barely familiar with the code, but it seems that `insetupVarsArray` is called with items from the `domainsDataStruct *domains;`, that may be based off of the requested domains from the DNS server?  If that is data from a user source, it would be best to be defensive I think.

Mass panic?  I doubt it.  If it is leaking, the memory allocated for domain is likely a few tens of bytes at most.  If it really was occurring a lot, I think people might have noticed.  Seems like small scale, just some potential cleanups

**Comment by DL6ER** [comment]
Thanks for reporting this. I will take a look at this and code a fix if needed. I'll reference this issue in this case so you will be notified.
