### ISSUE TITLE
pihole-FTL won't start if a DHCP server is already running, even with DHCP feature disabled

### ISSUE THREAD

**Issue by squash** [pi-hole/FTL#360]
**[BUG | ISSUE] Expected Behaviour:**
pihold-FTL starts successfully

**[BUG | ISSUE] Actual Behaviour:**
Aug 19 17:02:28 idea pihole-FTL[17262]: dnsmasq: failed to bind DHCP server socket: Address already in use

**[BUG | ISSUE] Steps to reproduce:**
Configure and start your own dnsmasq for dhcp
Install pi-hole with DHCP disabled
Try to start pihole-FTL
Frown when it doesn't work

**Device specifics**
Laptop PC
Ubuntu 18.04 amd64

As a workaround for evaluation purposes I'm letting pihole do DHCP but this prevents more advanced dhcp features.

**Comment by DL6ER** [comment]
> As a workaround for evaluation purposes I'm letting pihole do DHCP but this prevents more advanced dhcp features.

Why?

You do not need to use the (simplified) DHCP interface of Pi-hole that is presented on the settings page. You can use arbitrarily complicated DHCP configuration by just putting a suitable config file into `/etc/dnsmasq.d`.

**Comment by squash** [comment]
I found it. The interaction between dnsmasq and pihole wasn't clear. it's piggybacking on the OS installed dnsmasq and requires a blank config otherwise.

Removing my customized config options allows me to use another dhcp server instead.

**Comment by DL6ER** [comment]
Not sure what you mean by "piggybacking" as `pihole-FTL` in fact includes its own copy of `dnsmasq` (as of Pi-hole v4.0). The system-wide `dnsmasq` could even be removed.

**Comment by squash** [comment]
https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L2089

when i say piggybacking, I'm referring to pi-hole installer adding config options to an existing dnsmasq.conf. if you were using dnsmasq already, this can effectively break it. Maybe clarifying in the installer that an existing dnsmasq will be broken and that removing it might be a good prerequisite instead?

**Comment by DL6ER** [comment]
> Maybe clarifying in the installer that an existing dnsmasq will be broken and that removing it might be a good prerequisite instead?

Hmm, I agree that the quoted code part is not optimal. However, Pi-hole is rather meant to be installed on more or less vanilla systems not already using `dnsmasq` in an advanced configuration. We need to ensure that this line is in the config so that we can be sure that dropping any other config files in this folder is causing them to be loaded.

**Comment by squash** [comment]
The installer already detects the existence of a dnsmasq.conf and recognizes if it wasn't created by pi-hole. In that case maybe backing it up to a .old or similar and dropping in a new file would more reasonable?

**Comment by DL6ER** [comment]
I agree that moving the existing file out of the way and putting an empty file with only this one line there is a better solution. I will open a PR on the pi-hole/pi-hole PR for this.

**Comment by DL6ER** [comment]
The improved handling of an already existing `dnsmasq.conf` will be released in Pi-hole v4.1

@squash I think your issue is resolved, right? If so, we can close this ticket.

**Comment by squash** [comment]
My issue is resolved. The changes in the merge would have prevented my issue. Thanks!
