### ISSUE TITLE
Please add support for ignorelist.txt (skip the log)

### ISSUE THREAD

**Issue by sudhaker** [pi-hole/FTL#370]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**
4
---

**[BUG | ISSUE] Expected Behaviour:**

Devices like "Fire TV" (and other Amazon's devices) literally flood the DNS 

In about 10 hours, each of my "Fire TV" devices made over 12000 query to 'spectrum.s3.amazonaws.com' ; and the entries remains as blocked even if I block the domain.

Another domain which I find being slammed pretty hard is "device-metrics-us.amazon.com" (by default blocked, but frequency remains same even after white-listing).

These entries make DB bloated and Web UI  slow/crash.

**[BUG | ISSUE] Actual Behaviour:**

An healthy / usable system that can withstand abuse from "Amazon" devices.

**[BUG | ISSUE] Steps to reproduce:**

This URL will crash your browser - http://pi-hole/admin/queries.php?domain=spectrum.s3.amazonaws.com

**Log file output [if available]**

N/A

**Device specifics**

"Fire TV" (and other Amazon's devices)

**Enhancement / Feature Request**

It would be great if FTL can natively support ignorelist.txt (or skiplogs.txt) ; anything listed there should skip the logging system and bring back the sanity to pi-hole.

And  the corresponding UI to manage it.

**Comment by DL6ER** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we do not respond to Feature Requests in Issue tickets. Please visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance and open a feature request discussion there if a similar feature request does not already exist.
