### ISSUE TITLE
[FTLDNS] Add lookahead/lookbehind support for regular expressions

### ISSUE THREAD

**Issue by planetshg** [pi-hole/FTL#377]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1_

---

**ISSUE Expected Behaviour:**
Adding a regular expression (via web interface or directly to `/etc/pihole/regex.list`) _containing a look(behind|ahead)_ should allow, for example, to block a top-level domain while allowing wildcard-ish exceptions to it. This is deemed useful as to not force users list all acceptable subdomains of a specific domain within an otherwise blocked top level domain.

_Abstract example:_ The RegEx `(?<!some|where)(^|\.)gg$` should block all .gg domains except some.gg and where.gg, as well as their subdomains, like else.where.gg. [Here's a promising test case at regex101.com.](https://regex101.com/r/OuwjsW/2/)

_Real-world example:_ The RegEx `(?<!discord)(^|\.)gg$` should block all .gg domains except discord.gg as well as its subdomain gateway.discord.gg. [Here's a corresponding test case at regex101.com.](https://regex101.com/r/OuwjsW/1/)

**ISSUE Actual Behaviour:**
Rules containing a lookahead produce a regex compile error on FTL restart in /var/log/pihole-FTL.log (see below): `ERROR compiling regex on line 65: Invalid preceding regular expression (13)`.

Seemingly a consequence, all domains under that top-level domain remain unblocked.

This could be an implication of invoking `grep -E` or `egrep`, which is not supporting lookaheads (ERE).
A possible change may be invoking `grep -P` instead, to make use of PCRE.

**ISSUE Steps to reproduce:**
1. Make sure none of .gg, discord.gg and gateway.discord.gg are contained in any blacklist
1. Add lookahead RegEx to blacklist (e.g., `(?<!discord)(^|\.)gg$`
1. Restart service (e.g., `sudo service pihole-FTL restart`)
1. Lookup discord.gg (e.g., `nslookup discord.gg`)
1. Lookup gateway.discord.gg (e.g., `nslookup gateway.discord.gg`)
1. Lookup other .gg domain (e.g., `nslookup tanks.gg`)

**Log file output [if available]**
/var/log/pihole-FTL.log:
`ERROR compiling regex on line 65: Invalid preceding regular expression (13)`

Checking DNS resolution:
```
$ nslookup discord.gg
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   discord.gg
Address: 104.16.59.37
Name:   discord.gg
Address: 104.16.60.37

$ nslookup gateway.discord.gg
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   gateway.discord.gg
Address: 104.16.60.37
Name:   gateway.discord.gg
Address: 104.16.59.37

$ nslookup tanks.gg
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   tanks.gg
Address: 104.24.99.61
Name:   tanks.gg
Address: 104.24.98.61
```
Again, desirable ("expectation") would be 0.0.0.0 for tanks.gg, i.e. blocked, as its not contained within the lookahead clause.

**Device specifics**

Hardware Type: AMD Athlon(tm) 5350 APU with Radeon(tm) R3
OS: Debian GNU/Linux 9 (stretch)
Kernel: Linux 4.9.0-8-amd64
Architecture: x86-64
Pi-hole version: v4.0
AdminLTE version: v4.0
FTL version: v4.0

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
This is expected. As described [here](https://docs.pi-hole.net/ftldns/regex/overview/), we in fact implement ERE. However, we implement regex natively and changing it to something else would be an *immense* amount of work.

**Comment by DL6ER** [comment]
This is expected. As described [here](https://docs.pi-hole.net/ftldns/regex/overview/), we in fact implement ERE. However, we implement regex natively and changing it to something else would be an *immense* amount of work.
