### ISSUE TITLE
[doc] SQLite online backup

### ISSUE THREAD

**Issue by mfr-itr** [pi-hole/FTL#392]
The doc at https://docs.pi-hole.net/ftldns/database/ mentions that in order to backup the database, one muse stop the service and copy the .db file. There is an other option:
```
$ sqlite3 ftl.db
> .backup ftp-backup.db
>
```
It uses the [Online Backup](https://www.sqlite.org/backup.html) feature.

**Comment by DL6ER** [comment]
Thanks, we will add this as an alternative to the documentation. However, it will not replace the current suggestion as it is a bit easier for inexperienced users.

**Comment by mfr-itr** [comment]
I was thinking more like adding a backup script which would be even simpler and safer to use ^^

**Comment by mfr-itr** [comment]
BTW, you can also do `sqlite3 db ".backup db.backup"`.

**Comment by DL6ER** [comment]
> The doc at https://docs.pi-hole.net/ftldns/database/ mentions that in order to backup the database, one muse stop the service and copy the .db file.

I came around to check this now, and I don't think that this is what we say there. We say you need to sop / move / start if you want to move the database to another location:
> You can split your long-term database by periodically rotating the database file (do this only when pihole-FTL is not running). The individual database contents can easily be merged when required.

I suggest to add a new paragraph concerning a backup mechanism, but we currently just don't say anything about how to back up the database.

Suggested:
![screenshot at 2018-09-28 12-03-21](https://user-images.githubusercontent.com/16748619/46202215-8271e800-c316-11e8-92ed-d58d514f7cce.png)

Note that this will only become live until another member of the developers team has reviewed and approved the documentation change.

**Comment by mfr-itr** [comment]
Oh, my bad, I read that too fast. I missed that it's `mv` and not `cp`.
SGTM
