### ISSUE TITLE
Provide option to drop ESNI records for blocked domains

### ISSUE THREAD

**Issue by mhofman** [pi-hole/FTL#393]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:** 

_1_

---

**Expected / Actual Behaviour:**
When combining Pi-Hole with @kvic-z pixelsrv-tls, the encrypted blocked connections can be answered by an HTTPS server instead of being completely dropped (`BLOCKINGMODE=IP`).

The way this works is that pixelsrv-tls generates a certificate dynamically that will match the Server Name sent in the SNI extension, which should end up passing verification by the client (if the CA used to generate such certificates is trusted).

With [ESNI (Encrypted Server Name Indication)](https://tools.ietf.org/html/draft-ietf-tls-esni-01) that is now getting [tested by CloudFlare and Mozilla](https://blog.cloudflare.com/esni/), the client sends the server name encrypted so pixel-srv would be unable to generate a matching certificate.

While the connection will ultimately be blocked, the browser will attempt to establish such connections until it ultimately fails.

What would be great is if for blocked domains, there could be an option to also block the corresponding ESNI record. Right now this could mean answering with NXDOMAIN to _esni.blocked.domain.
It is probably safe enough to enable by default.

**Steps to reproduce:**
- Block encryptedsni.com
- Query type=TXT _esni.encryptedsni.com and observe a response

**Additional Information:**
According to [Mozilla bug 1473736](https://bugzilla.mozilla.org/show_bug.cgi?id=1473736), Firefox nightly 64.0a1 / 20180923100316 and newer is supposed to include changeset [52ee9ddf5060](https://hg.mozilla.org/integration/mozilla-inbound/rev/52ee9ddf5060) which adds support for esni. There is a new setting `network.security.esni.enabled` in `about:config`, but I currently can't get Firefox to perform ESNI.
Until then it's hard to see what the actual browser behavior is when encountering redirected traffic that has ESNI enabled. The spec implies that the browser should not fallback to send the SNI plaintext, but it's entirely possible they might do so at the beginning (or until the specs forbids it entirely).

**Comment by DL6ER** [comment]
> There is a new setting `network.security.esni.enabled` in `about:config`

I don't expect this new Firefox "feature" to have a big influence as

1. the number of users installing `pixelsrv-tls` is rather small (assumption), and
2. the feature can apparently (fairly simple) be disabled through `about:config`

On the contrary, I see a number of issues with this as, when we would include an `NXDOMAIN` for each blocked domain, this would effectively double the memory costs. If we'd scan domains for a preceding `_esni`, then this could maybe work, but you can already implement such a thing with regex filtering (`^_esni\.`).

If you think we need further support for this, please open a Feature Request ticket on [Discourse](https://discourse.pi-hole.net/c/feature-requests) where feature requests can be voted for by the community. Github is not the place to discuss feature requests. For fairness, we contrast the number of votes on a feature request to the amount of work to implement it.

**Comment by mhofman** [comment]
> I don't expect this new Firefox "feature" to have a big influence as
> 
> 1. the number of users installing `pixelsrv-tls` is rather small (assumption), and
> 2. the feature can apparently (fairly simple) be disabled through `about:config`
> 
Well right now it's more of a field trial and something that needs to be manually enabled, but in the future it will be a feature enabled by default. Safari has also committed to support this, and has an experimental implementation.

Asking users to disable a security feature of their browser is not the right way to go IMO.

Indeed, users combining pixelsrv-tls with Pi-Hole is probably rather small for now.
However the BLOCKINGMODE=IP that enables this is fairly new to Pi-Hole. pixelserv-tls is also used a lot with other solutions based on dnsmasq. At the end of the day FTLDNS is dnsmasq with improved stats and blocking management. I'm just advocating making it even better and more compatible at blocking.

> On the contrary, I see a number of issues with this as, when we would include an `NXDOMAIN` for each blocked domain, this would effectively double the memory costs. If we'd scan domains for a preceding `_esni`, then this could maybe work, but you can already implement such a thing with regex filtering (`^_esni\.`).

Blocking all ESNI records with a regex is not an option as that would impact legitimate websites.

I'm not sure how the query lookup logic works but since FTLDNS supports patterns and regexp, I suppose not all entries from the blocklist are always loaded into dnsmasq's cache.
One possible implementation could be, when you match a query, see if it has an _esni prefix and strip it out, then continue with the regular dynamic cache injection logic if the parent domain is blocked. In the cache injection, load the IP addresses for the parent record, and an NXDOMAIN for the _esni prefix.

That way, there is no need to increase the size of the blocklist, and only queried domains have an extra NXDOMAIN injected in the cache (if we inject an IP address for the parent, as NXDOMAIN or NULL mode don't require this).

> If you think we need further support for this, please open a Feature Request ticket on [Discourse](https://discourse.pi-hole.net/c/feature-requests) where feature requests can be voted for by the community. Github is not the place to discuss feature requests. For fairness, we contrast the number of votes on a feature request to the amount of work to implement it.

Here is the feature request on Discourse: https://discourse.pi-hole.net/t/support-dropping-esni-records-for-blocked-domains/13250

**Comment by Vednier** [comment]
> 

Additional Information: According to Mozilla bug 1473736, Firefox nightly 64.0a1 / 20180923100316 and newer is supposed to include changeset 52ee9ddf5060 which adds support for esni. There is a new setting network.security.esni.enabled in about:config, but I currently can't get Firefox to perform ESNI. 
--

No, you wrong. This bug implements only "necko" (network library) part of ESNI, NSS (which handles actual cryptostuff) is still not ready for ESNI

Its even stated in patch itself :

+// Enable/disable sni encryption.
+// Currently this does not work even if the pref is true, the nss part is
+// missing.
+pref("network.security.esni.enabled", false);

**Comment by Vednier** [comment]
You actually should look into https://bugzilla.mozilla.org/show_bug.cgi?id=1488622 since NSS 3.40 is required for ESNI according to https://bugzilla.mozilla.org/show_bug.cgi?id=1495221

**Comment by mhofman** [comment]
Right, I guess I didn't look into the specifics of the patch and those other bug items didn't exist back then.
I'll try again once NSS 3.40 lands!

**Comment by DL6ER** [comment]
This discussion will be continued on [Discourse](https://discourse.pi-hole.net/t/support-dropping-esni-records-for-blocked-domains/13250).

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/support-dropping-esni-records-for-blocked-domains/13250/1

**Comment by TSlivede** [comment]
For anyone stumbling here via google: This was implemented as dns.blockESNI

Though it should by now almost certainly be removed again, see https://github.com/pi-hole/FTL/pull/2690
