### ISSUE TITLE
Upstream Names Not Resolved If Database Is Disabled

### ISSUE THREAD

**Issue by Mcat12** [pi-hole/FTL#404]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

10

---

**[BUG | ISSUE] Expected Behaviour:**
Upstream names should be resolved even if not using the database, since that feature does not depend on the database functionality.

**[BUG | ISSUE] Actual Behaviour:**
Upstream names are only resolved in the database thread, which does not run if the database is not enabled:
https://github.com/pi-hole/FTL/blob/059693a32ace9e98b9c3df065b5419f16a18e9b9/database.c#L553

The client name resolution is duplicated in `reresolveHostnames`:
https://github.com/pi-hole/FTL/blob/059693a32ace9e98b9c3df065b5419f16a18e9b9/resolve.c#L67
The upstream name resolution should be moved to this function and `resolveNewClients` should be deleted, since `reresolveHostnames` is called from the GC thread and will run even if the database is disabled. The functionality of resolving only new clients/upstreams should be kept as a flag to the function.
https://github.com/pi-hole/FTL/blob/059693a32ace9e98b9c3df065b5419f16a18e9b9/gc.c#L174

**[BUG | ISSUE] Steps to reproduce:**

Precondition: FTL is set to use an upstream with a resolvable name, and there exists at least one client with a resolvable name.
- Stop FTL
- Disable the database by adding `DBFILE=` to the config file at `/etc/pihole/pihole-FTL.conf`
- Start FTL
- Make queries against FTL from at least one client with a resolvable name.
- After waiting for at least one hour (GC runs every hour), the upstream names should still remain unresolved but client names should be resolved. This can be verified by checking the web interface.

**Log file output [if available]**

N/A

**Device specifics**

Hardware Type: Tinkerboard
OS: Armbian 5.60 (Ubuntu 16.04.5 LTS)

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
I agree that the current implementation is suboptimal. Currently, we utilize the fact that the database thread is run (typically) every minute whereas the GC thread runs on every hour. I will work on an alternative that will (most likely):

- Remove the existing routines in favour of a new encompassing name resolving routine
- Add a new thread (with a fixed run interval) that will take care of this job

By this, the internal name resolution becomes independent of external settings such as the GC or DB intervals. The new thread will cause no additional load as it will be mostly idling and only work once a minute.
