### ISSUE TITLE
Mishandling host-record entries in /etc/dnsmasq.d/*conf files

### ISSUE THREAD

**Issue by mjaustin2** [pi-hole/FTL#409]
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:** 

2
---

**[BUG | ISSUE] Expected Behaviour:**

I could see three potential "expected" behaviors:

1. _host-record_ entries in /etc/dnsmasq.d/*conf are not listed in the "Static DHCP leases configuration" section of the DHCP configuration UI.

1. _host-record_ entries in /etc/dnsmasq.d/*conf omit the delete button in the UI.

1. Configuration of _host-records_ are managed via a separate UI widget.

I use the _host-records_ in an /etc/dnsmasq.d/*conf to handle non-DHCP hosts that should still be resolvable. This keeps the configurations in one place, removes the need to modify the /etc/hosts, and can be used to fix some weirdness around resolving the host that dnsmasq runs on.

**[BUG | ISSUE] Actual Behaviour:**

The _host-record_ entries for non-DHCP hosts are displayed in "Static DHCP leases configuration" section of the DHCP configuration UI, along with a delete button. Additionally, because _host-records_ follow a different format that allows multiple hostnames, the _dhcp-host_ entries are not displayed in their entirety.

I haven't tried deleting one of them, because I didn't want to cause any additional problems.

**[BUG | ISSUE] Steps to reproduce:**

1. Create _/etc/dnsmasq.d/05-static-hosts.conf_
1. Add the following lines to _/etc/dnsmasq.d/05-static-hosts.conf_
```
host-record=utopia-planitia,utopia-planitia.lan,192.168.1.1,900
host-record=enterprise,enterprise.lan,192.168.1.2,900
host-record=voyager,voyager.lan,192.168.1.3,900
host-record=uss-reliant,uss-reliant.lan,192.168.1.10,900
host-record=uss-defiant,uss-defiant.lan,192.168.1.11,900
host-record=pihole,pihole.lan,192.168.1.53,900
```
3. Restart pihole-FTL
```
systemctl restart pihole-FTL.service
```
4. Load Settings->DHCP in the Web UI
5. Observe _host-records_ entries appear in the "Static DHCP leases configuration" section

**Log file output [if available]**

`N/A`

**Device specifics**

Hardware Type: rPi
OS: Raspbian GNU/Linux 9.0 (stretch)

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by mjaustin2** [comment]
That's completely fair. I didn't intend to impose my personal requirements on the project. I just thought you guys should be aware since the UI is selective exposing the underlying functionality. And as an added bonus, I got to Star Trek theme my example, per the _contributors guide_. Thanks!

**Comment by DL6ER** [comment]
Thanks for your comments, they are appreciated and will not remain unheard. We're currently working on a new API for a future version of Pi-hole which is a bit better structured. One of the major problems is that Pi-hole grew organically into all directions from an initially small set of bash scripts into a rather extensive DNS suite. We're at the point were rethinking the implementation of everything will lead to better approaches that will not suffer from the issues like the one you described.
