### ISSUE TITLE
Broken: Fix for regex filters + privacy level > 0

### ISSUE THREAD

**Issue by rso42** [pi-hole/FTL#414]
Looks like this fix does not work anymore:
https://github.com/pi-hole/FTL/pull/331

I can reproduce this behavior with the latest version of Pi Hole on different machines.

**Comment by DL6ER** [comment]
Please fill out the entire issue template and re-open the issue afterwards.

It is unlikely that you are affected by the same bug but we can look together at your regex and the domains you expected to be blocked and find a solution.

**Comment by rso42** [comment]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [o] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**
2
I understand the functionality of FTL/dnsmasq/lighttp and know how to configure/tune Pi-Hole very well.

---

**[BUG | ISSUE] Expected Behaviour:**
Pi-Hole should block domains matching a wildcard/regex filter and resolve to 0.0.0.0


**[BUG | ISSUE] Actual Behaviour:**
- Sometimes it does not block at all.
- Sometimes it blocks the first match dc5.s240.meetrics.net, but then no other matches like dc6.s240.meetrics.net, dc7.s240.meetrics.net anymore.

**[BUG | ISSUE] Steps to reproduce:**
- Set privacy level to something > 0.
- Add wildcard domain or regex filter to blacklist (doesn't make any difference if by command line, web interface or manually editing the filter file). Example: (^|\.)meetrics\.net$
- clear DNS cache on client.
- nslookup from a client using Pi-Hole as DNS server should now block both dc5.s240.meetrics.net and  dc6.s240.meetrics.net.
- But it does not.
- Sometimes it blocks the first match dc5.s240.meetrics.net, but then no other matches like dc6.s240.meetrics.net, dc7.s240.meetrics.net anymore.
- If privacy level is set to 0, wildcard/regex filter works as expected at once.
- Can be reproduced under different environments, with every fresh install, with just one wildcard/regex filter added.
- Can be reproduces with and without unbound installed.

**Log file output [if available]**

**Device specifics**
Server 1: rPi 3B+ with Raspbian Strecht lite
Server 2: VPS with Ubuntu 18.04 LTS

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

Please let me know, if/how I can help to solve this.

**Comment by DL6ER** [comment]
Could you use regex debug mode and see if matches are reported with privacylevel = 0 and with privacylevel > 0 ?

See https://docs.pi-hole.net/ftldns/regex/overview/#pi-hole-regex-debugging-mode

**Comment by rso42** [comment]
Thank you DL6ER for taking care.

I did turn on debug and here is what I found out:

**Test 1** 
- privacy level = 0
- on client: nslookup nslookup dc5.s240.meetrics.net, nslookup dc6.s240.meetrics.net and nslookup dc7.s240.meetrics.net -> all resolved to 0.0.0.0
- pihole-FTL.log shows 3 entries:
[2018-11-07 17:48:51.032] DEBUG: Regex in line 1 "(^|\.)meetrics\.net$" matches "dc5.s240.meetrics.net"
[2018-11-07 17:48:55.673] DEBUG: Regex in line 1 "(^|\.)meetrics\.net$" matches "dc6.s240.meetrics.net"
[2018-11-07 17:48:59.139] DEBUG: Regex in line 1 "(^|\.)meetrics\.net$" matches "dc7.s240.meetrics.net"

**Test 2** 
- privacy level changed to 3 (over web interface)
- on client: nslookup nslookup dc5.s240.meetrics.net, nslookup dc6.s240.meetrics.net and nslookup dc7.s240.meetrics.net -> all resolved to 0.0.0.0
- pihole-FTL.log shows 0 entries

**Test 3**
- privacy level still set to 3 (verified by looking into config file)
- sudo service pihole-FTL restart
- on client: nslookup nslookup dc5.s240.meetrics.net, nslookup dc6.s240.meetrics.net and nslookup dc7.s240.meetrics.net -> first lookup resolved to 0.0.0.0, next two lookups were not blocked and resolved to real IPs!
- pihole-FTL.log only shows 1 entry:
[2018-11-07 17:51:49.578] DEBUG: Regex in line 1 "(^|\.)meetrics\.net$" matches "dc5.s240.meetrics.net"
- I checked twice: nslookup on client did use Pi-Hole server correctly.

**Comment by DL6ER** [comment]
If the first match is blocked and subsequent not, then there might be a caching issue. Background information: Due to performance reasons, we check each domain only once against the regex filters and store the blocked domain in the DNS cache afterwards. I'm not yet entirely sure what we're looking for as I cannot reproduce it, but I'm sure that we will find it at some point.

What is the output of
```
echo ">cacheinfo" | nc 127.0.0.1 4711
```
?

You tested here with privacy level 3, does it also happen with level 1 or 2? Initially, you said > 0 so I assume  the answer is Yes, but I think I should ask again just to be sure.

**Comment by rso42** [comment]
the output of 'echo ">cacheinfo" | nc 127.0.0.1 4711' is:
cache-size: 10000
cache-live-freed: 0
cache-inserted: 3282
---EOM---

I hoped you would be able to reproduce this bug.
As I can absolutely control the effect:

- I set privacy level to 1, 2 or 3 in pihole-FTL.conf.
- I restart the pihole-FTL service.
- nslookups from a client won't get filtered by wildcard/regex filters. (ok, sometimes the first nslookup gets blocked, but the following not.)

- Then I set  privacy level to 0 in pihole-FTL.conf and restart pihole-FTL service.
- nslookups get filtered correctly.

- Also if I use 'dig' directly on the server I get the same effect.


I don't want to waste your time.
I know it's hard to fix a bug that can't be reproduced.
Is there anything I can do to make it easier for you?
I could setup a server that I can give you access to so you can reproduce an check the effect yourself, for example.

**Comment by DL6ER** [comment]
Your cache info looks fine. A problem might be that I tried to reproduce the bug with the release candidate for v4.1 which might have already fixed this behavior. I'll try with with v4.0 version once I'm back home today.

You could also test the release candidate if you like:
```
sudo pihole checkout ftl release/4.1
```

**Comment by rso42** [comment]
I just checked with release candidate 4.1.
I can reproduce the same bug with this version, too.

**Comment by DL6ER** [comment]
Okay, now comes the time where it seems mandatory to share a server for debugging. I can generate a VM or you offered to do it. I don't mind either way. Do you have an account on https://discourse.pi-hole.net ? Exchanging the credentials via PM there seems to be the best option for this.

**Comment by rso42** [comment]
Okay.
I'm on on discourse.pi-hole.net now.
Please PM me and I'll answer with credentials for a prepared server for debugging.
