### ISSUE TITLE
BLOCKINGMODE=MODE_NX doesn't return a SOA record

### ISSUE THREAD

**Issue by Belphemur** [pi-hole/FTL#424]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

1

---

**[BUG | ISSUE] Expected Behaviour:**
Using BLOCKINGMODE=NXDOMAIN should return a DNS answer with a SOA in authority.
This way, the TTL given by the SOA can be used to cache the negative answer and reduce the number of requests that the DNS server receive.

**[BUG | ISSUE] Actual Behaviour:**
No SOA present.

**[BUG | ISSUE] Steps to reproduce:**

- Set blocking mode to MODE_NX
- Do a request on a blocked domain (with dig/drill)
- No Authority section

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
I'm not aware of a solution for this that does not involve a lot of coding. If you are able to describe how you would do this with `dnsmasq`, then we can talk about it. Further, `NXDOMAIN` is not the recommended blocking mode and is just offered for users that want to play around with this. Our documentation clearly states that this implementation of `NXDOMAIN` is likely not cached and, hence, the queries are often retried.

The `NULL` blocking mode itself is returning the expected answer. You are asking for an additional `SOA` record to be transmitted. Hence:
> Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net), as mentioned in our [Issue Templates](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md).

Thank you for your understanding.

**Comment by Belphemur** [comment]
I could try, but do you have any idea in which part of the code dnsmasq manage the return of a normal NXDOMAIN? 

Because after testing, if the domain.tld exist, dnsmasq will return the SOA. 

I guess it would be possible to reproduce the same behavior. 

________________________________

**Comment by DL6ER** [comment]
> do you have any idea in which part of the code dnsmasq manage the return of a normal NXDOMAIN?

Yes, the code is in `rfc1035.c:answer_request()`.

More specifically, it is here:
https://github.com/pi-hole/FTL/blob/4667efc31802e55e67d02b1c64e471839ebbd027/dnsmasq/rfc1035.c#L1975-L1976

Note that, although this reference points to a specific commit, this is merely to ensure that the linked content always stays the same. It is also worth to point out that we do not accept changes for the source code files of `dnsmasq`. This is done to ensure full compatibility with future `dnsmasq` releases. All modifications need to be submitted to the original `dnsmasq` repository and we automatically incorporate them when a new release of `dnsmasq` is rolled out.
