### ISSUE TITLE
[Bug] Can't Update FTL to 4.1

### ISSUE THREAD

**Issue by zero77** [pi-hole/FTL#434]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

1

---

**[BUG | ISSUE] Expected Behaviour:**
After running sudo pihole -up FTL should be running 4.1

**[BUG | ISSUE] Actual Behaviour:**
An update is found for FTL but it will not install and ends with "Unable to complete update, please contact Pi-hole Support".

**[BUG | ISSUE] Steps to reproduce:**

- Run sudo pihole -up
- Then an error is displayed.

**Log file output [if available]**

`output`

**Device specifics**

Hardware Type: rPi, VPS, etc
OS: Ubuntu 18.04

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Puredeathnight** [comment]
I am having issues aswell, But I am getting a 404 Error. I copied the url to my chrome browser and had a 404 error aswell. https://github.com/pi-hole/FTL/releases/download/v4.1/

**Comment by redant2u** [comment]
I'm having a issue as well with the update.
 [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/FTL/releases/download/v4.1/pihole-FTL-arm-linux-gnueabihf not found

**Comment by DL6ER** [comment]
@redant2u Please try again. The URL you posted is valid.
@Puredeathnight @zero77 Please generate a debug token for us to be able to help you.

**Comment by code-in-progress** [comment]
I'm also having the same issue.

![image](https://user-images.githubusercontent.com/33837776/50087263-76871b00-01cd-11e9-8ec8-479bb1e1c630.png)

There are no log entries that show an error in /var/log/pihole (nor any in /var/log/pihole.log).

**Comment by code-in-progress** [comment]
@PromoFaux All stock. 

I was able to make a bit of progress though. I ran apt update && apt upgrade -y and then pihole -r. After doing that, I was able to get web and core to update. FTL still won't update though.

**Comment by PromoFaux** [comment]
If you did that since the last debug token, can you run another please?

**Comment by code-in-progress** [comment]
@PromoFaux Done: b7j9s09si0

Thanks for looking into this. Very much appreciated.

**Comment by code-in-progress** [comment]
Crap. I didn't even see that. LOL I have no idea how that happened. When I ran pihole -up earlier, it was showing FTL as still requiring an update. 

Sorry about that. Problem solved by gremlins. I'm chalking it up to gremlins. :)

Thanks @PromoFaux

**Comment by DL6ER** [comment]
Closing as there was no response from the original posters. Feel free to re-open this issue if the error persists.

**Comment by zero77** [comment]
@DL6ER 
Sorry for the very late reply.
Debug Token: xlkse6p3vb

**Comment by Mcat12** [comment]
@zero77 What is the full output of the `pihole -up` command?

**Comment by zero77** [comment]
@Mcat12 
Output:
https://pastebin.com/McF35qkG

**Comment by Mcat12** [comment]
>   [i] Checking for lighttpd (will be installed)

It failed to install lighttpd for some reason. Try installing that package manually.

**Comment by zero77** [comment]
@Mcat12 
I am using pi-hole with apache, i think that's why lighttpd isn't installed.

**Comment by Mcat12** [comment]
The installer won't continue until it is able to install lighttpd, so you can install it and then remove it or disable it after the update. The new web interface and API will remove the need for an external web server, so this should not be a problem when that is released.

**Comment by zero77** [comment]
Ok thanks, i will try installing lighttpd and disabling it after.

> The new web interface and API will remove the need for an external web server

What version is that.

**Comment by Mcat12** [comment]
The new web interface and API have not yet been released.

**Comment by zero77** [comment]
It seems to have changed to this error after installing lighttpd.

https://pastebin.com/QBWZq066

**Comment by Mcat12** [comment]
Don't disable lighttpd until after the update, if you already did that. If not, then try manually enabling lighttpd via `systemctl enable lighttpd`

**Comment by zero77** [comment]
@Mcat12 
Thanks

**Comment by redant2u** [comment]
Hi All
i have tried again today to update my pihole and again getting an error on the FTL update. have copy the entire screen from putty to add it to my reply and hope someone can tell me what I'm doing wrong...
Can try "sudo pihole -up" or just "pihole-up" nothing update the FTL.
Even the complete command "curl -sSL https://install.pi-hole.net | bash"

If I'm doing something stupid please help me correct myself.

****This is the error:
Error: URL https://github.com/pi-hole/FTL/releases/download/v4.1.2/pihole-FTL-arm-linux-gnueabihf not found_

This below is everything from trying to update FTL.


login as: pi
pi@192.168.0.6's password:
Linux KidsPi 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Dec 31 16:48:52 2018 from 192.168.0.119
pi@KidsPi:~ $ sudo pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Existing PHP installation detected : PHP version 7.0.30-0+deb9u1
  [i] Performing unattended setup, no whiptail dialogs will be displayed
  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... 138 updates available
  [i] It is recommended to update your OS after installing the Pi-hole!

  [i] Installer Dependency checks...
  [✓] Checking for apt-utils
  [✓] Checking for dialog
  [✓] Checking for debconf
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for bc
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for resolvconf
  [✓] Checking for lighttpd
  [✓] Checking for php7.0-common
  [✓] Checking for php7.0-cgi
  [✓] Checking for php7.0-sqlite3

  [✓] Enabling lighttpd service to start on reboot...
  [✓] Checking for user 'pihole'
  [✓] Installing scripts from /etc/.pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf

  [i] Installing blocking page...
  [✓] Creating directory for blocking page, and copying files
  [✗] Backing up index.lighttpd.html
      No default index.lighttpd.html file found... not backing up

  [✓] Installing sudoer file

  [✓] Installing latest Cron script

  [✓] Installing latest logrotate script

  [i] FTL Checks...

  [✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection refused
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/FTL/releases/download/v4.1.2/pihole-FTL-arm-linux-gnueabihf not found
  [✗] FTL Engine not installed
  [✓] man pages installed and database updated
  [i] Testing if systemd-resolved is enabled
  [i] Systemd-resolved is not enabled
  [✓] Starting lighttpd service...
  [✓] Enabling lighttpd service to start on reboot...
  [i] Restarting services...
  [✓] Enabling pihole-FTL service to start on reboot...
  [✓] Starting pihole-FTL service...
  [✓] Deleting existing list cache
  [i] Pi-hole blocking is enabled
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [i] Target: raw.githubusercontent.com (hosts)
  [✓] Status: Retrieval successful

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [✓] Status: Retrieval successful

  [i] Target: sysctl.org (hosts)
  [✓] Status: Retrieval successful

  [i] Target: zeustracker.abuse.ch (blocklist.php?download=domainblocklist)
  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_ad.txt)
  [✓] Status: Retrieval successful

  [i] Target: hosts-file.net (ad_servers.txt)
  [✓] Status: Retrieval successful

  [✓] Consolidating blocklists
  [✓] Extracting domains from blocklists
  [i] Number of domains being pulled in by gravity: 159646
  [✓] Removing duplicate domains
  [i] Number of unique domains trapped in the Event Horizon: 136428
  [i] Number of whitelisted domains: 13
  [i] Number of blacklisted domains: 10
  [i] Number of regex filters: 62
  [✓] Parsing domains into hosts format
  [✓] Cleaning up stray matter

  [✓] Force-reloading DNS service
  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled

  [i] The install log is located at: /etc/pihole/install.log
Update Complete!

  Current Pi-hole version is v4.1.1
  Current AdminLTE version is v4.1.1
  Current FTL version is v4.0
pi@KidsPi:~ $ login as: pi
login: Cannot possibly work without effective root
pi@KidsPi:~ $ pi@192.168.0.6's password:
> Linux KidsPi 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l
>
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
>
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
> Last login: Mon Dec 31 16:48:52 2018 from 192.168.0.119
> pi@KidsPi:~ $ sudo pihole -up
>   [i] Checking for updates...
>   [i] Pi-hole Core:     up to date
>   [i] Web Interface:    up to date
>   [i] FTL:              update available
>
>   [i] FTL out of date, it will be updated by the installer.
>
>   [✓] Root user check
>
>         .;;,.
>         .ccccc:,.
>          :cccclll:.      ..,,
>           :ccccclll.   ;ooodc
>            'ccll:;ll .oooodc
-bash: pi@192.168.0.6s password:
Linux KidsPi 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Dec 31 16:48:52 2018 from 192.168.0.119
pi@KidsPi:~ $ sudo pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           ccll:: No such file or directory
-bash: ll: command not found
pi@KidsPi:~ $              .;cll.;;looo:.
-bash: syntax error near unexpected token `;;'
pi@KidsPi:~ $                  .. ','.
-bash: ..: command not found
pi@KidsPi:~ $                 .',,,,,,'.
-bash: .,,,,,,.: command not found
pi@KidsPi:~ $               .',,,,,,,,,,.
>             .',,,,,,,,,,,,....
-bash: $'.,,,,,,,,,,.\n            .,,,,,,,,,,,,....': command not found
pi@KidsPi:~ $           ....''',,,,,,,'.......
-bash: ....,,,,,,,.......: command not found
pi@KidsPi:~ $         .........  ....  .........
-bash: .........: command not found
pi@KidsPi:~ $         ..........      ..........
-bash: ..........: command not found
pi@KidsPi:~ $         ..........      ..........
-bash: ..........: command not found
pi@KidsPi:~ $         .........  ....  .........
-bash: .........: command not found
pi@KidsPi:~ $           ........,,,,,,,'......
>             ....',,,,,,,,,,,,.
-bash: $'........,,,,,,,......\n            ....,,,,,,,,,,,,.': command not found
pi@KidsPi:~ $                .',,,,,,,,,'.
-bash: .,,,,,,,,,.: command not found
pi@KidsPi:~ $                 .',,,,,,'.
-bash: .,,,,,,.: command not found
pi@KidsPi:~ $                   ..'''.
>
>   [i] Existing PHP installation detected : PHP version 7.0.30-0+deb9u1
>   [i] Performing unattended setup, no whiptail dialogs will be displayed
>   [✓] Disk space check
>   [✓] Update local cache of available packages
>
>   [✓] Checking apt-get for upgraded packages... 138 updates available
>   [i] It is recommended to update your OS after installing the Pi-hole!
>
>   [i] Installer Dependency checks...
>   [✓] Checking for apt-utils
>   [✓] Checking for dialog
>   [✓] Checking for debconf
>   [✓] Checking for dhcpcd5
>   [✓] Checking for git
>   [✓] Checking for iproute2
>   [✓] Checking for whiptail
>
>   [i] Performing reconfiguration, skipping download of local repos
>   [✓] Resetting repository within /etc/.pihole...
>   [✓] Resetting repository within /var/www/html/admin...
>   [i] Main Dependency checks...
>   [✓] Checking for bc
>   [✓] Checking for cron
>   [✓] Checking for curl
>   [✓] Checking for dnsutils
>   [✓] Checking for iputils-ping
>   [✓] Checking for lsof
>   [✓] Checking for netcat
>   [✓] Checking for psmisc
>   [✓] Checking for sudo
>   [✓] Checking for unzip
>   [✓] Checking for wget
>   [✓] Checking for idn2
>   [✓] Checking for sqlite3
>   [✓] Checking for libcap2-bin
>   [✓] Checking for dns-root-data
>   [✓] Checking for resolvconf
>   [✓] Checking for lighttpd
>   [✓] Checking for php7.0-common
>   [✓] Checking for php7.0-cgi
>   [✓] Checking for php7.0-sqlite3
>
>   [✓] Enabling lighttpd service to start on reboot...
>   [✓] Checking for user 'pihole'
>   [✓] Installing scripts from /etc/.pihole
>
>   [i] Installing configs from /etc/.pihole...
>   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
>   [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
>
>   [i] Installing blocking page...
>   [✓] Creating directory for blocking page, and copying files
>   [✗] Backing up index.lighttpd.html
>       No default index.lighttpd.html file found... not backing up
>
>   [✓] Installing sudoer file
>
>   [✓] Installing latest Cron script
>
>   [✓] Installing latest logrotate script
>
>   [i] FTL Checks...
>
>   [✓] Detected ARM-hf architecture (armv7+)
>   [i] Checking for existing FTL binary...
>   [i] Downloading and Installing FTL...curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection refused
>   [✗] Downloading and Installing FTL
>   Error: URL https://github.com/pi-hole/FTL/releases/download/v4.1.2/pihole-FTL-arm-linux-gnueabihf not found
>   [✗] FTL Engine not installed
>   [✓] man pages installed and database updated
>   [i] Testing if systemd-resolved is enabled
>   [i] Systemd-resolved is not enabled
>   [✓] Starting lighttpd service...
>   [✓] Enabling lighttpd service to start on reboot...
>   [i] Restarting services...
>   [✓] Enabling pihole-FTL service to start on reboot...
>   [✓] Starting pihole-FTL service...
>   [✓] Deleting existing list cache
>   [i] Pi-hole blocking is enabled
>   [i] Neutrino emissions detected...
>   [✓] Pulling blocklist source list into range
>
>   [i] Target: raw.githubusercontent.com (hosts)
>   [✓] Status: Retrieval successful
>
>   [i] Target: mirror1.malwaredomains.com (justdomains)
>   [✓] Status: Retrieval successful
>
>   [i] Target: sysctl.org (hosts)
>   [✓] Status: Retrieval successful
>
>   [i] Target: zeustracker.abuse.ch (blocklist.php?download=domainblocklist)
>   [✓] Status: Retrieval successful
>
>   [i] Target: s3.amazonaws.com (simple_tracking.txt)
>   [✓] Status: Retrieval successful
>
>   [i] Target: s3.amazonaws.com (simple_ad.txt)
>   [✓] Status: Retrieval successful
>
>   [i] Target: hosts-file.net (ad_servers.txt)
>   [✓] Status: Retrieval successful
>
>   [✓] Consolidating blocklists
>   [✓] Extracting domains from blocklists
>   [i] Number of domains being pulled in by gravity: 159646
>   [✓] Removing duplicate domains
>   [i] Number of unique domains trapped in the Event Horizon: 136428
>   [i] Number of whitelisted domains: 13
>   [i] Number of blacklisted domains: 10
>   [i] Number of regex filters: 62
>   [✓] Parsing domains into hosts format
>   [✓] Cleaning up stray matter
>
>   [✓] Force-reloading DNS service
>   [✓] DNS service is running
>   [✓] Pi-hole blocking is Enabled
>
>   [i] The install log is located at: /etc/pihole/install.log
> Update Complete!
>
>   Current Pi-hole version is v4.1.1
>   Current AdminLTE version is v4.1.1
>   Current FTL version is v4.0
> pi@KidsPi:~ $

**Comment by dschaper** [comment]
@redant2u Open a new issue at https://github.com/pi-hole/pi-hole and fill out the issue template. This issue is not related to your current problem as is closed.
