### ISSUE TITLE
pihole-FTL Compiled for ARM EABI5 Devices

### ISSUE THREAD

**Issue by backXslash** [pi-hole/FTL#436]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1_

---

**[BUG | ISSUE] Expected Behaviour:**
The pihole installation script installs the correct architecture binary of pihole-FTL for ARM EABI5 devices

**[BUG | ISSUE] Actual Behaviour:**
The pihole installation script installs the wrong architecture binary of pihole-FTL for ARM EABI5 devices

**[BUG | ISSUE] Steps to reproduce:**

1: Run the install script on an ARM EABI5 device
2: Be sad when it fails

**Device specifics**

Hardware Type: PogoPlug v4 "Kirkwood"
OS: Debian

I've compiled pihole-FTL 4.1 for use with ARM EABI5 devices. Specifically, I compiled it in situ on my PogoPlug v4 that's running Debian Stretch.

I'd like to add it to the available downloads, in case anyone else wants / needs it

[pihole-FTL.arm.eabi5.zip](https://github.com/pi-hole/FTL/files/2682373/pihole-FTL.arm.eabi5.zip)

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Thank you for the submission, we appreciate the effort and time. Unfortunately we are unable to accept a compiled binary from the community for distribution. The audit history and chain of custody of the code has been broken and for security purposes this makes the submission unusable. I hope you can understand our position.
