### ISSUE TITLE
Why blocked this domen tracker.grepler.com?

### ISSUE THREAD

**Issue by spawnlmg** [pi-hole/FTL#441]
Why blocked this domen tracker.grepler.com?
All filters disable.
![image](https://user-images.githubusercontent.com/23347625/50293373-1964c100-047c-11e9-88a6-569c479eebad.png)
![image](https://user-images.githubusercontent.com/23347625/50293435-3c8f7080-047c-11e9-990b-f1bd9f77da0c.png)
![image](https://user-images.githubusercontent.com/23347625/50293467-5335c780-047c-11e9-833d-e789dd881a26.png)
![image](https://user-images.githubusercontent.com/23347625/50293868-3fd72c00-047d-11e9-9c75-957623ee9979.png)

**Comment by Mcat12** [comment]
We do not control the block lists. Use `pihole -q` or the "Query Lists" feature on the web interface to see what block lists are causing that domain to get blocked.

**Comment by r00t0vi4** [comment]
tracker.grepler.com was blocked by downstream DNS server.
