### ISSUE TITLE
Status of conntrack functionality

### ISSUE THREAD

**Issue by rgriebl** [pi-hole/FTL#458]
What is the status of the FTLDNS-conntrack branch? I just ran into the problem that pihole stopped working for me after updating to 4.x because I have always been using the conntrack functionality that's readily available in Debian's dnsmasq package.

According to https://discourse.pi-hole.net/t/ftdns-conntrack/8266/2 (which happened 10 months ago), the CI would "just" need to have libnetfilter_conntrack installed.

**Comment by DL6ER** [comment]
Note that you will also have to install `libnetfilter-conntrack-dev` in addition to what is mentioned on the "Installing from source" page

**Comment by DL6ER** [comment]
Closing as no reaction for nearly a month. If you want to continue this discussion, our Discourse forum is more suitable.
