### ISSUE TITLE
dnsmasq fails to start on raspbian with dnsmasq 2.7.6

### ISSUE THREAD

**Issue by gotdibbs** [pi-hole/FTL#459]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

dnsmasq starts and DNS resolution is available.

**Actual behaviour:**

dnsmasq fails to start and DNS resolution is unavailable.

**Steps to reproduce:**

Switch to development branch and update.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`5n64o3tq1c`

**Troubleshooting undertaken, and/or other relevant information:**

I updated to the development branch to attempt to resolve an unrelated issue and found dnsmasq subsequently stayed down. The error received is below:

> Jan 09 20:28:01 marida dnsmasq[17967]: dnsmasq: bad option at line 47 of /etc/dnsmasq.d/01-pihole.conf
> Jan 09 20:28:01 marida systemd[1]: dnsmasq.service: Control process exited, code=exited status=1
> Jan 09 20:28:01 marida systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.

I had to disable FTL, enable dnsmasq, switch back to `ftl master`, then toggle dnsmasq/FTL again for things to work.

It looks like this is coming from #2570 if I had to guess. I am on dnsmasq 2.7.6 (which raspbian stretch reports as "latest"), and `dhcp-name-match` wasn't released until ~2.8, but I thought FTL was supposed to replace dnsmasq?

I am unsure if this breaking change was intended or not, but felt it warranted a report as I don't see documentation to the contrary.

**Comment by jfb-pihole** [comment]
With this version of Pi-Hole, dnsmasq does not run as a separate process.  The dnsmasq code is embedded in pihole-FTL.  What are the contents of /etc/dnsmasq.d/o1-pihole.conf (specifically line 47)?

**Comment by gotdibbs** [comment]
@jfb-pihole the contents are exactly what is in the PR I mentioned above. The update to the dev branch overwrote my config [this](https://github.com/pi-hole/pi-hole/blob/04fd296ffe8ea2411dc158c3a6f12cd6f48cc1be/advanced/01-pihole.conf). Line 47 contains the `dhcp-name-match` as I tried to imply at the bottom of my post. Thanks for the follow up!

**Comment by DL6ER** [comment]
Closing as resolved. It was a typo.

**Comment by gotdibbs** [comment]
@DL6ER Thanks!!

**Comment by gotdibbs** [comment]
@DL6ER this appears to continue to be an issue for me. Whenever I update, 01-pihole.conf is overwritten and `dhcp-name-match` is added back. Whenever that is enabled I receive the error above again that implies my version of dnsmasq doesn't support that option. Thoughts? Thanks!!

**Comment by Mcat12** [comment]
This is not a breaking change, because FTL ships v2.80. We can not support users using any version of dnsmasq. FTL embeds dnsmasq, so you do not need the standalone one. You are using the development version of core and web, but did not update FTL to development.

**Comment by gotdibbs** [comment]
@Mcat12 it was before the issue, but I reverted it because of the issue, and now I'm experiencing this issue while not on development. So I'm trying to understand what the path to resolution is for me. Can you help me understand? Are you saying I need to have all components on dev or none? Like having core or web on dev is somehow bringing in this FTL config option early?

**Comment by Mcat12** [comment]
According to your debug log, you have core and web on the development branches while FTL is on master.
```
*** [ DIAGNOSING ]: Core version
[i] Core: v4.1.1 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Branch: development (https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#checkout)
[i] Commit: v4.1.1-31-gf7ca74c

*** [ DIAGNOSING ]: Web version
[i] Web: v4.1 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Branch: devel (https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#checkout)
[i] Commit: v4.1-35-ga2615c8c

*** [ DIAGNOSING ]: FTL version
[✓] FTL: v4.1.2
```

To avoid possible errors like the one you found, the branches of all three components must match. If you want to stay on development, update FTL to development. If you want to go back to master, downgrade core and web to master.

**Comment by gotdibbs** [comment]
@mcat12 ah that makes sense, switched the rest of the components over and no more error. Thanks!!
