### ISSUE TITLE
pihole-FTL wont start after pihole -up

### ISSUE THREAD

**Issue by 7oxicshadow** [pi-hole/FTL#491]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_{1}_

---

**[BUG | ISSUE] Expected Behaviour:**
FTL should start

**[BUG | ISSUE] Actual Behaviour:**
FTL fails to start with:
dnsmasq: bad option at line 47 of /etc/dnsmasq.d/01-pihole.conf

line 47 of 01-pihole.conf is:
dhcp-name-match=set:wpad-ignore,wpad

**[BUG | ISSUE] Steps to reproduce:**
Update pihole
FTL wont start

**Device specifics**

Hardware Type: rPi
OS: raspian

**additional**
commenting out line 47 and 48 of 01-pihole.conf allows FTL to start

Pi-hole version is v4.1.1-34-g1e284f6 (Latest: v4.1.1)
AdminLTE version is v4.1-35-ga2615c8c (Latest: v4.1.1)
FTL version is v4.1.2 (Latest: v4.1.2)

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Have you tried to checkout a custom branch?

Please provide a debug token as asked in the issue template.

**Comment by 7oxicshadow** [comment]
Sorry for the late response.
I run a split network at home, each half having its own pihole server acting as separate dhcp servers.

Pihole 1 was working fine after an update.
Pihole 2 was not working after an update.

I did a side by side comparison and discovered that pihole 2 was running on the dev branch (i dont remember doing this but I must have done it a long time ago).
`pihole checkout dev`

I reverted back to the master branch and the problem lines in the 01-pihole.conf file are no longer there.
`pihole checkout master`

I will close this issue as it was a problem on the dev branch rather than the master. If you would like more information then re-open it and I will add what ever you need.

Sorry for wasting your time.

Thanks

**Comment by DL6ER** [comment]
Thanks, the issue here was that you checked out the `development` branch of https://github.com/pi-hole/pi-hole which expects also the development version of https://github.com/pi-hole/FTL

It added some keywords which are not available in `pihole-FTL` v4.1.2 (they will become available in v4.2 which is to be released soon):

https://github.com/pi-hole/pi-hole/blob/development/advanced/01-pihole.conf#L50-L53

This is known as being not a compatible configuration (Downgrading is not supported).
