### ISSUE TITLE
Internal name resolving - overwhelming PTR queries

### ISSUE THREAD

**Issue by chrisdlangton** [pi-hole/FTL#514]
It's back

https://discourse.pi-hole.net/t/lot-of-ptr-queries/8380/
https://github.com/pi-hole/FTL/pull/253Internal name resolving

![image](https://user-images.githubusercontent.com/3494633/52928462-e82d4200-3393-11e9-9d8f-e66f5c2d3930.png)

![image](https://user-images.githubusercontent.com/3494633/52928477-0430e380-3394-11e9-9620-ae42f8cc1feb.png)

**Comment by DL6ER** [comment]
I just checked this and found no code in the API that could trigger this:
- New host names are resolved once a minute
- Host names are (re)resolved every hour
- Host names are (re)resolved on user request via the `telnet` API

- Are you sure if only happens when you have the dashboard opened?
- Do you use the FTL binary provided by our build system or did you compile FTL from source? In the latter case, did you make any changes to the code?

**Comment by DL6ER** [comment]
@chrisdlangton We're about to release an FTL update today. Please also check if the issue is still there after updating as we re-organized a lot which might have helped.

**Comment by chrisdlangton** [comment]
@DL6ER humbly used 
```
git clone --depth 1 https://github.com/pi-hole/pi-hole.git Pi-hole
cd "Pi-hole/automated install/"
sudo bash basic-install.sh
```
Saw this odd data about 4 days ago and fresh installed, didn't know how it was caused then. After that fresh reinstall (using same method) 4 days ago it seemed to have stopped until last night i noticed it again.

You can see in the graph a section of time when it dipped down, that is when i closed all my browsers for a bit while i did some RAM intensive work, then it jumps back up when i leave the pi.hole dashboard open for a bit.

Honestly it is not priority now i am happy with the setup ,i'll rarely need to have the dashboard open unless i'm looking to do something specific.

Will try the update once it hits and report back.

**Comment by DL6ER** [comment]
@chrisdlangton FTL v4.2.2 has been released

**Comment by ookangzheng** [comment]
I DROP all PTR request from the client in the lab, it kinda attacks similar to ANY.

**Comment by DL6ER** [comment]
@chrisdlangton Is this still happening with FTL v4.2.3 ?

**Comment by chrisdlangton** [comment]
LGTM @DL6ER ty
