### ISSUE TITLE
Ip is reversed in PTR records

### ISSUE THREAD

**Issue by Max7641** [pi-hole/FTL#525]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---

**[BUG | ISSUE] Expected Behaviour:**

In Telnet API,The correct IP is:
192.168.31.146
192.168.31.149
192.168.31.1

**[BUG | ISSUE] Actual Behaviour:**

146.31.168.192.in-addr.arpa
149.31.168.192.in-addr.arpa
1.31.168.192.in-addr.arpa

**Log file output [if available]**

>getallqueries-client localhost (10)
1551407588 A github.com localhost 2 5 0 0
1551407589 A github-production-release-asset-2e65be.s3.amazonaws.com localhost 2 5 0 0
1551407740 A github.com localhost 2 5 0 0
1551407740 A github-production-release-asset-2e65be.s3.amazonaws.com localhost 2 5 0 0
1551407880 PTR 146.31.168.192.in-addr.arpa localhost 3 0 5 7
1551407880 PTR 149.31.168.192.in-addr.arpa localhost 3 0 5 4
1551407880 PTR 113.31.168.192.in-addr.arpa localhost 3 0 5 5
1551407880 PTR 1.31.168.192.in-addr.arpa localhost 2 0 2 184
1551407880 PTR 8.8.8.8.in-addr.arpa localhost 2 0 5 200
---EOM---

**Device specifics**

Hardware Type: rPi, VPS, etc
OS: Raspbian GNU/Linux 9 (stretch)

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
What is the issue here? PTR queries are made to be "backwards", that's how they work.
https://en.wikipedia.org/wiki/Reverse_DNS_lookup

**Comment by Max7641** [comment]
My fault, I learned...
