### ISSUE TITLE
Incorrect setcap path on Alpine Linux

### ISSUE THREAD

**Issue by DDoSolitary** [pi-hole/FTL#557]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1_

---

**[BUG | ISSUE] Expected Behaviour:**

`make install` completes successfully.

**[BUG | ISSUE] Actual Behaviour:**

`make install` fails with command not found.

**[BUG | ISSUE] Steps to reproduce:**

- `make`
- `make install`

**Log file output [if available]**

```
install -m 0755 pihole-FTL /usr/bin
/sbin/setcap CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_NET_ADMIN+eip /usr/bin/pihole-FTL
make: /sbin/setcap: Command not found
make: *** [Makefile:127: install] Error 127
```

**Device specifics**

Hardware Type: PC
OS: Alpine Linux

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DDoSolitary** [comment]
`setcap` resides in `/use/sbin/` instead on Alpine.

**Comment by DL6ER** [comment]
@DDoSolitary Please try branch `fix/setcap_path`

It offers both support for `DESTDIR` as well as dynamically determines the correct path for the `setcap` binary.

**Comment by DDoSolitary** [comment]
@DL6ER It works well, thanks.

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
