### ISSUE TITLE
FTL offline after new install on Ubuntu 18.04.2 LTS server

### ISSUE THREAD

**Issue by coderkingnoob** [pi-hole/FTL#562]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

2
---

**[BUG | ISSUE] Expected Behaviour:**
FTL should be online

**[BUG | ISSUE] Actual Behaviour:**
FTL is offline.  I installed pi-hole on a VM Ubuntu 18.04 server on synology

$ pihole -v
  Pi-hole version is Untagged (Latest: v4.2.2)
  AdminLTE version is Untagged (Latest: v4.2)
  FTL version is v4.2.3 (Latest: v4.2.3)

**[BUG | ISSUE] Steps to reproduce:**
here is the debug code

zxs2a7u9ji!

**Log file output [if available]**

sudo service pihole-FTL status
● pihole-FTL.service - LSB: pihole-FTL daemon
   Loaded: loaded (/etc/init.d/pihole-FTL; generated)
   Active: active (exited) since Mon 2019-05-06 18:23:18 EDT; 11min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1129 ExecStop=/etc/init.d/pihole-FTL stop (code=exited, status=0/SUCCESS)
  Process: 1139 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)

May 06 18:23:17 ubuntu systemd[1]: Starting LSB: pihole-FTL daemon...
May 06 18:23:17 ubuntu pihole-FTL[1139]: Not running
May 06 18:23:17 ubuntu su[1167]: Successful su for pihole by root
May 06 18:23:17 ubuntu su[1167]: + ??? root:pihole
May 06 18:23:17 ubuntu su[1167]: pam_unix(su:session): session opened for user pihole by (uid=0)
May 06 18:23:18 ubuntu pihole-FTL[1139]: dnsmasq: failed to create listening socket for 192.168.1.53: Address already in use
May 06 18:23:18 ubuntu su[1167]: pam_unix(su:session): session closed for user pihole
May 06 18:23:18 ubuntu systemd[1]: Started LSB: pihole-FTL daemon.

**Device specifics**

Hardware Type: VM on Synology
OS: Ubuntu 18.04.02

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
You have another process, probably BIND, running on port 53. Stop that process so that FTL can use the port.

**Comment by coderkingnoob** [comment]
I killed the bind process and the GUI is now showing dns and FTP are  not running error

**Comment by coderkingnoob** [comment]
I also ran the below
sudo ufw allow http
sudo ufw allow 53

**Comment by DL6ER** [comment]
You will have to (re)start the DNS service after you killed `bind`. Use
```
pihole restartdns
```

**Comment by coderkingnoob** [comment]
here is bind process

sudo lsof -i :53
COMMAND PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
named   665 bind   21u  IPv6  20685      0t0  TCP *:domain (LISTEN)
named   665 bind   22u  IPv4  20697      0t0  TCP localhost:domain (LISTEN)
named   665 bind   23u  IPv4  20700      0t0  TCP 192.168.1.53:domain (LISTEN)
named   665 bind  512u  IPv6  20681      0t0  UDP *:domain 
named   665 bind  513u  IPv4  20696      0t0  UDP localhost:domain 
named   665 bind  514u  IPv4  20698      0t0  UDP 192.168.1.53:domain 

I then killed 665, ran pihole restartdns

still no luck
<img width="198" alt="error" src="https://user-images.githubusercontent.com/50108306/57326853-6a97e900-70db-11e9-86c0-b782491bef92.png">

**Comment by DL6ER** [comment]
Maybe `bind` autorestarts?

Try to stop it using the regular `system` call, it is
```
sudo service named stop
``
if I'm not mistaken.

**Comment by coderkingnoob** [comment]
ak@ubuntu:~$ sudo service bind9 stop
ak@ubuntu:~$ pihole restartdns
  [✓] Starting DNS service

still the same.  gui shows dns not running / FTL offline

**Comment by DL6ER** [comment]
What does
```
sudo lsof -i :53
```
say? Is the port now free?

If yes, what are the last lines in `/var/log/pihole.log` and `/var/log/pihole-FTL.log`?

**Comment by coderkingnoob** [comment]
lsof -i :53 gives blank. 

ak@ubuntu:~$ cat /var/log/pihole.log
ak@ubuntu:~$ tail -5 /var/log/pihole-FTL.log
[2019-05-07 15:11:44.317 2071]  -> Unknown DNS queries: 0
[2019-05-07 15:11:44.317 2071]  -> Unique domains: 0
[2019-05-07 15:11:44.317 2071]  -> Unique clients: 0
[2019-05-07 15:11:44.317 2071]  -> Known forward destinations: 0
[2019-05-07 15:11:44.317 2071] Successfully accessed setupVars.conf

**Comment by coderkingnoob** [comment]
i deployed centos instead and it is working.  thanks

**Comment by NLLAPPS** [comment]
I have exactly same issue on Ubuntu server 18.04.2 LTS
I am using unbound and DNS service does not restart after reboot unless manually started with `sudo service pihole-FTL restart `



sudo service pihole-FTL status      
--------------------------------------
Jul 05 20:56:26 fitlet2 systemd[1]: Starting LSB: pihole-FTL daemon...
Jul 05 20:56:26 fitlet2 pihole-FTL[662]: Not running
Jul 05 20:56:26 fitlet2 su[919]: Successful su for pihole by root
Jul 05 20:56:26 fitlet2 su[919]: + ??? root:pihole
Jul 05 20:56:26 fitlet2 su[919]: pam_unix(su:session): session opened for user pihole by (uid=0)
Jul 05 20:56:26 fitlet2 pihole-FTL[662]: dnsmasq: unknown interface eno1
Jul 05 20:56:26 fitlet2 su[919]: pam_unix(su:session): session closed for user pihole
Jul 05 20:56:26 fitlet2 systemd[1]: Started LSB: pihole-FTL daemon.


sudo lsof -i :53
--------------------------------------
Returns nothing


pihole restartdns
--------------------------------------
Does not work



pihole -t
--------------------------------------
Jul  5 20:55:08 dnsmasq[1540]: cached checkipv6.digitalocean.synology.com is 2604:a880:2:d0::21a0:3001
Jul  5 20:55:08 dnsmasq[1540]: cached checkipv6.digitalocean.synology.com is 2604:a880:2:d0::222c:e001
Jul  5 20:55:08 dnsmasq[1540]: cached checkipv6.digitalocean.synology.com is 2604:a880:2:d0::2212:1
Jul  5 20:55:14 dnsmasq[1540]: query[A] ssl.google-analytics.com from 192.168.0.189
Jul  5 20:55:14 dnsmasq[1540]: /etc/pihole/gravity.list ssl.google-analytics.com is 0.0.0.0
Jul  5 20:55:26 dnsmasq[1540]: query[A] fitlet2 from 127.0.0.1
Jul  5 20:55:26 dnsmasq[1540]: /etc/pihole/local.list fitlet2 is 192.168.0.2
Jul  5 20:55:26 dnsmasq[1540]: query[AAAA] fitlet2 from 127.0.0.1
Jul  5 20:55:26 dnsmasq[1540]: config fitlet2 is NODATA-IPv6
**_Notice the SIGTERM here_**
**Jul  5 20:55:26 dnsmasq[1540]: exiting on receipt of SIGTERM**



sudo service pihole-FTL restart 
--------------------------------------
Restarts the service and everything works fine
