### ISSUE TITLE
sudo killall -SIGHUP pihole-FTL possibly not working as expected on DEV

### ISSUE THREAD

**Issue by mmotti** [pi-hole/FTL#582]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**
Adding a new regexp through the web interface should apply blocking immediately.

OR

Adding a new regexp directly to the DB (programmatically) and running `sudo killall -SIGHUP pihole-FTL` should apply blocking immediately.

Current method of adding to the DB:
`curl -sSl https://raw.githubusercontent.com/mmotti/pihole-regex/master/install.sh | bash `

**Actual behaviour:**
Assuming that `sudo killall -SIGHUP pihole-FTL` is ran after adding a regexp through the web interface, it isn't working as expected.

Also, when adding directly to the database and running `sudo killall -SIGHUP pihole-FTL`, the command seems to need to be entered twice for it to apply the regexp blocking.

**Steps to reproduce:**
With an **empty** regex table...

1. `dig ad.test.com`

```
pi@raspberrypi:~ $ dig ad.test.com

; <<>> DiG 9.10.3-P4-Raspbian <<>> ad.test.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9052
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;ad.test.com.                   IN      A

;; ANSWER SECTION:
ad.test.com.            2546    IN      A       69.172.200.109

;; Query time: 8 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Jun 05 16:45:31 BST 2019
;; MSG SIZE  rcvd: 56
```

2. Add `^(.+[-_.])??m?ad[sxv]?[0-9]*[-_.]` to the regex blacklist through the web interface

3. dig ad.test.com
```
pi@raspberrypi:~ $ dig ad.test.com

; <<>> DiG 9.10.3-P4-Raspbian <<>> ad.test.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35358
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;ad.test.com.                   IN      A

;; ANSWER SECTION:
ad.test.com.            2466    IN      A       69.172.200.109

;; Query time: 8 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Jun 05 16:46:51 BST 2019
;; MSG SIZE  rcvd: 56
```
4. Now MANUALLY run `sudo killall -SIGHUP pihole-FTL`

5. dig ad.test.com
```
pi@raspberrypi:~ $ dig ad.test.com

; <<>> DiG 9.10.3-P4-Raspbian <<>> ad.test.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61902
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ad.test.com.                   IN      A

;; ANSWER SECTION:
ad.test.com.            2       IN      A       0.0.0.0

;; Query time: 3 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Jun 05 16:47:44 BST 2019
;; MSG SIZE  rcvd: 56
```

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{N/A}`

**Troubleshooting undertaken, and/or other relevant information:**

Running `sudo killall -SIGHUP pihole-FTL` **twice** seems to apply blocking as expected when programmatically adding regexps to the DB.

**Comment by Mcat12** [comment]
I'm not able to reproduce this, it works fine for me. Are you using the latest dev version of FTL, core, and web?

Also, use `pihole restartdns reload` instead of `killall`.

**Comment by mmotti** [comment]
Yep - On the latest (bleeding edge) of everything.

Just some further troubleshooting:
1) Reverted to master `pihole checkout master`
2) Remove pi-hole DB `sudo rm -f /etc/pihole/gravity.db`
3) Restart Pi-hole `sudo service pihole-FTL restart`
4) `pihole -r` -> `repair` (noticed after reverting back that regex.list was missing and couldn't remember the permissions required to recreate it and allow the web interface access to it)
Actually - After having 'repaired' the install - The web interface still says something went wrong but gives no error output, where in actual fact it seems to have still added it to regex.list

Starting with empty regex.list on **master** branch
1. `dig track.test.com` -->  69.172.200.109
2. Add `^track(ers?|ing)?[0-9]*[-.]` to regex.list through web interface
3. `dig track.test.com` --> 0.0.0.0

Works as expected on master for me, but not Dev. Weird.

**Comment by mmotti** [comment]
Further, further troubleshooting:

1. Ran install again with re-configure option
2. `pihole checkout dev`
```
 Current Pi-hole version is v4.2.2-190-gb0c5dcf
 Current AdminLTE version is v4.1-100-g542aa8b4
 Current FTL version is vDev-ed15c15
```
3. Remove all regexp filters
4. `sudo service pihole-FTL restart`
5. `dig track.test.com` --> 69.172.200.109
6. Add `^track(ers?|ing)?[0-9]*[-.]`  through web interface (success)
7. `dig track.test.com` -->69.172.200.109
8. `dig track.test.com` -->69.172.200.109
9. `dig track.test.com` -->69.172.200.109
10. `pihole restartdns reload`
11. `dig track.test.com` --> 0.0.0.0

**Comment by Mcat12** [comment]
Thanks for the steps to reproduce, I have reproduced it on a fresh install.

**Comment by Mcat12** [comment]
I've done some more testing, and the bug only triggers if you start from having zero regex filters and add one. If you start from having one regex filter and add a second, the bug does not appear.

**Comment by Mcat12** [comment]
Looking at the code, this is most likely a bug in master as well.
