### ISSUE TITLE
pihole-FTL.db permissions

### ISSUE THREAD

**Issue by bcambl** [pi-hole/FTL#586]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 
---

**[BUG | ISSUE] Expected Behaviour:**
Network information displayed on network tab

**[BUG | ISSUE] Actual Behaviour:**
Database error on network tab

**[BUG | ISSUE] Steps to reproduce:**

- Install Fedora 30 Server
- Install Pi-hole
- Click Network Tab in Web UI  -> database error

PHP running as `lighttpd:lighttpd` cannot access `pihole-FTL.db` with permissions `600` & ownership of `pihole:pihole`.

Solution:
```
[root@localhost ~]# ls -la /etc/pihole/pihole-FTL.db 
-rw-------. 1 pihole pihole 28672 Jun  9 17:52 /etc/pihole/pihole-FTL.db
[root@localhost ~]# chmod 0644 /etc/pihole/pihole-FTL.db
[root@localhost ~]# ls -la /etc/pihole/pihole-FTL.db 
-rw-r--r--. 1 pihole pihole 28672 Jun  9 17:52 /etc/pihole/pihole-FTL.db
[root@localhost ~]# systemctl restart lighttpd
[root@localhost ~]# 
```

Reported via Reddit [HERE](https://www.reddit.com/r/pihole/comments/bxi5y9/when_will_fedora_30_be_officially_supported/eqfhq1q?utm_source=share&utm_medium=web2x)

**Comment by DL6ER** [comment]
Have you manually set a `umask`? What is the output of
```
umask
```
on your Fedora server?

I'm running Fedora 30 workstation where the standard `umask` seems to be `0002`.

**Comment by bcambl** [comment]
Fedora 30 Server is `0022` on a clean install.  
Fedora 30 Server ISO install on `vagrant-libvirt`.
