### ISSUE TITLE
Unable to clone/DEV via Windows due to repo directory naming using reserved device names

### ISSUE THREAD

**Issue by CollinChaffin** [pi-hole/FTL#599]
The use of the directory named `aux` in this repo makes it impossible to successfully fully clone and build/develop at all on a Windows environment due to this being one of the several "reserved" names (for device use) implemented back in the mid 1970's.  

I was aware of this so was not surprised when I saw the git error upon cloning on WIN regarding the directory named `AUX` causing the catastrophic git clone failure (my hair is really grey) but for most it is obviously probably not known and/or they are not attempting to clone and develop using a Windows environment.

Here is a bit more info from MS stating as much and some background ("file" also obviously goes for "directory" as they are both just file table/journal entries):

https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file

```
Do not use the following reserved names for the name of a file:

CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.
```

Since many DEVs, despite having access to Linux-based systems, perform their DEV workflows in a Windows environment it would be great to have this fixed so the repo can exist on a windows volume.  TIA!

**Comment by DL6ER** [comment]
> for most it is obviously probably not known and/or they are not attempting to clone and develop using a Windows environment.

I agree, however, we will surely adapt our repository structure to ensure compatibility with whatever development platform you prefer. I do not have any Windows machines within reach, so I cannot verify that #601 will actually fix your issue, but I hope you can try checking out the `fix/filenames` which is nothing else but the current `development` branch modulo the change concerning the `aux` directory.

**Comment by Mcat12** [comment]
I tested #601 and it fixes the issue.

**Comment by DL6ER** [comment]
This issue is fixed.

**Comment by Mcat12** [comment]
Until 5.0 is released (merged to master), you will have to clone the dev branch instead of master.
