### ISSUE TITLE
FTL is M.I.A

### ISSUE THREAD

**Issue by Tntdruid** [pi-hole/FTL#60]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_{1}_

**[BUG | ISSUE] Expected Behaviour:**
Rebooted my raspberry pi 3, saw that FTL was offline. Logged in via ssh

pi@raspberrypi:~ $ sudo service pihole-FLT status 
pihole-FLT.service
Loaded: not-found (Reason: No such file or directory) Active: inactive (dead)

pi@raspberrypi:~ $ sudo service pihole-FLT start
Failed to start pihole-FLT.service: Unit pihole-FLT.service failed to load: No such file or directory.

pi@raspberrypi:~ $ pihole -up
::: Checking for updates...
::: Pi-hole Core:   up to date
::: FTL:            up to date
::: Web Interface:  up to date
:::
::: Everything is up to date!

[2017-05-23 21:23:05.671] FATAL: FTL received SIGTERM from PID/UID 1/0, scheduled to exit gracefully

rydagvb2sr

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**Log file output [if available]**

`output`

**Device specifics**

```Hardware Type: rPi, VPS, etc
OS:


_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
```
pi@raspberrypi:~ $ sudo service pihole-FLT status
pihole-FLT.service
Loaded: not-found (Reason: No such file or directory) Active: inactive (dead)
```

Is the file `/etc/init.d/pihole-FTL` there? If not, I cannot explain why it is missing, but a Repair (`pihole -r`) will install it.

**Comment by Tntdruid** [comment]
pihole-FTL is in /etc/init.d/

**Comment by DL6ER** [comment]
Oh, now I see what happened - you had a typo!

> pi@raspberrypi:~ $ sudo service pihole-FLT status

That should not be `FLT`, but rather `FTL`

**Comment by Tntdruid** [comment]
woops :D
