### ISSUE TITLE
Allow a privacy mode where clients are anonymized but not domains

### ISSUE THREAD

**Issue by Crocmagnon** [pi-hole/FTL#629]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (at least I didn’t find it here or in the pi-hole repo)

**How familiar are you with the codebase?:**

1

---

**[ISSUE] Expected Behaviour:**
I’d expect to have a privacy level allowing for viewing domains but not clients. This would allow for whitelisting domains when someone reports a false positive without being able to relate it to any client.

**[ISSUE] Actual Behaviour:**
Currently if I want to see the domains I’m obligated to keep the related clients. There is no privacy level for anonymized clients but clear domains.

**[ISSUE] Steps to reproduce:**

- Go to the settings page
- Go to the privacy tab
- If you want to anonymize clients, you are obligated to anonymize domains.

**Device specifics**

Hardware Type: rPi
OS: raspbian stretch

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net), as mentioned in our [Issue Templates](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md).

Thank you for your understanding.

**Comment by Crocmagnon** [comment]
Hi @DL6ER 👋 
Thanks for pointing me in the right direction! Just for your information, the discourse forum is not mentioned in the issue template for this repo, I guess that's why I missed it!

Anyway, thanks! 🙂

**Comment by DL6ER** [comment]
No worries, my text might have sounded harsher than intended. The problem is just that Github as a platform is not really suited for (possible multi-user) discussions and Discourse is a much better place for this.

Thanks for reminding me to update the issue template.
