### ISSUE TITLE
Unreachable code detected

### ISSUE THREAD

**Issue by i39** [pi-hole/FTL#639]
Code in this position will never be reachable. 
https://github.com/pi-hole/FTL/blob/b60d63f448179cb139755eb8dcfd9d5335df3fd4/database.c#L529

Because of: 

			if(saved_error < 3)
			{
				**continue;**
			}
			else
			{
				logg("save_to_DB() - exiting due to too many errors");
				**break;**
			}

**Comment by DL6ER** [comment]
This has been resolved in v5.0.

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
