### ISSUE TITLE
follow-up to Make pihole-FTL executable error #627

### ISSUE THREAD

**Issue by petaflot** [pi-hole/FTL#640]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide].
- [X] The issue I am reporting can be *replicated*
- [?] The issue I am reporting isn't a duplicate --> does this count?

**How familiar are you with the codebase?:**

1

**[BUG | ISSUE] Expected Behaviour:**

compilation success

**[BUG | ISSUE] Actual Behaviour:**

comilation fails with error
dnsmasq/dnsmasq.h:156:34: fatal error: nettle/nettle-meta.h: No such file or directory

**[BUG | ISSUE] Steps to reproduce:**

- clone FTL git repo, checkout master
- make

**Log file output [if available]**

In file included from dnsmasq/arp.c:17:0:
dnsmasq/dnsmasq.h:156:34: fatal error: nettle/nettle-meta.h: No such file or directory
 #  include <nettle/nettle-meta.h>

**Device specifics**

Hardware Type: raspi 3B+

OS:

gcc (Raspbian 6.3.0-18+rpi1+deb9u1) 6.3.0 20170516

**Comment by DL6ER** [comment]
FTL depends on `libnettle` being installed in a development variant (header files are available). See our official documentation on [how to compile FTL from source](https://docs.pi-hole.net/ftldns/compile/) for further details.

Feel free to re-open this issue when you encounter an error that is not covered by our documentation.
