### ISSUE TITLE
estimated dev branch to master schedule

### ISSUE THREAD

**Issue by 4688-is-great** [pi-hole/FTL#641]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

6

---

**[BUG | ISSUE] Expected Behaviour:**
DL6ER needs a fat raise for his great work.  
More of a question than an issue.   Is it likely that the dev branch code will be merged to master in the next couple of months?  I looked for an announcement on https://pi-hole.net/blog/ but don't see one.  A few of my friends in the infosec world are very interested in the new whitelist changes that are in the development branch.  If there is a need for volunteers to help out with anything specific, please share here. 
**[BUG | ISSUE] Actual Behaviour:**
Not sure if DL6ER got his fat raise.  

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**Log file output [if available]**

`output`

**Device specifics**

Hardware Type: rPi, VPS, etc
OS:

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
We do not provide ETAs as all of your core developers are volunteers and we all have jobs that are obviously more important as they pay our salary. Nevertheless, we plan to pre-release up the current changes in `development` in a beta release testing rather soon (no promises but it is currently planned to happen this week or the next one).

During the beta testing, we provide the code in what we think is a good state, however, it will be provided as-is and may contain some glitches here and there. We ask all beta testers to provide feedback and meanwhile promise ourselves to try to fix any obstacles rather quickly.

**Comment by 4688-is-great** [comment]
Cheers, many thanks..will donate!
