### ISSUE TITLE
pihole-FTL crashing very often

### ISSUE THREAD

**Issue by servergeeks** [pi-hole/FTL#649]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`0`

---
**Expected behaviour:**

`{FTL should be up and running at all times}`

**Actual behaviour:**

```
{I've added a cronjob that run a check every 5 minutes to see if FTL is responding to DNS queries. Here are some states.....
DNS UP: Sat Oct  5 12:00:02 CEST 2019
DNS UP: Sat Oct  5 12:05:01 CEST 2019
DNS UP: Sat Oct  5 12:10:01 CEST 2019
DNS UP: Sat Oct  5 12:15:01 CEST 2019
DNS UP: Sat Oct  5 12:20:01 CEST 2019
DNS DOWN: Sat Oct  5 12:25:01 CEST 2019 ... RESTARTING
DNS UP: Sat Oct  5 12:30:01 CEST 2019
DNS UP: Sat Oct  5 12:35:01 CEST 2019
DNS UP: Sat Oct  5 12:40:01 CEST 2019
DNS UP: Sat Oct  5 12:45:01 CEST 2019
DNS UP: Sat Oct  5 12:50:01 CEST 2019
DNS UP: Sat Oct  5 12:55:01 CEST 2019
DNS UP: Sat Oct  5 13:00:01 CEST 2019
DNS UP: Sat Oct  5 13:05:01 CEST 2019
DNS UP: Sat Oct  5 13:10:02 CEST 2019
DNS UP: Sat Oct  5 13:15:01 CEST 2019
DNS UP: Sat Oct  5 13:20:01 CEST 2019
DNS DOWN: Sat Oct  5 13:25:01 CEST 2019 ... RESTARTING
DNS UP: Sat Oct  5 13:30:01 CEST 2019
DNS UP: Sat Oct  5 13:35:01 CEST 2019
DNS DOWN: Sat Oct  5 13:40:01 CEST 2019 ... RESTARTING
DNS DOWN: Sat Oct  5 13:45:01 CEST 2019 ... RESTARTING
DNS DOWN: Sat Oct  5 13:50:01 CEST 2019 ... RESTARTING
DNS UP: Sat Oct  5 13:55:01 CEST 2019
DNS UP: Sat Oct  5 14:00:01 CEST 2019
DNS UP: Sat Oct  5 14:05:01 CEST 2019
DNS UP: Sat Oct  5 14:10:01 CEST 2019
DNS UP: Sat Oct  5 14:15:01 CEST 2019
DNS DOWN: Sat Oct  5 14:20:01 CEST 2019 ... RESTARTING
DNS UP: Sat Oct  5 14:25:01 CEST 2019
DNS DOWN: Sat Oct  5 14:30:01 CEST 2019 ... RESTARTING
DNS UP: Sat Oct  5 14:35:01 CEST 2019
DNS UP: Sat Oct  5 14:40:01 CEST 2019
DNS UP: Sat Oct  5 14:45:01 CEST 2019
DNS UP: Sat Oct  5 14:50:01 CEST 2019
DNS UP: Sat Oct  5 14:55:01 CEST 2019
DNS UP: Sat Oct  5 15:00:01 CEST 2019
DNS UP: Sat Oct  5 15:05:01 CEST 2019
DNS UP: Sat Oct  5 15:10:01 CEST 2019
DNS UP: Sat Oct  5 15:15:01 CEST 2019
DNS DOWN: Sat Oct  5 15:20:01 CEST 2019 ... RESTARTING
DNS UP: Sat Oct  5 15:25:01 CEST 2019
DNS UP: Sat Oct  5 15:30:01 CEST 2019
DNS UP: Sat Oct  5 15:35:01 CEST 2019
DNS UP: Sat Oct  5 15:40:01 CEST 2019
}
```

**Steps to reproduce:**

`{No idea on how and why it dies.}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{cz4awcctm0}`

**Troubleshooting undertaken, and/or other relevant information:**

`{For now I have a cronjob checking the DNS status every 5 minutes to see if I need to restart the FTL service.}`

**Comment by dschaper** [comment]
```
   Oct  5 01:18:06 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
   Oct  5 01:18:12 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
   Oct  5 01:18:23 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
   Oct  5 01:18:32 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
   Oct  5 01:18:38 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
   Oct  5 01:31:35 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
   Oct  5 01:31:45 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
   Oct  5 01:31:56 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
   Oct  5 01:32:04 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
```

Do you have conditional forwarding enabled? Can you run `pihole -d` when the script says DNS is unavailable?

**Comment by dschaper** [comment]
Checking further,

```
    CONDITIONAL_FORWARDING=true
    CONDITIONAL_FORWARDING_IP=192.168.3.1
    CONDITIONAL_FORWARDING_DOMAIN=local
    CONDITIONAL_FORWARDING_REVERSE=3.168.192.in-addr.arpa
```

Does the DNS server at 192.168.3.1 have any configuration options that may send those queries to the Pi-hole device? Usually when max concurrent is reached it's because of a loop, Pi-hole queries upstream conditional DNS server and that server queries Pi-hole which then queries conditional DNS etc...

**Comment by servergeeks** [comment]
> ```
>    Oct  5 01:18:06 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
>    Oct  5 01:18:12 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
>    Oct  5 01:18:23 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
>    Oct  5 01:18:32 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
>    Oct  5 01:18:38 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
>    Oct  5 01:31:35 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
>    Oct  5 01:31:45 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
>    Oct  5 01:31:56 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
>    Oct  5 01:32:04 dnsmasq[10603]: Maximum number of concurrent DNS queries reached (max: 150)
> ```
> 
> Do you have conditional forwarding enabled? Can you run `pihole -d` when the script says DNS is unavailable?

I've seen this also and increase the cache_size to 150000. 
I haven't seen this type of message in the logs since.

**Comment by servergeeks** [comment]
> Checking further,
> 
> ```
>     CONDITIONAL_FORWARDING=true
>     CONDITIONAL_FORWARDING_IP=192.168.3.1
>     CONDITIONAL_FORWARDING_DOMAIN=local
>     CONDITIONAL_FORWARDING_REVERSE=3.168.192.in-addr.arpa
> ```
> 
> Does the DNS server at 192.168.3.1 have any configuration options that may send those queries to the Pi-hole device? Usually when max concurrent is reached it's because of a loop, Pi-hole queries upstream conditional DNS server and that server queries Pi-hole which then queries conditional DNS etc...

Thanks for the reply! The forwarding was because of the suggestion related to .local/.whatever dns lookups to have hostnames for clients on the network...

I've disabled that and also disabled the forwarding that was present on 192.168.3.1. 

I've ran again pihole -d and sent the log.

If you have the time please take a look over it...
[✓] Your debug token is: https://tricorder.pi-hole.net/xm76gg9mpi

Thank you!

**Comment by DL6ER** [comment]
> I've seen this also and increase the cache_size to 150000.
> I haven't seen this type of message in the logs since.

The cache size has nothing to do with the upper limit of concurrent DNS queries. The latter is a fixed value that should not be changed by the user. The limit is defined here:
https://github.com/pi-hole/FTL/blob/b60d63f448179cb139755eb8dcfd9d5335df3fd4/dnsmasq/config.h#L17
and can be changed at compile time with something like
```
dns-forward-max=150
```
in any `/etc/dnsmasq.d/*.conf` file.

> I've disabled that and also disabled the forwarding that was present on 192.168.3.1.

Did the issue disappear now?

**Comment by servergeeks** [comment]
No more restart/crash happened after I applied the changes. 
It seems to be stable, thank you for the help!!

br
