### ISSUE TITLE
pihole-FTL.service not restarting after upgrade

### ISSUE THREAD

**Issue by reymonlu** [pi-hole/FTL#715]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1_

---

**[ISSUE] Expected Behaviour:**
After an update, pihole-FTL.service restart without errors.

**[ISSUE] Actual Behaviour:**
My defaut umask is 037 for security reason. Whenever I upgrade Pihole, I have some permission issues with files  /etc/dnsmasq.conf and /etc/pihole/gravity.list because of my umask (the owner and groups are root and pihole user can't read the file...)

**[ISSUE] Steps to reproduce:**

- Install pihole on a system where default umask is 037.
- Update pihole
- pihole-FTL.service is not restarting and domain in /etc/pihole/gravity.list are not used.

**[ISSUE] Log**
`
Mar 22 13:10:01 raspbian1 pihole-FTL[27621]: dnsmasq: cannot read /etc/dnsmasq.conf: Permission denied
`

**Device specifics**

Hardware Type: rPi 3B+
OS: Raspbian Buster

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
I'm not sure how we can do anything to change our behavior. Any suggestions? If the files are owned by root then only root will be able to change them, we wouldn't have that kind of access.

**Comment by reymonlu** [comment]
I don't think you need to change your behaviour. But if pihole user needs to read this file. Can you just grant the read access to others on this particular file ?
Like a `chmod o+r /etc/dnsmasq.conf` during installation/update process

**Comment by dschaper** [comment]
Off the top of my head, we may be able to `install` instead of `cp` and use something like a mode of 644. 

https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L1244

**Comment by pvogt09** [comment]
This has already been fixed in pi-hole/pi-hole#2730 but did not make it to the master branch until now.

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.
