### ISSUE TITLE
upgrade v5 error

### ISSUE THREAD

**Issue by it-can** [pi-hole/FTL#726]
on my pihole v5 is tried upgrading but get this error....

```
[✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [i] Checksums do not match, downloading from ftl.pi-hole.net.
  [i] Downloading and Installing FTL...pihole-FTL-arm-linux-gnueabihf: FAILED
sha1sum: WARNING: 1 computed checksum did NOT match
  [✗] Downloading and Installing FTL
  Error: Download of https://ftl.pi-hole.net/release/v5.0/pihole-FTL-arm-linux-gnueabihf failed (checksum error)
  [✗] FTL Engine not installed

  Unable to complete update, please contact Pi-hole Support
```

**Comment by Alomamabobo** [comment]
Hello,
Same here (RPI2) wrong checksum :)
My 2 cents, keep up the good work :)

**Comment by it-can** [comment]
works again

**Comment by Alomamabobo** [comment]
Thanks, works too here.

**Comment by DL6ER** [comment]
The underlying issue is described here (in case you are interested): https://discourse.pi-hole.net/t/ftl-update-this-morning-fails-with-checksum-error/30243/6

**Comment by MCX513** [comment]
I am getting an error as well 
The error I am getting is:
E: Unable to locate package php5-xml
E: Unable to locate package php-intl
