### ISSUE TITLE
Cohabitation PiHole 4+ and dnsmasq

### ISSUE THREAD

**Issue by maniackcrudelis** [pi-hole/FTL#734]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
5

---
**Expected behaviour:**

Run PiHole and dnsmasq on the same server, as it was before 4.0

**Actual behaviour:**

FTLDNS replace dnsmasq, thus dnsmasq is disable in your install script.

**Steps to reproduce:**

Install Pi-Hole with the automated script.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

---

Hi

I'm the current packager of PiHole for [YunoHost](https://yunohost.org/#), unfortunately the version we propose stopped to 3.3.1
Many users are asking for newer versions of your tool. Unfortunately, we have dnsmasq running on our system, and we can't just turn it off.
With version prior to 4.0, everything work pretty well and we can enjoy using Pi-Hole easily.

So I would like to know if there's any way to have Pi-Hole version 4 or later to work along with dnsmasq, as it was before.
I just had a (quick) look to your repository and didn't find anything relevant on that matter. Only that the install script does stop and disable dnsmasq.

I hope to find a way to use your new versions and to propose those new version to our users.

**Comment by DL6ER** [comment]
No worries, we want to create the best experience for all users - even on operating systems we do not officially support. At least, when this is neither an immense task nor adds maintenance workload  while it would only be used by very few users. Both these points are not true here.

Please try the branch `new/dnsmasq_dropin_replacement`

Your symbolic link should automatically trigger the drop-in mode. I'm interested in your feedback and also whether we would need to change something in addition to make your life easier!

**Comment by maniackcrudelis** [comment]
Back with some news, pretty good news.

First thanks for your quick answer with something I can actually work with.

The trick was that dnsmasq and pihole both use sysvinit instead of systemd, and so systemd use systemd.generator to build a systemd script to be actually used.
And finally the systemd script use some specific calls for the sysvinit service that doesn't work with pi-hole sysvinit script.
So, I finally put aside the start scripts of dnsmasq. Although it appeared that dnsmasq is more resilient than a T1000 ! I finally succeed !
I made a fake dnsmasq systemd script that is actually pihole-FTL. And an action on one of them does affect the other as they're the same one.

So it's a first victory.
But even if the service is running, I have actually no DNS resolution. That's an epic fail...
But I'll call it a day anyway, I'm falling asleep on my keyboard...

As a side note, even I did drop, somehow, the sysvinit service, your patch is still very important for me as it allow to run dnsmasq (as pihole-FTL) as if actually dnsmasq from /usr/sbin/dnsmasq

**Comment by maniackcrudelis** [comment]
Somehow found what was the cause of my dns failure.
PiHole-FTL needs a gravity db to start, but actually gravity.sh needs Pihole-FTL to be running to be executed. So, we have a dead end !

I missed the part where the patch was actually on your version 5 ;)
So I made a backport of your patch on the version 4.3.1, so far it's seems to be ok.

Or at least, I have my dns working at the end of the install, pihole-FTL is running, and `/usr/sbin/dnsmasq --test` says "dnsmasq: syntax check OK."

I guess now, I just to have to do all of that properly. Not what I'm doing right now with my crappy script.
And finally check that Pi-Hole does actually work fine.

**Comment by DL6ER** [comment]
`dnsmasq` drop-in replacement support has been merged and will be shipped with Pi-hole v5.0

**Comment by maniackcrudelis** [comment]
As I'm still working on the version 4 (a lot of other things to do as we're working hard on Buster).
So I was  wondering, do you have an idea, even a vague idea about when you're going to release that v5.0 ?
Maybe it's not completely worth it to work on the v4 if the v5 is about to be out very soon.

No pressure though ;) I know how it can be irritating to have those questions when you're already working hard to make that release happen !
Just to know if on my side I should rather wait than hurry.

**Comment by dschaper** [comment]
Barring any kind of surprise I'd say a week or less.

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released.

**Comment by maniackcrudelis** [comment]
Thanks you :+1: 
I add it on top of my todo list
