### ISSUE TITLE
SIOCGSTAMP undeclared

### ISSUE THREAD

**Issue by nuxeh** [pi-hole/FTL#746]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

1
---

Failure to build. Interested if this has been seen before.

**[BUG] Steps to reproduce:**

This seems to happen with recent kernel headers.

**Log file output [if available]**

```
gcc -c -o dnsmasq/obj/loop.o dnsmasq/loop.c -g3 -std=gnu11 -I. -Wall -Wextra -Wno-unused-parameter -D_FILE_OFFSET_BITS=64 -fstack-protector-strong -Wp,-D_FORTIFY_SOURCE=2 -O3 -Wl,-z,relro,-z,now -pie -fPIE -fexceptions -fasynchronous-unwind-tables -Wl,-z,defs -Wl,-z,now -Wl,-z,relro -rdynamic -fno-omit-frame-pointer  -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_DEFAULT_MEMSTATUS=0 -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_PROGRESS_CALLBACK -DSQLITE_OMIT_MEMORYDB -DVERSION=\""pi-hole-2.80"\" -DHAVE_DNSSEC -DHAVE_DNSSEC_STATIC
dnsmasq/dhcp.c: In function 'dhcp_packet':
dnsmasq/dhcp.c:182:17: error: 'SIOCGSTAMP' undeclared (first use in this function); did you mean 'SIOCGARP'?
  182 |   if (ioctl(fd, SIOCGSTAMP, &tv) == 0)
      |                 ^~~~~~~~~~
      |                 SIOCGARP
dnsmasq/dhcp.c:182:17: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:121: dnsmasq/obj/dhcp.o] Error 1
```

**Device specifics**

Hardware Type: Generic
OS: Linux/NixOS

**Comment by nuxeh** [comment]
Building release `Pi-hole FTL v4.3.1`

**Comment by nuxeh** [comment]
Linux headers 5.5

**Comment by DL6ER** [comment]
Please try to build [`release/v5.0`](https://github.com/pi-hole/FTL/tree/release/v5.0) to see if the issue persists. All of the development within the past year went into this branch.

I recall having fixed a few compiler errors showing up with `gcc-9`. The one you are reporting might have been one of them. However, as this is now almost one year ago, I don't recall exactly so it will be interesting to see if you still encounter the issue with the most recent version of FTL.

**Comment by nuxeh** [comment]
Hi @DL6ER, thanks. As it happens, I was just about to submit a pull request based on `v4.3.1` fixing three errors building with nettle 3.5, gcc 9.3 and linux 5.5 respectively, but when it came to rebasing on `development`, all three are already fixed.

However, I just built `release/v5.0` and I get another gcc 9 warning/error:

```
gcc -c -o build/signals.o src/signals.c -g3 -std=gnu11 -pipe -Isrc -Wall -Wextra -Wno-unused-parameter -D_FILE_OFFSET_BITS=64 -fstack-protector-strong -Wp,-D_FORTIFY_SOURCE=2 -O3 -Wl,-z,relro,-z,now -fexceptions -funwind-tables -fasynchronous-unwind-tables -Wl,-z,defs -Wl,-z,now -Wl,-z,relro -pie -fPIE -rdynamic -fno-omit-frame-pointer  -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_DEFAULT_MEMSTATUS=0 -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_PROGRESS_CALLBACK -DSQLITE_OMIT_MEMORYDB -DSQLITE_DEFAULT_FOREIGN_KEYS=1 -DSQLITE_DQS=0 -DHAVE_POLL_H -Werror -Waddress -Wlogical-op -Wmissing-field-initializers -Woverlength-strings -Wformat -Wformat-nonliteral -Wuninitialized -Wswitch-enum -Wshadow -Wfloat-equal -Wbad-function-cast -Wwrite-strings -Wparentheses -Wlogical-op -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Winline -Wduplicated-cond -Wduplicated-branches -Wcast-align=strict -Wlogical-not-parentheses -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=noreturn -Wsuggest-attribute=malloc -Wsuggest-attribute=format -Wsuggest-attribute=cold
In file included from /nix/store/wy7r2ff0x939dkg13bn23s287y5w6mgn-glibc-2.30-dev/include/string.h:494,
                 from src/FTL.h:24,
                 from src/api/api.c:11:
In function 'memcpy',
    inlined from 'getVersion' at src/api/api.c:1045:2:
/nix/store/wy7r2ff0x939dkg13bn23s287y5w6mgn-glibc-2.30-dev/include/bits/string_fortified.h:34:10: error: '__builtin_memcpy' forming offset [2, 7] is out of the bounds [0, 1] [-Werror=array-bounds]
   34 |   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by nuxeh** [comment]
Building with `gcc (GCC) 9.3.0`

**Comment by nuxeh** [comment]
Actually, this one is because git isn't present in my build environment, so the makefile shelling out to git to get the current revision returns an empty string, hence the error on build, I believe.

I'll report back when I get it to build.

**Comment by nuxeh** [comment]
So yes, `release/v5.0` builds fine here @DL6ER. I have to I manually override the variables expected to be retrieved at build time from Git... it's tricky to have a full git clone in a deterministic build system, it seems.

**Comment by nuxeh** [comment]
Do you know when you might make this release official?

**Comment by DL6ER** [comment]
We need to have the variables included in the binary for debugging purposes. It seems to be the best way to do it like this as FTL development is a very active topic and we'd surely forget to change the variables for branch, version and commit the binary was built from often enough.

> Do you know when you might make this release official?

It should have happened roughly one month ago. Final testing is finished by now. It all depends on when enough developers can be present to "push the button" and stay ready for possibly incoming support requests. It may happen any time.

**Comment by nuxeh** [comment]
I'm not suggesting that that's setting the git attributes manually is an alternative for upstream, it's just what I'm currently having to do in order to get the build to work in packaging FTL. I can't think of a viable alternative right now, but it's not a big issue. The important thing is that it builds :)

Ok, interesting. I'll keep my eyes peeled. For now I'll package and test this branch for my NixOS package submission, unless I keep with v4.3.1 and backport the fixes. Hmm.

Thanks for your help!

**Comment by DL6ER** [comment]
> what I'm currently having to do in order to get the build to work in packaging FTL. I can't think of a viable alternative right now, but it's not a big issue.

Why aren't you using a workflow typically suggested for automated builds?

Like
```bash
git clone --depth 1 git@github.com:pi-hole/FTL.git
cd FTL
make
```

`git clone --depth 1` ensures you're only downloading the current code and not the entire history (saving bandwidth). You can specify `git clone --depth 1 -b release/v5.0` if you want to shallow-clone a custom branch.

If you go this preferred route, you will also have `git` available for the established workflow.

**Comment by nuxeh** [comment]
Hi @DL6ER , thanks for the suggestion! However, shallow cloning is already the default for NixOS build environments which fetch from Git. There is even the possibility of configuring the git fetcher to leave the .git directory for cases such as this, but it's not recommended to do so, because it's far from being a clear case that doing so is deterministic. Git could change its packing format, or otherwise it has been documented that even when stripping the git repo as much as possible even after shallow cloning (as is the default if leaving the .git) can still lead to non-deterministic variations between builds checking out the same source ref. The preferred way to fetch is actually from (release) tarballs.

Totally as an aside, this is also the case with builds from the tarball releases, which also lack the .git, e.g.:
```
wget https://github.com/pi-hole/FTL/archive/v4.3.1.tar.gz
cd FTL-4.3.1/
make
```
Gives on a system with git installed:
```
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
```
Also as an aside, if I am to package this for NixOS, I am thinking the best versions to use would be the stable versions, with AdminLTE rather than Web, which hasn't had a release yet.

**Comment by DL6ER** [comment]
The NixOS way of doing it sounds strange - maybe even wrong - in this case. How and why should

> Git could change its packing format

be affecting you? You have the `git` binary in your build system. It will create the `.git` directory itself (it will not simply plain download an existing one!) and it is likewise the only party which is messing with any contents of `.git`. I may agree that there is a slight chance that inconsistencies arise when cloneing and working with vastly differing `git` versions, however, this is not the case when the very same `git` version you used for `clone` is also doing all the rest.

>  or otherwise it has been documented that even when stripping the git repo as much as possible even after shallow cloning (as is the default if leaving the .git) can still lead to non-deterministic variations between builds checking out the same source ref.

If this is the case, then this is a bug, likely in NixOS when it is doing its own `git` builds. Checking out the same commit hash will **always** give the exact same source code. Yes, the exact contents of `.git` may vary, however, all outputs will still be the same and the code itself will even 100% guaranteed be the same.

How does the output of the `git` builds (without stripping `.git` which is breaking the cloned repository!) look like?

> Totally as an aside, this is also the case with builds from the tarball releases, which also lack the .git

Yes, we don't have a build process which would inject the version/hash/etc. into the GitHub provided tar.gz archives. We may look at this if you find it necessary. Still, the recommended way of building FTL is through cloning the repo (possibly shallow) and not mess around with the repository's subarchitecture.

> Also as an aside, if I am to package this for NixOS, I am thinking the best versions to use would be the stable versions, with AdminLTE rather than Web, which hasn't had a release yet.

Yes, `web` is far from being even close to feature-complete due to a lack of time to work on this project right now. Furthermore, it is not supposed as a drop-in replacement, there are several other things that need to be done in the rest of the project (they are already mostly done, however, on custom branches).

**Comment by nuxeh** [comment]
> The NixOS way of doing it sounds strange - maybe even wrong - in this case. How and why should
> 
> > Git could change its packing format
> 
> be affecting you? You have the `git` binary in your build system. It will create the `.git` directory itself (it will not simply plain download an existing one!) and it is likewise the only party which is messing with any contents of `.git`. I may agree that there is a slight chance that inconsistencies arise when cloneing and working with vastly differing `git` versions, however, this is not the case when the very same `git` version you used for `clone` is also doing all the rest.

If NixOS were to bump the Git version in use to one which changed the packing format, then newer systems building the same package could receive a different SHA.

The difference is you need the SHA of the source directory's contents to match between successive builds across different systems. And this could in theory differ due to different versions of Git generating the source directory on any given system.

> If this is the case, then this is a bug, likely in NixOS when it is doing its own `git` builds. Checking out the same commit hash will **always** give the exact same source code. Yes, the exact contents of `.git` may vary, however, all outputs will still be the same and the code itself will even 100% guaranteed be the same.

Yes, I completely see your point, and yes, of course the code is the same... but, the Nix builder hashes the entire contents of the checked out source directory before the build happens to help maintain some degree of determinism. So the hash of the *contents* of the source directory could be different, if you include the .git directory.

If you didn't strip it, or even shallow clone it, it could even be affected by refs which don't relate to the branch you're interested in.

> How does the output of the `git` builds (without stripping `.git` which is breaking the cloned repository!) look like?

Just fine, actually. It doesn't do anything destructive, but then again, it perhaps it still isn't deterministic.

https://github.com/NixOS/nixpkgs/blob/2fb5dac372fedd482ef3c65b608810bb7dd45083/pkgs/build-support/fetchgit/nix-prefetch-git#L243

> Yes, we don't have a build process which would inject the version/hash/etc. into the GitHub provided tar.gz archives. We may look at this if you find it necessary. Still, the recommended way of building FTL is through cloning the repo (possibly shallow) and not mess around with the repository's subarchitecture.

Thank you, but I have a feeling this would be difficult, if not impossible, to do, without Github implementing it themselves.

> Yes, `web` is far from being even close to feature-complete due to a lack of time to work on this project right now. Furthermore, it is not supposed as a drop-in replacement, there are several other things that need to be done in the rest of the project (they are already mostly done, however, on custom branches).

That's very good to know. I'm still unsure whether I should package FTL v4.3.1 or v5.0, however. The fixes applied to v5.0 aren't easily applied as backports to v4.3.1 because they are part of various other functional changes in the most part, and if I fix them myself then there is a lack of testing. If v5.0 is already tested then I might consider using that.

**Comment by DL6ER** [comment]
> the Nix builder hashes the entire contents of the checked out source directory before the build happens to help maintain some degree of determinism

I see. My opinion is that this is a clear NixOS bug in this case and should be fixed by excluding `.git` from the checksum generation. This would still ensure the *code* of what you are compiling is the same. Our information is put into the binary by creating `version.h` on this fly. This file will always be the same for the same git commit.
You may not want to change the way NixOS does this, even when I find it would be more meaningful, your feelings might differ. And that's no problem as I assume you can change your build process like:

1. Clone as usual
2. Compile FTL
3. Remove `.git` in the end before hashing.

We can still optimize things here when you see room for improvement, that's never ruled out.

> If v5.0 is already tested then I might consider using that.

The code is frozen and we're basically only waiting for enough developers to be around at the same time to give possibly needed support on our platforms after pushing the RELEASE NOW button. We haven't had any new bug reports in recent days, so the code is done.

**Comment by nuxeh** [comment]
The .git being left out is the default case. There is an option to leave it, if the build system requires Git, but it's not recommended because it has questionable repeatability. I assure you it's not a bug in NixOS :)

The hashing really pertains to the fetching of the code only, to ensure that the same source is fetched when the package builds. Since FTL shells out to git and generates `version.h` during build, this will always happen afterwards, and it also requires the .git directory to persist, so it's a catch 22.

As I said a few comments back on this thread, it's not a huge issue, it's pretty easy to work around, and it's not an uncommon problem when fetching source from git for things with build time dependencies on git.

That said, if `version.h` was pre-generated and included in the release tarballs, that would seem to be an ideal scenario.

**Comment by DL6ER** [comment]
Pi-hole v5.0 has just been released. Feel free to re-open this ticket or open a new one if you'd like to see further changes.
