### ISSUE TITLE
pihole-FTL - nettle 3.6 - error while loading shared libraries: libnettle.so.7

### ISSUE THREAD

**Issue by MrDuck2742** [pi-hole/FTL#748]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1_

---

**[BUG | ISSUE] Expected Behaviour:**

Install: Arch AUR pi-hole-server 4.4-1

https://aur.archlinux.org/packages/pi-hole-server/

pihole-FTL service starts as expected:

`May 07 18:43:11 hostname systemd[1]: Starting Pi-hole FTLDNS engine...
May 07 18:43:11 hostname systemd[1]: Started Pi-hole FTLDNS engine.
May 07 18:43:11 hostname pihole-FTL[954]: [2020-05-07 18:43:11.485 954] Using log file /run/log/pihole-ftl/pihole-FTL.log
May 07 18:43:11 hostname pihole-FTL[954]: [2020-05-07 18:43:11.485 954] ########## FTL started! ##########
May 07 18:43:11 hostname pihole-FTL[954]: [2020-05-07 18:43:11.485 954] FTL branch: master
May 07 18:43:11 hostname pihole-FTL[954]: [2020-05-07 18:43:11.485 954] FTL version: v4.3.1
May 07 18:43:11 hostname pihole-FTL[954]: [2020-05-07 18:43:11.485 954] FTL commit: ff1ac73
May 07 18:43:11 hostname pihole-FTL[954]: [2020-05-07 18:43:11.485 954] FTL date: 2019-07-08
May 07 18:43:11 hostname pihole-FTL[954]: [2020-05-07 18:43:11.485 954] FTL user: pihole
...`

**[BUG | ISSUE] Actual Behaviour:**

pihole-FTL service fails to start as expected:

`May 07 18:34:04 hostname systemd[1]: Starting Pi-hole FTLDNS engine...
May 07 18:34:04 hostname systemd[1]: Started Pi-hole FTLDNS engine.
May 07 18:34:04 hostname pihole-FTL[544]: /usr/bin/pihole-FTL: error while loading shared libraries: libnettle.so.7: cannot open shared object file: No such file or directory
May 07 18:34:04 hostname systemd[1]: pihole-FTL.service: Main process exited, code=exited, status=127/n/a
May 07 18:34:04 hostname systemd[1]: pihole-FTL.service: Failed with result 'exit-code'.`

`ls -l /var/cache/pacman/pkg/*nettle*tar*
-rw-r--r-- 1 root root 337332 Nov 13 15:51 /var/cache/pacman/pkg/nettle-3.5.1-2-x86_64.pkg.tar.xz
-rw-r--r-- 1 root root    310 Nov 13 15:51 /var/cache/pacman/pkg/nettle-3.5.1-2-x86_64.pkg.tar.xz.sig
-rw-r--r-- 1 root root 414879 May  5 05:56 /var/cache/pacman/pkg/nettle-3.6-1-x86_64.pkg.tar.zst
`

**[BUG | ISSUE] Steps to reproduce:**
1. Downgrade nettle from 3.6 to 3.5.1
2. pihole-FTL service starts as expected
-
-
-
-

**Log file output [if available]**

as above.

**Device specifics**

Hardware Type: VMware ESXi 6.0.0
OS: `Linux hostname 5.6.11-arch1-1 #1 SMP PREEMPT Wed, 06 May 2020 17:32:37 +0000 x86_64 GNU/Linux`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
We are linking `libnettle` statically to avoid such issues. ArchLinux applies its own patches to their FTL builds, one of which causes `libnettle` to be linked dynamically. You should open an issue ticket with them.

`libnettle`  v3.5+ support has been added for the Pi-hole v5.0 release, which is expected very soon. I see that the ArchLinux guys have backported c8f86dfaa752dd002942b6410a79b0e805fd9c71 in https://aur.archlinux.org/cgit/aur.git/tree/nettle35.patch?h=pi-hole-ftl
