### ISSUE TITLE
Gravity Adlists not blocked when "No Statistics mode" is enabled

### ISSUE THREAD

**Issue by mzino** [pi-hole/FTL#755]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

(Pi-Hole installed on Ubuntu Server 18.04)
I expect Pi-Hole to block all domains present in Adlists even when query logging is disabled and "No Statistics mode" is enabled in Privacy settings. This was the case until v4.x.x.

**Actual behaviour:**

After updating to v5.0, when "No Statistics mode" is enabled in Settings/Privacy, Gravity lists are ignored and all domains present in Adlists are not blocked. As soon as I switch to "Anonymous mode" (or any other mode above it) blocking resumes as expected.

**Steps to reproduce:**

Update to v5.0;
Enable "No Statistics mode" under Settings/Privacy

**Comment by DL6ER** [comment]
I checked the code and this is expected. Even if it may not be fully intended.

**Technical reason**
When the privacy level is higher than
https://github.com/pi-hole/FTL/blob/3d7c095cb10a1b692c80dd28f6051dea91d45baa/src/dnsmasq_interface.c#L424-L425
we will never reach this point
https://github.com/pi-hole/FTL/blob/3d7c095cb10a1b692c80dd28f6051dea91d45baa/src/dnsmasq_interface.c#L603

The reason for this is that we need to analyze the client and domain data in order to interact with the gravity database. I don't really see a possibility to circumvent this.

Shall we rather remove the no-statistics mode or shall we change its description?

**Comment by gonzoblue** [comment]
I ran in to the same issue. For now I have set my value to 3 to get things back working, waiting to see what gets decided.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/since-pihole-5-ads-dont-get-blocked-in-microsoft-edge/33044/2

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/0-blocked-and-all-network-devices-are-device-does-not-use-pi-hole/34393/2

**Comment by DL6ER** [comment]
We already [removed privacy level 4 from the web interface](https://github.com/pi-hole/AdminLTE/commit/0e4d1e4e7f3035686c9b6b567e4ea7f31b4bcbab) so we should probably do the same with FTL.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/version-5-dns-over-https-any-solutions/34116/22

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/ads-arent-blocked-on-pi-hole-5-0/35275/4

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/ads-arent-blocked-on-pi-hole-5-0/35275/4

**Comment by DL6ER** [comment]
The problematic privacy level has been removed. Case closed.
