### ISSUE TITLE
relating to bug 759 - worked until it didn't

### ISSUE THREAD

**Issue by lesthawk** [pi-hole/FTL#776]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**
1

Issue isexactly as per bug 759, however the fix proposed only worked for a short period. Once all the devices were reboted including the pihole server, the DC and the box I'm trying to add to the domain, the problem returned. doing a ping of the full SRV record name returns the correct IP.

**Comment by DL6ER** [comment]
See https://github.com/pi-hole/FTL/issues/759#issuecomment-632624783

I missed you opened a new ticket but agree we should continue here.

**Comment by DL6ER** [comment]
@lesthawk Any update for us?

**Comment by lesthawk** [comment]
I've sort of worked around this by putting in a Bind9 back end DNS as the upstream for PiHole, operating on a virtual NIC (eth0:1) with a different range IP. However this has it's faults as Pi-Hole doesn't seem to like starting the FTL straight in. Complains that it can't attach to the port, or in one case the IP. I have a feeling there's a race condition between Samba-AD-DC, Bind9 and PiHole... but it's only appeared since installing Pi-hole. Here's the output of a freshly booted service Status. 
restarting each service seems to succeed hence I think it's a race consdition.
Bind9 uses 192.168.1.1 on eth0:1
PiHole is bound to 172.16.1.3
Samba-Ad-DC was bound to SAMBA INTERNAL, but is now bound to Bind9

pi@DC01:~ $ sudo service pihole-FTL status && sudo service bind9 status && sudo service samba-ad-dc status
● pihole-FTL.service - LSB: pihole-FTL daemon
   Loaded: loaded (/etc/init.d/pihole-FTL; generated)
   Active: active (exited) since Tue 2020-05-26 23:10:11 BST; 12h ago
     Docs: man:systemd-sysv-generator(8)
  Process: 468 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)

May 26 23:10:09 DC01 systemd[1]: Starting LSB: pihole-FTL daemon...
May 26 23:10:09 DC01 pihole-FTL[468]: Not running
May 26 23:10:10 DC01 su[568]: (to pihole) root on none
May 26 23:10:10 DC01 su[568]: pam_unix(su:session): session opened for user pihole by (uid=0)
May 26 23:10:11 DC01 pihole-FTL[468]: dnsmasq: failed to create listening socket for 172.16.1.3: Cannot assign requested address
May 26 23:10:11 DC01 su[568]: pam_unix(su:session): session closed for user pihole
May 26 23:10:11 DC01 systemd[1]: Started LSB: pihole-FTL daemon.
● bind9.service - BIND Domain Name Server
   Loaded: loaded (/lib/systemd/system/bind9.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-05-26 23:10:12 BST; 12h ago
     Docs: man:named(8)
  Process: 421 ExecStart=/usr/sbin/named $OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 451 (named)
    Tasks: 7 (limit: 4915)
   Memory: 41.3M
   CGroup: /system.slice/bind9.service
           └─451 /usr/sbin/named -u bind

May 26 23:10:15 DC01 named[451]: network unreachable resolving 'eth0/A/IN': 202.12.27.33#53
May 26 23:10:15 DC01 named[451]: network unreachable resolving 'eth0/AAAA/IN': 192.58.128.30#53
May 26 23:10:15 DC01 named[451]: network unreachable resolving 'eth0/A/IN': 2001:503:ba3e::2:30#53
May 26 23:10:15 DC01 named[451]: network unreachable resolving 'eth0/AAAA/IN': 192.112.36.4#53
May 26 23:10:15 DC01 named[451]: network unreachable resolving 'eth0/A/IN': 192.58.128.30#53
May 26 23:10:15 DC01 named[451]: network unreachable resolving 'eth0/AAAA/IN': 199.7.83.42#53
May 26 23:10:15 DC01 named[451]: network unreachable resolving 'eth0/A/IN': 192.112.36.4#53
May 26 23:10:15 DC01 named[451]: network unreachable resolving 'eth0/A/IN': 199.7.83.42#53
May 26 23:10:39 DC01 named[451]: resolver priming query complete
May 27 09:58:51 DC01 named[451]: resolver priming query complete
● samba-ad-dc.service - Samba AD Daemon
   Loaded: loaded (/lib/systemd/system/samba-ad-dc.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-05-26 23:10:13 BST; 12h ago
     Docs: man:samba(8)
           man:samba(7)
           man:smb.conf(5)
 Main PID: 428 (samba)
   Status: "smbd: ready to serve connections..."
    Tasks: 20 (limit: 4915)
   Memory: 109.5M
   CGroup: /system.slice/samba-ad-dc.service
           ├─428 samba: root process
           ├─647 samba: task[dcesrv]
           ├─648 samba: task[nbtd]
           ├─649 samba: task[wrepl]
           ├─650 samba: task[ldapsrv]
           ├─651 samba: task[cldapd]
           ├─652 samba: task[kdc]
           ├─653 samba: task[dreplsrv]
           ├─654 samba: task[winbindd_parent]
           ├─655 samba: task[ntp_signd]
           ├─656 samba: task[kccsrv]
           ├─657 samba: task[dnsupdate]
           ├─658 samba: tfork waiter process
           ├─659 /usr/sbin/winbindd -D --option=server role check:inhibit=yes --foreground
           ├─660 samba: task[s3fs_parent]
           ├─663 samba: tfork waiter process
           ├─665 /usr/sbin/smbd -D --option=server role check:inhibit=yes --foreground
           ├─670 /usr/sbin/smbd -D --option=server role check:inhibit=yes --foreground
           ├─671 /usr/sbin/smbd -D --option=server role check:inhibit=yes --foreground
           └─675 /usr/sbin/smbd -D --option=server role check:inhibit=yes --foreground

May 26 23:10:10 DC01 samba[428]: root process[428]:   Copyright Andrew Tridgell and the Samba Team 1992-2018
May 26 23:10:12 DC01 samba[428]: root process[428]: [2020/05/26 23:10:12.631800,  0] ../source4/smbd/server.c:773(binary_smbd_main)
May 26 23:10:12 DC01 samba[428]: root process[428]:   binary_smbd_main: samba: using 'standard' process model
May 26 23:10:13 DC01 winbindd[659]: [2020/05/26 23:10:13.650449,  0] ../source3/winbindd/winbindd_cache.c:3160(initialize_winbindd_cache)
May 26 23:10:13 DC01 winbindd[659]:   initialize_winbindd_cache: clearing cache and re-creating with version number 2
May 26 23:10:13 DC01 winbindd[659]: [2020/05/26 23:10:13.679650,  0] ../lib/util/become_daemon.c:138(daemon_ready)
May 26 23:10:13 DC01 systemd[1]: Started Samba AD Daemon.
May 26 23:10:13 DC01 winbindd[659]:   daemon_ready: STATUS=daemon 'winbindd' finished starting up and ready to serve connections
May 26 23:10:13 DC01 smbd[665]: [2020/05/26 23:10:13.977403,  0] ../lib/util/become_daemon.c:138(daemon_ready)
May 26 23:10:13 DC01 smbd[665]:   daemon_ready: STATUS=daemon 'smbd' finished starting up and ready to serve connections

**Comment by DL6ER** [comment]
I just came to my mind that you could also use https://docs.pi-hole.net/ftldns/configfile/#delay_startup to work around this bug if it still exists. I'll close this as I don't think that this is much else we could do here, it really seems to boil to teh very specific configuration/combination of software you run. (this obviously does not mean that we will not try to do our best!). Feel free to re-open this ticket if we should continue to discuss something.
