### ISSUE TITLE
pihole-FTL starts with weird upstream DNSes?

### ISSUE THREAD

**Issue by D33M0N** [pi-hole/FTL#810]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1_

---

**[BUG | ISSUE] Expected Behaviour:**
pihole-FTL uses only DNS servers I have configured in /etc/dnsmasq.d/01-pihole.conf
or the ones in /etc/pihole/setupVars.conf

**[BUG | ISSUE] Actual Behaviour:**
pihole-FTL starts with adding 2 DNS servers I have never set up:
8.8.8.8
8.8.4.4
THEN reads the config file and adds my configured DNS servers on top of those 2.
**Or am I not looking in the right places? Where can I remove all the undesired upstream DNS servers?**

**[BUG | ISSUE] Steps to reproduce:**
- edit config files. I have there only 192.168.1.1 btw. (now it shows there also 1.1.1.1 and 1.1.1.3 I did add for testing, then later removed... )
- pihole restartdns
- journalctl -e
-
-

**Log file output [if available]**

```juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.533 447362] ########## FTL started! ##########
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.533 447362] FTL branch: master
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.533 447362] FTL version: v5.0
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.533 447362] FTL commit: 038b735
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.533 447362] FTL date: 2020-05-11
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.533 447362] FTL user: pihole
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.533 447362] Compiled for x86_64 (compiled locally) using cc (Arch Linux 9.3.0-1) 9.3.0
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.533 447362] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.533 447362]    SOCKET_LISTENING: only local
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.533 447362]    AAAA_QUERY_ANALYSIS: Show AAAA queries
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.533 447362]    MAXDBDAYS: max age for stored queries is 365 days
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.533 447362]    RESOLVE_IPV6: Resolve IPv6 addresses
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.533 447362]    RESOLVE_IPV4: Resolve IPv4 addresses
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    DBINTERVAL: saving to DB file every minute
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    DBFILE: Using /etc/pihole/pihole-FTL.db
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    MAXLOGAGE: Importing up to 24.0 hours of log data
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    PRIVACYLEVEL: Set to 0
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    IGNORE_LOCALHOST: Show queries from localhost
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    BLOCKINGMODE: Null IPs for blocked domains
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    ANALYZE_ONLY_A_AND_AAAA: Disabled. Analyzing all queries
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    DBIMPORT: Importing history from database
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    PIDFILE: Using /run/pihole-ftl/pihole-FTL.pid
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    PORTFILE: Using /run/pihole-ftl/pihole-FTL.port
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    SOCKETFILE: Using /run/pihole-ftl/FTL.sock
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    SETUPVARSFILE: Using /etc/pihole/setupVars.conf
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    MACVENDORDB: Using /etc/pihole/macvendor.db
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    GRAVITYDB: Using /etc/pihole/gravity.db
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    PARSE_ARP_CACHE: Active
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    CNAME_DEEP_INSPECT: Active
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    DELAY_STARTUP: No delay requested.
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362]    BLOCK_ESNI: Enabled, blocking _esni.{blocked domain}
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362] Finished config file parsing
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362] Database version is 5
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.534 447362] Database successfully initialized
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.535 447362] New upstream server: 8.8.8.8 (0/128)
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.535 447362] New upstream server: 8.8.4.4 (1/128)
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.537 447362] Resizing "/FTL-strings" from 4096 to 8192
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.539 447362] Resizing "/FTL-queries" from 262144 to 524288
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.540 447362] Resizing "/FTL-strings" from 8192 to 12288
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.542 447362] Resizing "/FTL-strings" from 12288 to 16384
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.545 447362] New upstream server: 192.168.1.1 (2/128)
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.546 447362] Resizing "/FTL-queries" from 524288 to 786432
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.550 447362] Resizing "/FTL-strings" from 16384 to 20480
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.550 447362] New upstream server: 1.1.1.3 (3/128)
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.550 447362] New upstream server: 1.1.1.1 (4/128)
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.551 447362] Imported 10737 queries from the long-term database
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.551 447362]  -> Total DNS queries: 10737
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.551 447362]  -> Cached DNS queries: 3337
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.551 447362]  -> Forwarded DNS queries: 6204
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.551 447362]  -> Blocked DNS queries: 1196
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.551 447362]  -> Unknown DNS queries: 0
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.551 447362]  -> Unique domains: 694
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.551 447362]  -> Unique clients: 4
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.551 447362]  -> Known forward destinations: 5
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.551 447362] Successfully accessed setupVars.conf
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.551 447362] PID of FTL process: 447362
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-0
```

also the last line there is this way weirdly broken.

**Device specifics**

Hardware Type: x86-64
OS: Manjaro Linux

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
```
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.535 447362] New upstream server: 8.8.8.8 (0/128)
juuni 14 06:14:56 Zen pihole-FTL[447362]: [2020-06-14 06:14:56.535 447362] New upstream server: 8.8.4.4 (1/128)
```
This only tells you that FTL is **aware** of these servers not necessarily that it is also using them. It typically means that you used these servers within the last 24 hours so they are still part of the history data that is loaded on startup of FTL for computing the over-time (24 hours) history you see on the dashboard pi.hole.

There is nothing to worry about them right now. Check `/var/log/pihole.log` for the actually used upstream servers. The logged lines will look like
```
Jun 13 15:50:10 dnsmasq[12733]: using only locally-known addresses for domain use-application-dns.net
Jun 13 15:50:10 dnsmasq[12733]: using nameserver 127.0.0.1#5353        <---------------------------------
Jun 13 15:50:10 dnsmasq[12733]: read /etc/hosts - 8 addresses
Jun 13 15:50:10 dnsmasq[12733]: read /etc/pihole/custom.list - 4 addresses
Jun 13 15:50:10 dnsmasq[12733]: read /etc/pihole/local.list - 2 addresses
```
I'm closing this as this doesn't appear like a real issue, it's just a slight misunderstanding. Feel free to re-open this ticket at any point in case you still think that there is a bug. Otherwise, we can also continue discussing things whilst this is closed.

**Comment by DL6ER** [comment]
> also the last line there is this way weirdly broken.

Concerning this you may want to check if your disk is full. I'm not familiar with Manjaro Linux and if, e.g., you're using an in memory-style filesystem for `/var/log`, etc. How did you obtain the log above?
Does `/var/log/pihole-FTL.log` contain the log output without weirdness?

**Comment by D33M0N** [comment]
> > also the last line there is this way weirdly broken.
> 
> Concerning this you may want to check if your disk is full. I'm not familiar with Manjaro Linux and if, e.g., you're using an in memory-style filesystem for `/var/log`, etc. How did you obtain the log above?
> Does `/var/log/pihole-FTL.log` contain the log output without weirdness?

The previous log I got from `journalctl -e` which is part of `systemd`? Disk is nearly full indeed, but not that full it can't store few log lines :sweat_smile:  145G / 2T still empty.
Yes, pihole-ftl own log in /run/log/pihole-ftl/pihole-FTL.log seems to be intact and not broken. 

Is there a way to see actual currently being used upstream DNS-es somehow? I have not installed the web gui thing -- if I wanted to do that now, how should I proceed to manually add it "later" (pihole own documentation only talks about automated install script now and/or manually executing the said script)? `pihole -c` does say today morning that it only has now 1 DNS (yesterday at the moment of reporting this it was 2 and earlier yesterday even 3 when I started to trying to change it to one)
```
|¯¯¯(¯)_|¯|_  ___|¯|___        Core: version is 
| ¯_/¯|_| ' \/ _ \ / -_)        Web: v5.0.
|_| |_| |_||_\___/_\___|        FTL: 
 ——————————————————————————————————————————————————————————
  Hostname: Zen                (Manjaro  )
    Uptime: 1 day, 14:23:17                                            
 Task Load: 1.28 1.13 1.05     (Active: 3 of 125 tasks)
 CPU usage: 1%                 (16x 3.2 GHz @ 36c)
 RAM usage: 45%                (Used: 7 GB of 16 GB)
 HDD usage: 92%                (Used: 2 TB of 2 TB)
  LAN addr: 192.168.1.11       (Gateway: 192.168.1.1)
   Pi-hole: Active             (Blocking: 84281 sites)
 Ads Today: 6%                 (Total: 777 of 12136)
Local Qrys: 38%                (1 DNS servers)
   Blocked: cdn.onesignal.com                                          
Top Advert: nashira.iad-06.braze.com                                   
Top Domain: pgorelease.nianticlabs.com                                 
Top Client: localhost                        
```

**Comment by dschaper** [comment]
How are you installing Pi-hole? The install script or the AUR?

**Comment by DL6ER** [comment]
> Is there a way to see actual currently being used upstream DNS-es somehow?

Yes, run

> dig CHAOS TXT servers.bind +short

It will return lines like:
```
127.0.0.1#5353 19001 0
```
which is to be interpreted as
```
IP-address#port number-of-queries number-of-errors
```

> who should I approach to suggest pi-hole package in-buit for the Mikrotik RouterOS -- probably Mikrotik own team?

Yes, I think so. We neither have the hardware not the manpower to do this ourselves.

**Comment by D33M0N** [comment]
> ```
> dig CHAOS TXT servers.bind +short
> ```

Thank you very much! :-)

I found in archwiki for changing upstream DNS with
`$ pihole -a setdns server`

is this AUR maintainer own implementation or is this part of official pihole? As this is NOT described or even mentioned in `pihole -a`. Could it be added?

**Comment by dschaper** [comment]
> AUR

Just so you're aware: 

> **ArchLinux Pi-hole is not officially supported by Pi-hole project. In case of bugs and malfunctions please DO NOT file a report upstream.**
> 
> First of all check if the wiki (https://wiki.archlinux.org/index.php/Pi-hole) can help then ask here for assistance and tips.
> When it will be excluded that the problem does not depend on ArchLinux we will file a bug upstream.

https://aur.archlinux.org/packages/pi-hole-server/?O=10&PP=10#pinned-633053
