### ISSUE TITLE
cmake dosnt build/compil on armv5l (debian)

### ISSUE THREAD

**Issue by Conan179** [pi-hole/FTL#834]
Hello@all
I wanted to compile the latest version of the FTL for my armv5l NAS (debian).
But if I do ./build.sh I only get this error message:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
IDN
    linked by target "pihole-FTL" in directory /root/FTL/src

-- Configuring incomplete, errors occurred!
See also "/root/FTL/cmake/CMakeFiles/CMakeOutput.log".
See also "/root/FTL/cmake/CMakeFiles/CMakeError.log".
[CMakeError.log](https://github.com/pi-hole/FTL/files/4928202/CMakeError.log)
[CMakeOutput.log](https://github.com/pi-hole/FTL/files/4928203/CMakeOutput.log)

**Comment by DL6ER** [comment]
cmake cannot locate `libidn`

Note that the [`libidn`](https://www.gnu.org/software/libidn/) is a new dependency of Pi-hole v5.1

**Comment by Conan179** [comment]
Searching libidn for ubuntu, i cam to this:
https://packages.debian.org/search?keywords=libidn
libidn11 and libidn2-0
are innstalled
root@Qnap-NAS:~/FTL# apt install libidn11
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
libidn11 ist schon die neueste Version (1.33-2.2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
root@Qnap-NAS:~/FTL# apt install libidn2-0
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
libidn2-0 ist schon die neueste Version (2.0.5-1+deb10u1).
libidn2-0 wurde als manuell installiert festgelegt.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
My try, first pihole -up and after ./build.sh
is nothing canche.

**Comment by DL6ER** [comment]
You always need the development versions when you want to compile from source. In this case, it is `libidn11-dev`.

Sorry, I just realized that the documentation for v5.1 has not yet been published. You can find the changes here meanwhile: https://deploy-preview-328--pihole-docs.netlify.app/ftldns/compile/#debian-ubuntu-raspbian

**Comment by Conan179** [comment]
I thank you for your help.
After the installation of libidn11-dev, the build /compile worked without proleme.
