### ISSUE TITLE
FTL out of date message after updating to 2.9

### ISSUE THREAD

**Issue by frankrpi3** [pi-hole/FTL#86]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1_

---

**[BUG | ISSUE] Expected Behaviour:**
no message after a succesful update to FTL 2.9

**[BUG | ISSUE] Actual Behaviour:**
FTL out of date message appears after succesful FTL update to 2.9

**[BUG | ISSUE] Steps to reproduce:**
pihole -up

**Log file output [if available]**

`output`

**Device specifics**

Hardware Type: rPi, VPS, etc
OS:

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Please provide further details like

- where do you see this? (can you provide a screenshot if it is on the web?)
- what does `pihole -v` tell you?
- what does `pihole-FTL version` say?

**Comment by frankrpi3** [comment]
![ftl29](https://user-images.githubusercontent.com/26540758/27255639-7b77d4fe-53a2-11e7-8112-6f82753086b0.PNG)

There are also posts regarding this on reddit.com/r/pihole.

**Comment by dschaper** [comment]
Thanks for the report, it looks to be a small issue with the version reporting. You do have the latest version, but it's not reporting as such. We'll get a fix out, but we use Travis to build the binaries and there has been a backlog with that service so it may take a day to get that fix out.

**Comment by Comodore125** [comment]
FTL is not up to date. It is bug and I found the cause. 
I wrote simple shell script with this content.

`echo "$(/usr/bin/pihole-FTL tag)"
echo "$(curl -sI https://github.com/pi-hole/FTL/releases/latest | grep 'Location' | awk -F '/' '{print $NF}' | tr -d '\r\n')"`

And the result was 
```
2.9
v2.9.
```

And update.sh is comparing these two values. FTL is updated everytime they are different. 
So next time please check tags.

**Comment by dschaper** [comment]
Thanks for the very productive comments.

**Comment by jpmck** [comment]
Hello, I was working on my Chronometer2 project earlier today, and found that the version that is being reported by FTL is missing the "v" before the version number:

```
pi@raspberrypi:~ $ pihole-FTL version
2.9
```

Pulling the latest version of FTL includes the "v":
```
pi@raspberrypi:~ $ curl -sI https://github.com/pi-hole/FTL/releases/latest | grep 'Location' | awk -F '/' '{print $NF}' | tr -d '\r\n'
v2.9
```

If it's any help, the version number reported when connecting to FTL via telnet is 2.9 (without a "v"):
```
>version
version 2.9
tag 2.9
branch (no branch)
date 2017-06-16 18:51:46 +0200
```

I've had relatively decent luck finding my way around the scripts that are used for Pi-hole core and web admin, but haven't found where the version information is stored in FTL.

**Comment by WaLLy3K** [comment]
Hey @jpmck, and thanks for your efforts on Chronometer2!

As I understand it, `pihole-FTL` has the version number baked into it when it's compiled, as you can see when using `strings /usr/bin/pihole-FTL | grep "v2.8"`.

I believe the expected behavior is to have "v" before the version number, as is consistent with `pihole-FTL version` (by extension, [`pihole --version`](https://github.com/pi-hole/pi-hole/blob/30035ce1c2d84114c7597b195ab146c51d15b62e/advanced/Scripts/version.sh#L19)) and `telnet pihole-FTL >version`

**Comment by jpmck** [comment]
That's right, and it looks like updater grabs the latest compiled version of FTL from Github:
```
curl -sSL --fail "https://github.com/pi-hole/FTL/releases/download/${latesttag%$'\r'}/${binary}" -o "/tmp/${binary}
```
Then it installs the new version of FTL:
```
install -T -m 0755 /tmp/${binary} /usr/bin/pihole-FTL
```
As you mentioned, the baked in version is listed without the "v".
```
pi@raspberrypi:/opt/pihole $ strings /usr/bin/pihole-FTL | grep "2.9"
...
GIT_VERSION "2.9"
GIT_TAG "2.9"
...
```

Perhaps the version checker should strip out letters prior to the version comparison [like so](https://github.com/jpmck/chronometer2/blob/master/chronometer2.sh#L198)?

**Comment by WaLLy3K** [comment]
Okay interesting! 2.8 showed the v beforehand and 2.9 does not. Going to need input from @DL6ER on that one, because it affects both the upcoming updates of `version.sh` as well as `chronometer.sh`.

It's only fair to give a heads up that the output of `pihole -v` will be changing with the Core v3.1 update, and will show something along the lines of:

```
pihole -v -c
  Current Pi-hole version is v3.0-120-g8ab5ffd
  Current AdminLTE version is v3.0-63-g399f2ad
  Current FTL version is 2.9
```

I would recommend using [something along the lines of this code](https://github.com/pi-hole/pi-hole/blob/c609815632c7d1e66b546344a9f92ccfe4bbbd42/advanced/Scripts/chronometer.sh#L224) to retrieve and parse the version output from a single call to `pihole -v` for your script.

**Comment by DL6ER** [comment]
> It's only fair to give a heads up that the output of pihole -v will be changing with the Core v3.1 update

This will not happen and what you are seeing is not a FTL bug, but rather a bug in the continuous integration systems we use for building the binaries which was behaving screwy over the last couple of days.

So, again this was neither expected nor intended and should be readjusted automatically when we release the next version (which I wanted to do already yesterday, but let's wait until we can be sure that the CI is playing nicely along).

**Comment by DL6ER** [comment]
```
user@ThinkPad ~ $ ./pihole-FTL-linux-x86_64 version
v2.9.1
```
