### ISSUE TITLE
read from gzipped host file to save storage space

### ISSUE THREAD

**Issue by laoshaw** [pi-hole/FTL#904]
Somehow I could not create a new feature request at the forum.

For adblock the /etc/hosts alike files are huge in size, could it be gzipped and then FTL will read from the zipped files to build its internal database out of the hosts file for adblock? I'm trying to run pi-hole on a resource restricted device where storage space is limited.

**Comment by dschaper** [comment]
They shouldn't be huge in size?

**Comment by jfb-pihole** [comment]
What is the URL of one of the huge lists?

**Comment by laoshaw** [comment]
there are many adblock lists e.g. steven's hosts, 80000 lines 2MB in size, which is a lot for 64MB products.

I just checked dnsmasq's code, it reads say /etc/hosts.ads, build a hash table, and no longer uses /etc/hosts.ads anymore(assuming all the adblock entries are in /etc/hosts.ads).

I can essentially do: gunzip /etc/hosts.ads.gz; /etc/init.d/dnsmasq start; gzip /etc/hosts.ads to save some storage without changing dnsmasq's code.

**Comment by dschaper** [comment]
You're not going to get Pi-hole in 64MB.

**Comment by laoshaw** [comment]
my board has 32/64/128/256 MB in size just so you know, which is why I removed the 64MB, anyways.

**Comment by dschaper** [comment]
Use `dnsmasq`, you're not going to get `sqlite3` in anything near that size.

**Comment by yubiuser** [comment]
https://docs.pi-hole.net/main/prerequisites/#hardware

**Comment by dschaper** [comment]
> my board has 32/64/128/256 MB in size just so you know, which is why I removed the 64MB, anyways.

Do you mean that in RAM or in drive space?

**Comment by laoshaw** [comment]
Just curious what made pi-hole to require 2GB space, is it PHP?
 
dnsmasq and its lists should be fine for 64MB, be it disk or RAM.

**Comment by dschaper** [comment]
There's a lot of things that Pi-hole adds. And no, Pi-hole will not run in 64MB RAM, no matter how much disk you have.

**Comment by laoshaw** [comment]
OK Thanks!

**Comment by yubiuser** [comment]
Long-term database and adlist/dpmain/group database. Both can grow in size quite large depending on your use.
