### ISSUE TITLE
FTL running but not responding

### ISSUE THREAD

**Issue by mitchellrj** [pi-hole/FTL#911]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version:  Raspberry Pi OS (Debian 10) 

- Platform:  Raspberry Pi 4 (64-bit OS)

### Expected behavior
FTL runs flawlessly for a long time.

### Actual behavior / bug
Twice in the last weeks, FTL has stopped responding to queries at around 5am. The UI continues running and just shows all queries stop. Restarting the service causes it to resume normal service. Reloading configuration (`service pihole-FTL reload`) does not help matters - it causes the `pihole-FTL` process to exit and not re-launch.

### Steps to reproduce

Unable to reproduce predictably.

### Debug Token

- URL:  https://tricorder.pi-hole.net/jidslbui21

### Screenshots
<img width="1249" alt="Screenshot 2020-10-25 at 14 30 51" src="https://user-images.githubusercontent.com/147070/97118553-7548a280-1702-11eb-93b0-b165c9b6e2c2.png">

### Additional context

`journalctl -fu pihole-FTL`:
```
Oct 19 21:12:37 ganymede systemd[1]: Starting LSB: pihole-FTL daemon...
Oct 19 21:12:37 ganymede pihole-FTL[30744]: Not running
Oct 19 21:12:37 ganymede su[30762]: (to pihole) root on none
Oct 19 21:12:37 ganymede su[30762]: pam_unix(su:session): session opened for user pihole by (uid=0)
Oct 19 21:12:37 ganymede pihole-FTL[30744]: FTL started!
Oct 19 21:12:37 ganymede su[30762]: pam_unix(su:session): session closed for user pihole
Oct 19 21:12:37 ganymede systemd[1]: Started LSB: pihole-FTL daemon.
```

`tail /var/log/pihole-FTL.log`:
```
[2020-10-25 01:05:05.649 30784M] Resizing "/FTL-dns-cache" from 126976 to 131072
[2020-10-25 01:37:34.414 30784M] Resizing "/FTL-strings" from 172032 to 176128
[2020-10-25 04:55:04.110 30784M] Reloading DNS cache
[2020-10-25 04:55:04.110 30784M] Blocking status is enabled
```

`tail /var/log/pihole.log`: shows normal queries up to 04:55:03, then nothing.

`netstat -plnu`:
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp   214464      0 0.0.0.0:53              0.0.0.0:*                           -
udp6     768      0 :::53                   :::*                                -
```

`lsof -ni :53`:
```
COMMAND     PID       USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
pihole-FT 30784     pihole    4u  IPv4 65132016      0t0  UDP *:domain
pihole-FT 30784     pihole    5u  IPv4 65132017      0t0  TCP *:domain (LISTEN)
pihole-FT 30784     pihole    6u  IPv6 65132018      0t0  UDP *:domain
pihole-FT 30784     pihole    7u  IPv6 65132019      0t0  TCP *:domain (LISTEN)
```

CPU is 95% idle

`free -h`:
```
              total        used        free      shared  buff/cache   available
Mem:          7.6Gi       742Mi       752Mi        41Mi       6.2Gi       7.0Gi
Swap:          99Mi       0.0Ki        99Mi
```

procstat values for FTL (PID 30784)
```
Created at: Mon Oct 19 2020 21:12:37 GMT+0100 (British Summer Time)
Threads: 5
VMS bytes: 434659328
Voluntary context switches: not-changing
```

`time host pi-hole.net 127.0.0.1`:
```
;; connection timed out; no servers could be reached

real	0m10.026s
user	0m0.020s
sys	0m0.007s
```
`host -T pi-hole.net 127.0.0.1`:
```
;; Connection to 127.0.0.1#53(127.0.0.1) for pi-hole.net failed: connection refused.
```

Lookups to 1.1.1.1 and local router work fine.

Deliberately using nginx instead of lighttpd.

**Comment by DL6ER** [comment]
Thanks for your report and sorry for the inconvenience you're experiencing. We'll try our best to get this fixed for you.

First, two questions:

- You said "Twice in the last weeks, FTL has stopped responding to queries at around 5am". If it is (fairly) reproducible, it would be great if you could narrow this down to the last query which was made and the last successful one (if not identical).
- Is such a high "background noise" of roughly 4000 queries per timeslot expected in your setup? However, it doesn't seem to be a memory issue judging from your `free` output.

We changes quite a bit in the inner workings of Pi-hole in the current `development` branches and hope for a new release in the not too distant future. If you're fine with updating to the latest development changes, we can maybe squash your bug instantaneously and avoid any future work (that would be redundant).

**Comment by mitchellrj** [comment]
Unfortunately my logs don't go far enough back to figure out what the last query was the previous times it has stopped responding. The background query level is fairly normal and all legitimate traffic - I have a Prometheus server that generates most of the traffic.

Happy to try a development version, as I have another pihole that I can leave on stable and should handle failover. Will `pihole checkout ftl development` do it, or are there any dependencies on other component versions?

**Comment by PromoFaux** [comment]
When running any of the dev branches, it's best to do a full dev checkout with `pihole checkout dev`, as things can change in the other repositories, as you rightly questioned :)

**Comment by mitchellrj** [comment]
These symptoms have happened again, though maybe with a different cause on the stable version. This time there are logs:
```
[2020-10-30 19:07:00.483 28168/T28173] SQLite3 message: database corruption at line 67286 of [3bfa9cc97d] (11)
[2020-10-30 19:07:00.483 28168/T28173] SQLite3 message: database disk image is malformed in "SELECT name FROM network WHERE id = (SELECT network_id FROM network_addresses WHERE ip = ?);" (11)
[2020-10-30 19:07:00.483 28168/T28173] getDatabaseHostname("192.168.3.9") - SQL error prepare: database disk image is malformed
[2020-10-30 19:07:36.205 28168M] Received: Real-time signal 0 (34 -> 0)
[2020-10-30 19:08:07.364 28168/T28169] Received: Real-time signal 0 (34 -> 0)
[2020-10-30 19:08:40.297 28168/T28170] Received: Real-time signal 0 (34 -> 0)
```

It may be relevant that my DB is quite large:
`ls -lh /etc/pihole/pihole-FTL.db`:
```
-rw-r--r-- 1 pihole pihole 8.7G Aug 24 21:59 /etc/pihole/pihole-FTL.db
```

In this scenario the ports are still held open by the running process, but not responding.

**Comment by mitchellrj** [comment]
dev versions now running 👍 
```
Current Pi-hole version is development v5.0-617-g89d94ac.
Current AdminLTE version is devel v5.1.1-131-g274c196.
Current FTL version is development vDev-86d5b8a.
```

**Comment by DL6ER** [comment]
@mitchellrj 

> `SQL error prepare: database disk image is malformed`

This typically means what it says. The image is damaged on-disk. This can have an number of causes, on Raspberry Pi(-like) systems, this typically means a bad power supply or a dirty reboot (unplugged power during a transaction event). Sometimes, it may also relate to a worn out SD card having just too many bad sectors or improper bad sector handling (when bad sectors aren't skipped as they ought to be). This happens only rarely because the database has strong mechanisms against this kind of data corruption, however, a bad power supply may lead to several bits not being written properly to disk. There is nothing we could do here.

The database can *sometimes* be recovered by recreating it. Just Google for `sqlite3 database disk image is malformed`` and you will find a lot of pages about.

**Comment by DL6ER** [comment]
@mitchellrj Do you have any update for us?

**Comment by mitchellrj** [comment]
No repeat occurrences since the last updated.

**Comment by mitchellrj** [comment]
Still no change. Happy to close at this point. Thanks for your assistance!
