### ISSUE TITLE
Settings through webUI is not getting saved

### ISSUE THREAD

**Issue by Prakkie** [pi-hole/FTL#915]
### Versions

- Pi-hole:  v5.1.2
- FTL: v5.2 

### Platform

- OS and version:  Arch Linux 5.9.1

- Platform: Desktop  

### Expected behavior

_Settings through UI should get saved._

### Actual behavior / bug

_No setting through UI is getting saved. I am using nginx. It was all working till upgrade to this version. Tried after complete browser cache clear too. Still issue persists. Also, checked http user expiry. All good with the user. _

### Steps to reproduce

1. Click on any option and change the setting.
2. Click on any other option. Whatever changes made wont get saved and resets to whatever there before.
3. Tried with disabling pihole for all time options, DNS settings, UI theme to dark.
4. No errors.

**Comment by dschaper** [comment]
Please contact the AUR as requested by the package managers.
