### ISSUE TITLE
Resolve CNAME without DNSSEC on DNSSEC domain

### ISSUE THREAD

**Issue by Virsacer** [pi-hole/FTL#921]
### Versions
  Pi-hole version is v5.1.2 (Latest: v5.1.2)
  AdminLTE version is v5.1.1 (Latest: v5.1.1)
  FTL version is v5.2 (Latest: v5.2)

### Platform
- OS and version: Ubuntu 20.04
- Platform: Docker on Raspberry Pi with

### Expected behavior

My domain uses DNSSEC and I have a CNAME to another domain, that does not.
In Pihole "Use DNSSEC" is enabled.
I expect to get the IP of the other domain returned, like bind9 (with "dnssec-validation auto") does:

Server:         192.168.20.2
Address:        192.168.20.2#53

Non-authoritative answer:
status.**********.de       canonical name = stats.uptimerobot.com.
Name:   stats.uptimerobot.com
Address: 52.9.130.155

### Actual behavior / bug

I get the CNAME but no IP:

Server:         192.168.18.2
Address:        192.168.18.2#53

Non-authoritative answer:
status.**********.de       canonical name = stats.uptimerobot.com.

**Comment by DL6ER** [comment]
Without actually knowing the domain in question, it'll be hard to trace what is happening. Do you get the correct IP when you disable DNSSEC in Pi-hole or why do you correlate this to DNSSEC?

**Comment by Virsacer** [comment]
Yes, when I disabled "Use DNSSEC" to test, I got the IP

**Comment by DL6ER** [comment]
You can send me the complete domain to `<my username>@<my username>.de` and I'll look at what I can find out tomorrow. I'll make sure to anonymize your domain in the same way as you did to not leak any private information.

**Comment by Virsacer** [comment]
I added the same CNAME to a domain that I can share:

status.virsacer.net

**Comment by Virsacer** [comment]
Afer a lot more "dig"-ing I found out, that my zone-slave (which I have as backup in "Conditional Forwarding") does not allow recursion.
So when I disabled DNSSEC to test, I apparently got the response from my zone-master and it worked...
