### ISSUE TITLE
Failed to build 5.2 release on ubuntu 20.04

### ISSUE THREAD

**Issue by laoshaw** [pi-hole/FTL#928]
I downloaded 5.2 from github and untar-ed it to a directory, run build.sh and I got this

```
inlined from ‘getVersion’ at /home/test/FTL-5.2/src/api/api.c:1062:2:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:34:10: error: ‘__builtin_memcpy’ forming offset [2, 7] is out of the bounds [0, 1] [-Werror=array-bounds]
   34 |   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
```

I then git clone the git repository and it built fine.

The problem is with src/version.h.in, for released files those variables are empty, and gcc/memcpy does not like that.

maybe in the release version.in.h file it should be pre-filled release info manually? after I manually put stuff in I can build fine.

**Comment by DL6ER** [comment]
Thanks for pointing this out. I have never tried to build FTL from the downloadable tar file.

> maybe in the release version.in.h file it should be pre-filled release info manually?

That's an obvious solution, however, I think it is somewhat dirty. I know from other projects that there is (typically immediately before a release) a change in the source code just to bump the number. It is another moving gear that could get forgotten...

I can see mostly three ways to go forward:

1. Disable tar/zip downloads (is that even possible?).
    That'd be my preferred option.
2. Force users to use `git`
    It is easy to detect the absence of `git` information during build. We could show them a clear error message like
    > Pi-hole FTL needs `git` information to build the correct binary. Please download FTL using `git`, like
    > `git clone --depth 1 https://github.com/pi-hole/FTL.git`
    Using specifically `--depth 1` to get a shallow clone (saves a lot of space).
3. Just fix the code to work without version information.
    This will lead to `pihole-FTL -v` returning nothing really useful, so it'd be my least favored version.

@dschaper @PromoFaux Your input is appreciated.

**Comment by dschaper** [comment]
>     1. Disable tar/zip downloads (is that even possible?).

No, it's a "feature" of using releases. Every release generates an archive, missing the `.git` folder of course.

https://github.community/t/disable-tarball/139966

**Comment by DL6ER** [comment]
Ah, yes, I see...

> I’d recommend instructing users experiencing those issues to clone the repo instead.

**Comment by DL6ER** [comment]
The next version of FTL has been released. Please update and run
```
pihole checkout master
```
to get back on-track if you switched to a custom branch. The fix/feature branch you switched to will not receive any further updates.

Thanks for helping us to make Pi-hole better for us all!

If you have any issues, please either reopen this ticket or (preferably) create a new ticket describing the issues in further detail and only reference this ticket. This will help us to help you best.
