### ISSUE TITLE
pihole-FTL pidfile vs dnsmasq -x pidfile in drop-in mode

### ISSUE THREAD

**Issue by laoshaw** [pi-hole/FTL#930]
I'm using the newest FTL and made a symlink: `ln -s pihole-FTL dnsmasq` to run it as 'drop-in' dnsmasq, I ran 'dnsmasq -C /etc/dnsmasq.conf -k -x /tmp/dnsmasq.pid'

the pilhole-FTL.pid is different from dnsmasq.pid and in fact dnsmasq.pid process does not exist in the system shortly after so only pihole-FTL.pid is running, these may lead to issues with existing dnsmasq scripts where dnsmasq.pid is used to manage the process.

Should pihole-FTL.pid fill in the place somehow where dnsmasq.pid is expected in drop-in mode?

**Comment by dschaper** [comment]
No, `pihole-FTL` is not `dnsmasq` and will not impersonate `dnsmasq` by dropping PID files. You can run `pihole-FTL` with `dnsmasq` commands but symlinking `pihole-FTL` in and calling it `dnsmasq` will not be supported nor will it work.

If you keep opening issues and ignoring the templates as the process we ask of you we will prevent you from opening new issues.
