### ISSUE TITLE
Audit Log "audit" function crashes FTTL

### ISSUE THREAD

**Issue by Thomas-Schubert** [pi-hole/FTL#947]
### Versions
- Pi-hole:  5.2
- AdminLTE:  5.2
- FTL:  5.3.1

### Platform
- OS and version:  Debian Stretch
- Platform:  Raspberry Pi

### Expected behavior

Adding entry to audit log processes the entry.

### Actual behavior / bug
FTL crashes.
Segmentation fault (0xd1) with code "SEGV_MAPPER (address not mapped to object).
### Steps to reproduce

1. Go to 'Audit Log"
2. Click on 'add to audit log in "blocked queries" section"
3. Open Log

## Debug Token

- URL:   https://tricorder.pi-hole.net/97v9dngr00

See log file
[pihole-FTL.log] (https://github.com/pi-hole/FTL/files/5615689/pihole-FTL.log) enclosed.

**Comment by DL6ER** [comment]
Thanks for your report and sorry for the inconvenience you experienced. I tried to reproduce the crash but couldn't. Is this crash repeatable or does it only happen sometimes? Does it happen for any blocked domain or only for specific ones?

**Comment by Thomas-Schubert** [comment]
Thanks for the response ... It happened twice to me with the same user interaction within 20 minutes, I guess it is reproducible, though I'm not sure whether it happened with different domains or the same domains. It's the DNS resolver that also has energy monitoring tasks, so I cannot shoot it down too often...
