### ISSUE TITLE
pihole-FTL.log - Host name of client "W.X.Y.Z" => "     localhost localhost.localdomain localhost6 localhost6.local" contains (at least) one invalid character at position 0

### ISSUE THREAD

**Issue by frollic** [pi-hole/FTL#956]
### Versions

- Pi-hole:  5.2
- AdminLTE:  5.2
- FTL:  5.3.1

### Platform
- OS and version:  Debian 7
- Platform:  Oracle cloud x86_64
 
### Expected behavior
Not sure if it's a bug, just want to know where the error/warning comes from ...

### Actual behavior / bug
[root@instance etc]# **tail -f /var/log/pihole-FTL.log |grep invalid**
[2020-12-02 06:00:00.996 6527/T6531] HOSTNAME WARNING: Host name of client "1.2.3.4" => "     localhost localhost.localdomain localhost6 localhost6.local" contains (at least) one invalid character at position 0
[2020-12-02 07:00:02.196 6527/T6531] HOSTNAME WARNING: Host name of client "4.5.6.7" => "     localhost localhost.localdomain localhost6 localhost6.local" contains (at least) one invalid character at position 0
[2020-12-02 08:00:00.931 6527/T6533] HOSTNAME WARNING: Host name of client "8.9.10.11" => "     localhost localhost.localdomain localhost6 localhost6.local" contains (at least) one invalid character at position 0
[2020-12-02 08:00:01.020 6527/T6533] HOSTNAME WARNING: Host name of client "12.13..14.15" => "     localhost localhost.localdomain localhost6 localhost6.local" contains (at least) one invalid character at position 0

The IPs aren't from the hosts file, it only have two enties, one is 127.0.0.1 2nd is 10.0.0.3

![image](https://user-images.githubusercontent.com/7432497/100847272-e1e05b00-347f-11eb-929c-0df2b0a8ef19.png)
****

**Comment by DL6ER** [comment]
**IMPORTANT** It seems your Pi-hole is reachable from the Internet without any filtering. These IP addresses (from the screenshot) belong to `netsystemsresearch.com` which is a networking scanner. First, make sure your Pi-hole's port 53 is not accessible from the Internet. Instead, use a VPN to connect to your device.

Then, please check `/var/log/pihole.log` for who replied to these name resolution queries.

**Comment by frollic** [comment]
Yes, we've previously establishesd it's open to the internet ... ;)

There's often, but not always a **dnsmasq[6527]: reply error is SERVFAIL** in the vicinity of the requests from the IPs on the list.
But also a warning about the lenght of th host name.
 
[root@instance log]# cat pihole-FTL.log | grep "139.162.60.27"
[2020-12-02 12:00:01.046 6527/T6531] WARNING: Hostname of client 139.162.60.27 too long, truncating to 64 chars!
[2020-12-02 12:00:01.046 6527/T6531] HOSTNAME WARNING: Host name of client "139.162.60.27" => "     localhost localhost.localdomain localhost6 localhost6.local" contains (at least) one invalid character at position 0

[root@instance log]# cat pihole-FTL.log | grep "79.102.213.83"
[2020-12-02 07:00:02.126 6527/T6531] WARNING: Hostname of client 79.102.213.83 too long, truncating to 64 chars!
[2020-12-02 07:00:02.196 6527/T6531] HOSTNAME WARNING: Host name of client "79.102.213.83" => "     localhost localhost.localdomain localhost6 localhost6.local" contains (at least) one invalid character at position 0

**Comment by DL6ER** [comment]
Ah, yes, sorry, so many users out there ;-)

This is still somewhat odd. Are there really no lines in `/var/log/pihole.log` (not `FTL.log`)? Please run
```
grep "139.162.60.27" /var/log/pihole.log
```
and also
```
grep "27.60.162.139" /var/log/pihole.log
```

**Comment by frollic** [comment]
There are, but nothing that would stand out in a crowd ... 

[root@instance log]# grep "139.162.60.27" /var/log/pihole.log
Dec  2 01:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
Dec  2 02:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
Dec  2 03:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
Dec  2 04:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
Dec  2 05:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
Dec  2 06:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
Dec  2 07:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
Dec  2 08:00:01 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
Dec  2 09:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
Dec  2 10:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
Dec  2 11:00:01 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
Dec  2 12:00:01 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
Dec  2 13:00:01 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
[root@instance log]#

[root@instance log]# grep "27.60.162.139" /var/log/pihole.log
Dec  2 01:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
Dec  2 02:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
Dec  2 03:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
Dec  2 04:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
Dec  2 05:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
Dec  2 06:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
Dec  2 07:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
Dec  2 08:00:01 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
Dec  2 09:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
Dec  2 10:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
Dec  2 11:00:01 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
Dec  2 12:00:01 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
Dec  2 13:00:01 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
[root@instance log]#

**Comment by DL6ER** [comment]
That's already something, how about
```
grep -nA 5 "27.60.162.139" /var/log/pihole.log
```
? It should give some more details (print 5 context lines after each search result + line numbers)

**Comment by frollic** [comment]
[root@instance log]# grep -nA 5 "27.60.162.139" /var/log/pihole.log
16974:Dec  2 01:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
16975-Dec  2 01:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
16976-Dec  2 01:00:00 dnsmasq[6527]: query[PTR] 9.64.73.184.in-addr.arpa from 127.0.0.1
16977-Dec  2 01:00:00 dnsmasq[6527]: forwarded 9.64.73.184.in-addr.arpa to 208.67.222.222
16978-Dec  2 01:00:00 dnsmasq[6527]: reply 184.73.64.9 is ec2-184-73-64-9.compute-1.amazonaws.com
16979-Dec  2 01:00:00 dnsmasq[6527]: query[PTR] 41.66.108.198.in-addr.arpa from 127.0.0.1
--
28284:Dec  2 02:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
28285-Dec  2 02:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
28286-Dec  2 02:00:00 dnsmasq[6527]: query[PTR] 9.64.73.184.in-addr.arpa from 127.0.0.1
28287-Dec  2 02:00:00 dnsmasq[6527]: forwarded 9.64.73.184.in-addr.arpa to 208.67.220.220
28288-Dec  2 02:00:00 dnsmasq[6527]: reply 184.73.64.9 is ec2-184-73-64-9.compute-1.amazonaws.com
28289-Dec  2 02:00:00 dnsmasq[6527]: query[PTR] 41.66.108.198.in-addr.arpa from 127.0.0.1
--
40197:Dec  2 03:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
40198-Dec  2 03:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
40199-Dec  2 03:00:00 dnsmasq[6527]: query[PTR] 9.64.73.184.in-addr.arpa from 127.0.0.1
40200-Dec  2 03:00:00 dnsmasq[6527]: forwarded 9.64.73.184.in-addr.arpa to 208.67.220.220
40201-Dec  2 03:00:00 dnsmasq[6527]: reply 184.73.64.9 is ec2-184-73-64-9.compute-1.amazonaws.com
40202-Dec  2 03:00:00 dnsmasq[6527]: query[PTR] 41.66.108.198.in-addr.arpa from 127.0.0.1
--
50813:Dec  2 04:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
50814-Dec  2 04:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
50815-Dec  2 04:00:00 dnsmasq[6527]: query[PTR] 9.64.73.184.in-addr.arpa from 127.0.0.1
50816-Dec  2 04:00:00 dnsmasq[6527]: forwarded 9.64.73.184.in-addr.arpa to 208.67.220.220
50817-Dec  2 04:00:00 dnsmasq[6527]: reply 184.73.64.9 is ec2-184-73-64-9.compute-1.amazonaws.com
50818-Dec  2 04:00:00 dnsmasq[6527]: query[PTR] 41.66.108.198.in-addr.arpa from 127.0.0.1
--
61816:Dec  2 05:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
61817-Dec  2 05:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
61818-Dec  2 05:00:00 dnsmasq[6527]: query[PTR] 9.64.73.184.in-addr.arpa from 127.0.0.1
61819-Dec  2 05:00:00 dnsmasq[6527]: forwarded 9.64.73.184.in-addr.arpa to 208.67.220.220
61820-Dec  2 05:00:00 dnsmasq[6527]: reply 184.73.64.9 is ec2-184-73-64-9.compute-1.amazonaws.com
61821-Dec  2 05:00:00 dnsmasq[6527]: query[PTR] 41.66.108.198.in-addr.arpa from 127.0.0.1
--
71910:Dec  2 06:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
71911-Dec  2 06:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
71912-Dec  2 06:00:00 dnsmasq[6527]: query[PTR] 9.64.73.184.in-addr.arpa from 127.0.0.1
71913-Dec  2 06:00:00 dnsmasq[6527]: forwarded 9.64.73.184.in-addr.arpa to 208.67.220.220
71914-Dec  2 06:00:00 dnsmasq[6527]: reply 184.73.64.9 is ec2-184-73-64-9.compute-1.amazonaws.com
71915-Dec  2 06:00:01 dnsmasq[6527]: query[PTR] 222.222.67.208.in-addr.arpa from 127.0.0.1
--
85055:Dec  2 07:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
85056-Dec  2 07:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
85057-Dec  2 07:00:00 dnsmasq[6527]: query[PTR] 9.64.73.184.in-addr.arpa from 127.0.0.1
85058-Dec  2 07:00:00 dnsmasq[6527]: forwarded 9.64.73.184.in-addr.arpa to 208.67.220.220
85059-Dec  2 07:00:00 dnsmasq[6527]: reply 184.73.64.9 is ec2-184-73-64-9.compute-1.amazonaws.com
85060-Dec  2 07:00:00 dnsmasq[6527]: query[PTR] 41.66.108.198.in-addr.arpa from 127.0.0.1
--
96735:Dec  2 08:00:01 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
96736-Dec  2 08:00:01 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
96737-Dec  2 08:00:01 dnsmasq[6527]: query[PTR] 9.64.73.184.in-addr.arpa from 127.0.0.1
96738-Dec  2 08:00:01 dnsmasq[6527]: forwarded 9.64.73.184.in-addr.arpa to 208.67.222.222
96739-Dec  2 08:00:01 dnsmasq[6527]: reply 184.73.64.9 is ec2-184-73-64-9.compute-1.amazonaws.com
96740-Dec  2 08:00:01 dnsmasq[6527]: query[PTR] 41.66.108.198.in-addr.arpa from 127.0.0.1
--
108962:Dec  2 09:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
108963-Dec  2 09:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
108964-Dec  2 09:00:00 dnsmasq[6527]: query[PTR] 9.64.73.184.in-addr.arpa from 127.0.0.1
108965-Dec  2 09:00:00 dnsmasq[6527]: forwarded 9.64.73.184.in-addr.arpa to 208.67.220.220
108966-Dec  2 09:00:00 dnsmasq[6527]: reply 184.73.64.9 is ec2-184-73-64-9.compute-1.amazonaws.com
108967-Dec  2 09:00:00 dnsmasq[6527]: query[PTR] 41.66.108.198.in-addr.arpa from 127.0.0.1
--
120910:Dec  2 10:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
120911-Dec  2 10:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
120912-Dec  2 10:00:00 dnsmasq[6527]: query[PTR] 9.64.73.184.in-addr.arpa from 127.0.0.1
120913-Dec  2 10:00:00 dnsmasq[6527]: forwarded 9.64.73.184.in-addr.arpa to 208.67.222.222
120914-Dec  2 10:00:00 dnsmasq[6527]: reply 184.73.64.9 is ec2-184-73-64-9.compute-1.amazonaws.com
120915-Dec  2 10:00:00 dnsmasq[6527]: query[PTR] 41.66.108.198.in-addr.arpa from 127.0.0.1
--
133592:Dec  2 11:00:01 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
133593-Dec  2 11:00:01 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
133594-Dec  2 11:00:01 dnsmasq[6527]: query[PTR] 9.64.73.184.in-addr.arpa from 127.0.0.1
133595-Dec  2 11:00:01 dnsmasq[6527]: forwarded 9.64.73.184.in-addr.arpa to 208.67.220.220
133596-Dec  2 11:00:01 dnsmasq[6527]: reply 184.73.64.9 is ec2-184-73-64-9.compute-1.amazonaws.com
133597-Dec  2 11:00:01 dnsmasq[6527]: query[PTR] 41.66.108.198.in-addr.arpa from 127.0.0.1
--
144050:Dec  2 12:00:01 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
144051-Dec  2 12:00:01 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
144052-Dec  2 12:00:01 dnsmasq[6527]: query[PTR] 220.220.67.208.in-addr.arpa from 127.0.0.1
144053-Dec  2 12:00:01 dnsmasq[6527]: cached 208.67.220.220 is resolver2.opendns.com
144054-Dec  2 12:00:01 dnsmasq[6527]: query[PTR] 9.64.73.184.in-addr.arpa from 127.0.0.1
144055-Dec  2 12:00:01 dnsmasq[6527]: forwarded 9.64.73.184.in-addr.arpa to 208.67.222.222
--
155812:Dec  2 13:00:01 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
155813-Dec  2 13:00:01 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
155814-Dec  2 13:00:01 dnsmasq[6527]: query[PTR] 9.64.73.184.in-addr.arpa from 127.0.0.1
155815-Dec  2 13:00:01 dnsmasq[6527]: forwarded 9.64.73.184.in-addr.arpa to 208.67.220.220
155816-Dec  2 13:00:01 dnsmasq[6527]: reply 184.73.64.9 is ec2-184-73-64-9.compute-1.amazonaws.com
155817-Dec  2 13:00:01 dnsmasq[6527]: query[PTR] 41.66.108.198.in-addr.arpa from 127.0.0.1
--
167332:Dec  2 14:00:00 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
167333-Dec  2 14:00:00 dnsmasq[6527]: cached 139.162.60.27 is li1473-27.members.linode.com
167334-Dec  2 14:00:00 dnsmasq[6527]: query[PTR] 9.64.73.184.in-addr.arpa from 127.0.0.1
167335-Dec  2 14:00:00 dnsmasq[6527]: forwarded 9.64.73.184.in-addr.arpa to 208.67.222.222
167336-Dec  2 14:00:00 dnsmasq[6527]: reply 184.73.64.9 is ec2-184-73-64-9.compute-1.amazonaws.com
167337-Dec  2 14:00:00 dnsmasq[6527]: query[PTR] 41.66.108.198.in-addr.arpa from 127.0.0.1
--
180856:Dec  2 15:00:01 dnsmasq[6527]: query[PTR] 27.60.162.139.in-addr.arpa from 127.0.0.1
180857:Dec  2 15:00:01 dnsmasq[6527]: forwarded 27.60.162.139.in-addr.arpa to 208.67.220.220
180858-Dec  2 15:00:01 dnsmasq[6527]: reply 139.162.60.27 is li1473-27.members.linode.com
180859-Dec  2 15:00:01 dnsmasq[6527]: query[PTR] 9.64.73.184.in-addr.arpa from 127.0.0.1
180860-Dec  2 15:00:01 dnsmasq[6527]: forwarded 9.64.73.184.in-addr.arpa to 208.67.220.220
180861-Dec  2 15:00:01 dnsmasq[6527]: reply 184.73.64.9 is ec2-184-73-64-9.compute-1.amazonaws.com
180862-Dec  2 15:00:01 dnsmasq[6527]: query[PTR] 220.220.67.208.in-addr.arpa from 127.0.0.1
[root@instance log]#

**Comment by DL6ER** [comment]
You should enclose your stuff in ` ``` ` (once above and once below) to get the correct formatting.

I really don't know what happened here. Some foreign (?) resolver seems to have replied with said string ` localhost localhost.localdomain localhost6 localhost6.local`
As spaces are invalid in hostnames, FTL correctly complained about the character at position zero (which is a string). We seem unable to reproduce/find the PTR returning the space string, so I'm not really sure what we can do. Probably nothing and, as you already said,

> Not sure if it's a bug, just want to know where the error/warning comes from ...

I think we did that. Point is that DNS servers are allowed to send *anything* as reply. They are not limited to valid stuff. They can very well also send Umlauts (ä ö ü ß) or non-printable characters like newline and other control characters. It just doesn't make sense and FTL is filtering them out to prevent them doing anything nasty (even when SQL or HTTP injections are not possible).
