### ISSUE TITLE
Pihole services stop working when enabling a group in group management

### ISSUE THREAD

**Issue by htyac** [pi-hole/FTL#973]
### Versions
 Pi-hole version is v5.2.1 (Latest: v5.2.1)
  AdminLTE version is v5.2.1 (Latest: v5.2.1)
  FTL version is v5.3.2 (Latest: v5.3.2)

### Platform
- OS and version:  Raspbian GNU/Linux 10 (buster)
- Platform:  Raspberry Pi

### Expected behavior

Various IP addresses belongs to group Default and Group1.
Group1 is disabled.
I want to enable Group1 containing these clients and linked to different blocked domains regex .

### Actual behavior / bug

When re enabling the group that was disabled, all pihole services stop working.
I have to force a pihole restart issuing the command : sudo pihole restartdns
And then the group is enabled and pihole is blocking the domains properly.

### Steps to reproduce

1. Go to Group Management / Groups
2. Click on 'Disable/Enable' toggle button to enable the group

## Debug Token

- URL:  https://tricorder.pi-hole.net/5ugkfrvhby

**Comment by DL6ER** [comment]
And once again a `pihole -up` and test please. It isn't clear where FTL stops for you, however, the last message was precisely in front of a small bug we fixed only yesterday (#971). I absorbed this fix into your test branch so we'll see if it fixes your issue.

**Comment by gluedig** [comment]
Hey
had exactly same issue, came here looking for answers, found a fix in place already, great!
I can confirm that this is fixed on development branch for me as well.

btw. I'm wondering why ftl is not restarting automatically on crash?
or should it be but does not to for me only for some reason?
or maybe i was not patient enough?

**Comment by DL6ER** [comment]
Sorry for the delay, my inbox exploded after having had a few days without access and I'm only slowly working through it right now.

>  Must I stay on that test branch until the fix is published in master ?

Yes

>  And how do I go back to master ? pi checkout ftl master ?

Almost, but yes: `pihole checkout ftl master`

I'll ping you once this is available.

> I'm wondering why ftl is not restarting automatically on crash?

Yeah, I've been thinking about this, too. We may want to do this. Even when there shouldn't be any crashes in the first place, of course. I'm not sure if it can be done easily with SysV init scripts, pinging @dschaper for comments (if he has some).

**Comment by piotr-haber-red** [comment]
>Yeah, I've been thinking about this, too. We may want to do this. Even when there shouldn't be any crashes in the first place, of >course. I'm not sure if it can be done easily with SysV init scripts, pinging @dschaper for comments (if he has some).
Might be tricky without introducing external system dependency (like monit) or delegating to systemd (or upstart).
Maybe a wrapper script around pihole-FTL executable

**Comment by dschaper** [comment]
> 'm not sure if it can be done easily with SysV init scripts, pinging @dschaper for comments (if he has some).

I can't think of any watchdog that would work for normal installs. You can do this in docker now, but of course there is the docker daemon that watches. 

You'd need to somehow know why `pihole-FTL` isn't running. Did the init system kill it for a valid reason, did it crash, did the user stop it... And in each case you'd need to know if it was safe to restart, or if restarting would cause further damage.

**Comment by DL6ER** [comment]
The next version of FTL has been released. Please update and run
```
pihole checkout master
```
to get back on-track. Thanks for helping us to make Pi-hole better for us all!

If you have any issues, please either reopen this ticket or (preferably) create a new ticket describing the issues in further detail and only reference this ticket. This will help us to help you best.
